import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['brand'] };

export const brandDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Identify From Transaction',
				value: 'identifyFromTransaction',
				action: 'Identify a brand from transaction data',
				description:
					'Match merchant name from bank statement to a brand. <a href="https://docs.context.dev/api-reference/retrieve-brand/identify-brand-from-transaction-data" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/transaction_identifier' } },
			},
			{
				name: 'Retrieve by Company Name',
				value: 'retrieveByName',
				action: 'Retrieve brand data by company name',
				description:
					'Search by company name and retrieve brand data. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-company-name" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-name' } },
			},
			{
				name: 'Retrieve by Domain',
				value: 'retrieve',
				action: 'Retrieve brand data by domain',
				description:
					'Get logos, colors, description and more. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-domain" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve' } },
			},
			{
				name: 'Retrieve by Email',
				value: 'retrieveByEmail',
				action: 'Retrieve brand data by email address',
				description:
					'Extracts domain from email (excludes free/disposable). <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-email-address" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-email' } },
			},
			{
				name: 'Retrieve by ISIN',
				value: 'retrieveByIsin',
				action: 'Retrieve brand data by ISIN',
				description:
					'Look up by International Securities Identification Number. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-isin" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-isin' } },
			},
			{
				name: 'Retrieve by Stock Ticker',
				value: 'retrieveByTicker',
				action: 'Retrieve brand data by stock ticker',
				description:
					'Look up by stock ticker symbol. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-stock-ticker" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-ticker' } },
			},
			{
				name: 'Retrieve Simplified',
				value: 'retrieveSimplified',
				action: 'Retrieve simplified brand data',
				description:
					'Faster response with only domain, title, colors, logos, backdrops. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-simplified-brand-data-by-domain" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-simplified' } },
			},
		],
		default: 'retrieve',
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieve', 'retrieveSimplified'] } },
		default: '',
		placeholder: 'stripe.com',
		routing: { request: { qs: { domain: '={{ $value }}' } } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByEmail'] } },
		default: '',
		placeholder: 'contact@stripe.com',
		description: 'Free email providers (gmail.com, yahoo.com) and disposable addresses are not allowed',
		routing: { request: { qs: { email: '={{ $value }}' } } },
	},
	{
		displayName: 'Company Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByName'] } },
		default: '',
		placeholder: 'Stripe',
		routing: { request: { qs: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Stock Ticker',
		name: 'ticker',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByTicker'] } },
		default: '',
		placeholder: 'AAPL',
		routing: { request: { qs: { ticker: '={{ $value }}' } } },
	},
	{
		displayName: 'ISIN',
		name: 'isin',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByIsin'] } },
		default: '',
		placeholder: 'US0378331005',
		routing: { request: { qs: { isin: '={{ $value }}' } } },
	},
	{
		displayName: 'Transaction Info',
		name: 'transaction_info',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['identifyFromTransaction'] } },
		default: '',
		placeholder: 'STARBUCKS STORE #12345',
		description: 'Merchant name as it appears on a bank statement',
		routing: { request: { qs: { transaction_info: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				...show,
				operation: [
					'retrieve',
					'retrieveByEmail',
					'retrieveByName',
					'retrieveByTicker',
					'retrieveByIsin',
					'retrieveSimplified',
					'identifyFromTransaction',
				],
			},
		},
		options: [
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: 'San Francisco',
				routing: { request: { qs: { city: '={{ $value }}' } } },
			},
			{
				displayName: 'Country Code',
				name: 'country_gl',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction', 'retrieveByName'] } },
				default: '',
				placeholder: 'us',
				description: 'ISO 3166-1 alpha-2 country code',
				routing: { request: { qs: { country_gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Force Language',
				name: 'force_language',
				type: 'options',
				default: 'english',
				options: [
					{ name: 'Afrikaans', value: 'afrikaans' },
					{ name: 'Albanian', value: 'albanian' },
					{ name: 'Amharic', value: 'amharic' },
					{ name: 'Arabic', value: 'arabic' },
					{ name: 'Armenian', value: 'armenian' },
					{ name: 'Assamese', value: 'assamese' },
					{ name: 'Aymara', value: 'aymara' },
					{ name: 'Azeri', value: 'azeri' },
					{ name: 'Basque', value: 'basque' },
					{ name: 'Belarusian', value: 'belarusian' },
					{ name: 'Bengali', value: 'bengali' },
					{ name: 'Bosnian', value: 'bosnian' },
					{ name: 'Bulgarian', value: 'bulgarian' },
					{ name: 'Burmese', value: 'burmese' },
					{ name: 'Cantonese', value: 'cantonese' },
					{ name: 'Catalan', value: 'catalan' },
					{ name: 'Cebuano', value: 'cebuano' },
					{ name: 'Chinese', value: 'chinese' },
					{ name: 'Corsican', value: 'corsican' },
					{ name: 'Croatian', value: 'croatian' },
					{ name: 'Czech', value: 'czech' },
					{ name: 'Danish', value: 'danish' },
					{ name: 'Dutch', value: 'dutch' },
					{ name: 'English', value: 'english' },
					{ name: 'Esperanto', value: 'esperanto' },
					{ name: 'Estonian', value: 'estonian' },
					{ name: 'Farsi', value: 'farsi' },
					{ name: 'Fijian', value: 'fijian' },
					{ name: 'Finnish', value: 'finnish' },
					{ name: 'French', value: 'french' },
					{ name: 'Galician', value: 'galician' },
					{ name: 'Georgian', value: 'georgian' },
					{ name: 'German', value: 'german' },
					{ name: 'Greek', value: 'greek' },
					{ name: 'Guarani', value: 'guarani' },
					{ name: 'Gujarati', value: 'gujarati' },
					{ name: 'Haitian Creole', value: 'haitian-creole' },
					{ name: 'Hausa', value: 'hausa' },
					{ name: 'Hawaiian', value: 'hawaiian' },
					{ name: 'Hebrew', value: 'hebrew' },
					{ name: 'Hindi', value: 'hindi' },
					{ name: 'Hmong', value: 'hmong' },
					{ name: 'Hungarian', value: 'hungarian' },
					{ name: 'Icelandic', value: 'icelandic' },
					{ name: 'Igbo', value: 'igbo' },
					{ name: 'Indonesian', value: 'indonesian' },
					{ name: 'Irish', value: 'irish' },
					{ name: 'Italian', value: 'italian' },
					{ name: 'Japanese', value: 'japanese' },
					{ name: 'Javanese', value: 'javanese' },
					{ name: 'Kannada', value: 'kannada' },
					{ name: 'Kazakh', value: 'kazakh' },
					{ name: 'Khmer', value: 'khmer' },
					{ name: 'Kinyarwanda', value: 'kinyarwanda' },
					{ name: 'Korean', value: 'korean' },
					{ name: 'Kurdish', value: 'kurdish' },
					{ name: 'Kyrgyz', value: 'kyrgyz' },
					{ name: 'Lao', value: 'lao' },
					{ name: 'Latin', value: 'latin' },
					{ name: 'Latvian', value: 'latvian' },
					{ name: 'Lingala', value: 'lingala' },
					{ name: 'Lithuanian', value: 'lithuanian' },
					{ name: 'Luxembourgish', value: 'luxembourgish' },
					{ name: 'Macedonian', value: 'macedonian' },
					{ name: 'Malagasy', value: 'malagasy' },
					{ name: 'Malay', value: 'malay' },
					{ name: 'Malayalam', value: 'malayalam' },
					{ name: 'Maltese', value: 'maltese' },
					{ name: 'Maori', value: 'maori' },
					{ name: 'Marathi', value: 'marathi' },
					{ name: 'Mongolian', value: 'mongolian' },
					{ name: 'Nepali', value: 'nepali' },
					{ name: 'Norwegian', value: 'norwegian' },
					{ name: 'Odia', value: 'odia' },
					{ name: 'Oromo', value: 'oromo' },
					{ name: 'Pashto', value: 'pashto' },
					{ name: 'Pidgin', value: 'pidgin' },
					{ name: 'Polish', value: 'polish' },
					{ name: 'Portuguese', value: 'portuguese' },
					{ name: 'Punjabi', value: 'punjabi' },
					{ name: 'Quechua', value: 'quechua' },
					{ name: 'Romanian', value: 'romanian' },
					{ name: 'Russian', value: 'russian' },
					{ name: 'Samoan', value: 'samoan' },
					{ name: 'Scottish Gaelic', value: 'scottish-gaelic' },
					{ name: 'Serbian', value: 'serbian' },
					{ name: 'Sesotho', value: 'sesotho' },
					{ name: 'Shona', value: 'shona' },
					{ name: 'Sindhi', value: 'sindhi' },
					{ name: 'Sinhala', value: 'sinhala' },
					{ name: 'Slovak', value: 'slovak' },
					{ name: 'Slovene', value: 'slovene' },
					{ name: 'Somali', value: 'somali' },
					{ name: 'Spanish', value: 'spanish' },
					{ name: 'Sundanese', value: 'sundanese' },
					{ name: 'Swahili', value: 'swahili' },
					{ name: 'Swedish', value: 'swedish' },
					{ name: 'Tagalog', value: 'tagalog' },
					{ name: 'Tajik', value: 'tajik' },
					{ name: 'Tamil', value: 'tamil' },
					{ name: 'Tatar', value: 'tatar' },
					{ name: 'Telugu', value: 'telugu' },
					{ name: 'Thai', value: 'thai' },
					{ name: 'Tibetan', value: 'tibetan' },
					{ name: 'Tigrinya', value: 'tigrinya' },
					{ name: 'Tongan', value: 'tongan' },
					{ name: 'Tswana', value: 'tswana' },
					{ name: 'Turkish', value: 'turkish' },
					{ name: 'Turkmen', value: 'turkmen' },
					{ name: 'Ukrainian', value: 'ukrainian' },
					{ name: 'Urdu', value: 'urdu' },
					{ name: 'Uyghur', value: 'uyghur' },
					{ name: 'Uzbek', value: 'uzbek' },
					{ name: 'Vietnamese', value: 'vietnamese' },
					{ name: 'Welsh', value: 'welsh' },
					{ name: 'Wolof', value: 'wolof' },
					{ name: 'Xhosa', value: 'xhosa' },
					{ name: 'Yiddish', value: 'yiddish' },
					{ name: 'Yoruba', value: 'yoruba' },
					{ name: 'Zulu', value: 'zulu' },
				],
				routing: { request: { qs: { force_language: '={{ $value }}' } } },
			},
			{
				displayName: 'High Confidence Only',
				name: 'high_confidence_only',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: false,
				description: 'Whether to only return a brand match when confidence is high',
				routing: { request: { qs: { high_confidence_only: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				default: 7776000000,
				description: 'Max age of cached data in ms before a hard refresh. Default 3 months.',
				typeOptions: { minValue: 86400000, maxValue: 31536000000 },
				routing: { request: { qs: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether to skip time-consuming operations for a faster response at the cost of less data',
				routing: { request: { qs: { maxSpeed: '={{ $value }}' } } },
			},
			{
				displayName: 'MCC',
				name: 'mcc',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: '5814',
				description: 'Merchant Category Code',
				routing: { request: { qs: { mcc: '={{ $value }}' } } },
			},
			{
				// SDK types `phone` as number; we deliberately expose it as a string so users can
				// enter real phone formats (leading +, spaces) that aren't valid JS numbers. The
				// value is passed through verbatim as the `phone` query param.
				displayName: 'Phone',
				name: 'phone',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: '+14155551234',
				description: 'Company phone number to help identify the brand',
				routing: { request: { qs: { phone: '={{ $value }}' } } },
			},
			{
				displayName: 'Ticker Exchange',
				name: 'ticker_exchange',
				type: 'options',
				displayOptions: { show: { '/operation': ['retrieveByTicker'] } },
				default: 'NASDAQ',
				options: [
					{ name: 'AMEX (NYSE American)', value: 'AMEX' },
					{ name: 'AMS (Amsterdam)', value: 'AMS' },
					{ name: 'AQS (AQSE, UK)', value: 'AQS' },
					{ name: 'ASX (Australia)', value: 'ASX' },
					{ name: 'ATH (Athens)', value: 'ATH' },
					{ name: 'BER (Berlin)', value: 'BER' },
					{ name: 'BME (Madrid)', value: 'BME' },
					{ name: 'BRU (Brussels)', value: 'BRU' },
					{ name: 'BSE (Bombay)', value: 'BSE' },
					{ name: 'BUD (Budapest)', value: 'BUD' },
					{ name: 'BUE (Buenos Aires)', value: 'BUE' },
					{ name: 'BVC (Colombia)', value: 'BVC' },
					{ name: 'CBOE (Chicago)', value: 'CBOE' },
					{ name: 'CNQ (Canadian Securities Exchange)', value: 'CNQ' },
					{ name: 'CPH (Copenhagen)', value: 'CPH' },
					{ name: 'DFM (Dubai)', value: 'DFM' },
					{ name: 'DOH (Doha)', value: 'DOH' },
					{ name: 'DUB (Dublin)', value: 'DUB' },
					{ name: 'DUS (Dusseldorf)', value: 'DUS' },
					{ name: 'DXE (Cboe Europe Equities)', value: 'DXE' },
					{ name: 'EGX (Egypt)', value: 'EGX' },
					{ name: 'FSX (Frankfurt)', value: 'FSX' },
					{ name: 'HAM (Hamburg)', value: 'HAM' },
					{ name: 'HEL (Helsinki)', value: 'HEL' },
					{ name: 'HKSE (Hong Kong)', value: 'HKSE' },
					{ name: 'HOSE (Ho Chi Minh)', value: 'HOSE' },
					{ name: 'ICE (Iceland)', value: 'ICE' },
					{ name: 'IOB (International Order Book, LSE)', value: 'IOB' },
					{ name: 'IST (Istanbul)', value: 'IST' },
					{ name: 'JKT (Jakarta)', value: 'JKT' },
					{ name: 'JNB (Johannesburg)', value: 'JNB' },
					{ name: 'JPX (Tokyo)', value: 'JPX' },
					{ name: 'KLS (Kuala Lumpur)', value: 'KLS' },
					{ name: 'KOE (Korea OTC/KONEX)', value: 'KOE' },
					{ name: 'KSC (Korea Stock Exchange - KOSPI)', value: 'KSC' },
					{ name: 'KUW (Kuwait)', value: 'KUW' },
					{ name: 'LIS (Lisbon)', value: 'LIS' },
					{ name: 'LSE (London)', value: 'LSE' },
					{ name: 'MCX (Moscow)', value: 'MCX' },
					{ name: 'MEX (Mexico)', value: 'MEX' },
					{ name: 'MIL (Milan)', value: 'MIL' },
					{ name: 'MUN (Munich)', value: 'MUN' },
					{ name: 'NASDAQ', value: 'NASDAQ' },
					{ name: 'NEO (Canada)', value: 'NEO' },
					{ name: 'NSE (India)', value: 'NSE' },
					{ name: 'NYSE', value: 'NYSE' },
					{ name: 'NZE (New Zealand)', value: 'NZE' },
					{ name: 'OSL (Oslo)', value: 'OSL' },
					{ name: 'OTC (Over-the-Counter, US)', value: 'OTC' },
					{ name: 'PAR (Paris)', value: 'PAR' },
					{ name: 'PNK (Pink Sheets, US)', value: 'PNK' },
					{ name: 'PRA (Prague)', value: 'PRA' },
					{ name: 'RIS (Riga)', value: 'RIS' },
					{ name: 'SAO (Sao Paulo)', value: 'SAO' },
					{ name: 'SAU (Saudi Arabia)', value: 'SAU' },
					{ name: 'SES (Singapore)', value: 'SES' },
					{ name: 'SET (Thailand)', value: 'SET' },
					{ name: 'SGO (Santiago)', value: 'SGO' },
					{ name: 'SHH (Shanghai)', value: 'SHH' },
					{ name: 'SHZ (Shenzhen)', value: 'SHZ' },
					{ name: 'SIX (Switzerland)', value: 'SIX' },
					{ name: 'STO (Stockholm)', value: 'STO' },
					{ name: 'STU (Stuttgart)', value: 'STU' },
					{ name: 'TAI (Taiwan)', value: 'TAI' },
					{ name: 'TAL (Tallinn)', value: 'TAL' },
					{ name: 'TLV (Tel Aviv)', value: 'TLV' },
					{ name: 'TSX (Toronto)', value: 'TSX' },
					{ name: 'TSXV (TSX Venture)', value: 'TSXV' },
					{ name: 'TWO (Taipei OTC)', value: 'TWO' },
					{ name: 'VIE (Vienna)', value: 'VIE' },
					{ name: 'WSE (Warsaw)', value: 'WSE' },
					{ name: 'XETRA (Deutsche Börse)', value: 'XETRA' },
				],
				routing: { request: { qs: { ticker_exchange: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { qs: { timeoutMS: '={{ $value }}' } } },
			},
		],
	},
];
