import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['brand'] };

export const brandDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Retrieve by Domain',
				value: 'retrieve',
				action: 'Retrieve brand data by domain',
				description:
					'Get logos, colors, description and more. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-domain" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve' } },
			},
			{
				name: 'Retrieve by Email',
				value: 'retrieveByEmail',
				action: 'Retrieve brand data by email address',
				description:
					'Extracts domain from email (excludes free/disposable). <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-email-address" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-email' } },
			},
			{
				name: 'Retrieve by Company Name',
				value: 'retrieveByName',
				action: 'Retrieve brand data by company name',
				description:
					'Search by company name and retrieve brand data. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-company-name" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-name' } },
			},
			{
				name: 'Retrieve by Stock Ticker',
				value: 'retrieveByTicker',
				action: 'Retrieve brand data by stock ticker',
				description:
					'Look up by stock ticker symbol. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-stock-ticker" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-ticker' } },
			},
			{
				name: 'Retrieve by ISIN',
				value: 'retrieveByIsin',
				action: 'Retrieve brand data by ISIN',
				description:
					'Look up by International Securities Identification Number. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-brand-data-by-isin" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-by-isin' } },
			},
			{
				name: 'Retrieve Simplified',
				value: 'retrieveSimplified',
				action: 'Retrieve simplified brand data',
				description:
					'Faster response with only domain, title, colors, logos, backdrops. <a href="https://docs.context.dev/api-reference/retrieve-brand/retrieve-simplified-brand-data-by-domain" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/retrieve-simplified' } },
			},
			{
				name: 'Identify from Transaction',
				value: 'identifyFromTransaction',
				action: 'Identify a brand from transaction data',
				description:
					'Match merchant name from bank statement to a brand. <a href="https://docs.context.dev/api-reference/retrieve-brand/identify-brand-from-transaction-data" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/brand/transaction_identifier' } },
			},
		],
		default: 'retrieve',
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieve', 'retrieveSimplified'] } },
		default: '',
		placeholder: 'stripe.com',
		routing: { request: { qs: { domain: '={{ $value }}' } } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByEmail'] } },
		default: '',
		placeholder: 'contact@stripe.com',
		description: 'Free email providers (gmail.com, yahoo.com) and disposable addresses are not allowed',
		routing: { request: { qs: { email: '={{ $value }}' } } },
	},
	{
		displayName: 'Company Name',
		name: 'name',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByName'] } },
		default: '',
		placeholder: 'Stripe',
		routing: { request: { qs: { name: '={{ $value }}' } } },
	},
	{
		displayName: 'Stock Ticker',
		name: 'ticker',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByTicker'] } },
		default: '',
		placeholder: 'AAPL',
		routing: { request: { qs: { ticker: '={{ $value }}' } } },
	},
	{
		displayName: 'ISIN',
		name: 'isin',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['retrieveByIsin'] } },
		default: '',
		placeholder: 'US0378331005',
		routing: { request: { qs: { isin: '={{ $value }}' } } },
	},
	{
		displayName: 'Transaction Info',
		name: 'transaction_info',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['identifyFromTransaction'] } },
		default: '',
		placeholder: 'STARBUCKS STORE #12345',
		description: 'Merchant name as it appears on a bank statement',
		routing: { request: { qs: { transaction_info: '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				...show,
				operation: [
					'retrieve',
					'retrieveByEmail',
					'retrieveByName',
					'retrieveByTicker',
					'retrieveByIsin',
					'retrieveSimplified',
					'identifyFromTransaction',
				],
			},
		},
		options: [
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: 'San Francisco',
				routing: { request: { qs: { city: '={{ $value }}' } } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: 'United States',
				routing: { request: { qs: { country: '={{ $value }}' } } },
			},
			{
				displayName: 'Country Code',
				name: 'country_gl',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: 'us',
				description: 'ISO 3166-1 alpha-2 country code',
				routing: { request: { qs: { country_gl: '={{ $value }}' } } },
			},
			{
				displayName: 'Force Language',
				name: 'force_language',
				type: 'options',
				default: 'english',
				options: [
					{ name: 'Arabic', value: 'arabic' },
					{ name: 'Chinese', value: 'chinese' },
					{ name: 'Czech', value: 'czech' },
					{ name: 'Danish', value: 'danish' },
					{ name: 'Dutch', value: 'dutch' },
					{ name: 'English', value: 'english' },
					{ name: 'Finnish', value: 'finnish' },
					{ name: 'French', value: 'french' },
					{ name: 'German', value: 'german' },
					{ name: 'Greek', value: 'greek' },
					{ name: 'Hebrew', value: 'hebrew' },
					{ name: 'Hindi', value: 'hindi' },
					{ name: 'Hungarian', value: 'hungarian' },
					{ name: 'Indonesian', value: 'indonesian' },
					{ name: 'Italian', value: 'italian' },
					{ name: 'Japanese', value: 'japanese' },
					{ name: 'Korean', value: 'korean' },
					{ name: 'Norwegian', value: 'norwegian' },
					{ name: 'Polish', value: 'polish' },
					{ name: 'Portuguese', value: 'portuguese' },
					{ name: 'Romanian', value: 'romanian' },
					{ name: 'Russian', value: 'russian' },
					{ name: 'Spanish', value: 'spanish' },
					{ name: 'Swedish', value: 'swedish' },
					{ name: 'Thai', value: 'thai' },
					{ name: 'Turkish', value: 'turkish' },
					{ name: 'Ukrainian', value: 'ukrainian' },
					{ name: 'Vietnamese', value: 'vietnamese' },
				],
				routing: { request: { qs: { force_language: '={{ $value }}' } } },
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: 0,
				routing: { request: { qs: { latitude: '={{ $value }}' } } },
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: 0,
				routing: { request: { qs: { longitude: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				default: 7776000000,
				description: 'Max age of cached data in ms before a hard refresh. Default 3 months.',
				typeOptions: { minValue: 86400000, maxValue: 31536000000 },
				routing: { request: { qs: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether to skip time-consuming operations for a faster response at the cost of less data',
				routing: { request: { qs: { maxSpeed: '={{ $value }}' } } },
			},
			{
				displayName: 'MCC',
				name: 'mcc',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: '5814',
				description: 'Merchant Category Code',
				routing: { request: { qs: { mcc: '={{ $value }}' } } },
			},
			{
				displayName: 'Postal Code',
				name: 'postal_code',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				routing: { request: { qs: { postal_code: '={{ $value }}' } } },
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				displayOptions: { show: { '/operation': ['identifyFromTransaction'] } },
				default: '',
				placeholder: 'CA',
				routing: { request: { qs: { state: '={{ $value }}' } } },
			},
			{
				displayName: 'Ticker Exchange',
				name: 'ticker_exchange',
				type: 'options',
				displayOptions: { show: { '/operation': ['retrieveByTicker'] } },
				default: 'NASDAQ',
				options: [
					{ name: 'AMEX', value: 'AMEX' },
					{ name: 'ASX (Australia)', value: 'ASX' },
					{ name: 'FSX (Frankfurt)', value: 'FSX' },
					{ name: 'HKSE (Hong Kong)', value: 'HKSE' },
					{ name: 'JPX (Tokyo)', value: 'JPX' },
					{ name: 'LSE (London)', value: 'LSE' },
					{ name: 'NASDAQ', value: 'NASDAQ' },
					{ name: 'NSE (India)', value: 'NSE' },
					{ name: 'NYSE', value: 'NYSE' },
					{ name: 'SGX (Singapore)', value: 'SGX' },
					{ name: 'SSE (Shanghai)', value: 'SSE' },
					{ name: 'TSX (Toronto)', value: 'TSX' },
				],
				routing: { request: { qs: { ticker_exchange: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				default: 30000,
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { qs: { timeoutMS: '={{ $value }}' } } },
			},
		],
	},
];
