import type { INodeProperties } from 'n8n-workflow';

export const utilityDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['utility'] } },
			options: [
			{ name: 'Prefetch Brand Data by Email', value: 'prefetchBrandDataByEmail', action: 'Prefetch brand data by email', description: 'Signal that you may fetch brand data for a particular domain soon to improve latency. This endpoint accepts an email address, extracts the domain from it, validates that it\'s not a disposable or free email provider, and queues the domain for prefetching.', routing: { request: { method: 'POST', url: '/brand/prefetch-by-email' } } },
			{ name: 'Prefetch Brand Data for a Domain', value: 'prefetchBrandDataForADomain', action: 'Prefetch brand data for a domain', description: 'Signal that you may fetch brand data for a particular domain soon to improve latency', routing: { request: { method: 'POST', url: '/brand/prefetch' } } },
			{ name: 'Prefetch Data', value: 'prefetchData', action: 'Prefetch data', description: 'Signal that you may fetch data soon to improve latency. The type field selects what to prefetch (\'brand\' queues a brand data fetch, \'styleguide\' queues a styleguide extraction) and identifier carries exactly one lookup key: a domain, or an email whose domain is extracted and validated (free email providers and disposable email addresses are not allowed).', routing: { request: { method: 'POST', url: '/utility/prefetch' } } },
			],
			default: 'prefetchBrandDataForADomain',
		},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchBrandDataForADomain'] } },
		required: true,
		default: "",
		description: 'Domain name to prefetch brand data for',
		routing: { send: { property: 'domain', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchBrandDataForADomain'] } },
		options: [
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchBrandDataByEmail'] } },
		required: true,
		default: "",
		description: 'Email address to prefetch brand data for. The domain will be extracted from the email. Free email providers (gmail.com, yahoo.com, etc.) and disposable email addresses are not allowed.',
		routing: { send: { property: 'email', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchBrandDataByEmail'] } },
		options: [
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchData'] } },
		required: true,
		default: "brand",
		options: [{ name: 'Brand', value: "brand" }, { name: 'Styleguide', value: "styleguide" }],
		description: 'What to prefetch: \'brand\' warms the brand data cache, \'styleguide\' warms the styleguide cache',
		routing: { send: { property: 'type', type: 'body' } },
	},
	{
		displayName: 'Domain',
		name: 'identifierDomain',
		type: 'string',
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchData'] } },
		required: true,
		default: "",
		description: 'Domain name to prefetch data for',
		routing: { send: { property: 'identifier.domain', type: 'body' } },
	},
	{
		displayName: 'Email',
		name: 'identifierEmail',
		type: 'string',
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchData'] } },
		required: true,
		default: "",
		description: 'Email address to prefetch data for. The domain will be extracted from the email. Free email providers (gmail.com, yahoo.com, etc.) and disposable email addresses are not allowed.',
		routing: { send: { property: 'identifier.email', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['utility'], operation: ['prefetchData'] } },
		options: [
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
];
