import type { INodeProperties } from 'n8n-workflow';

export const peopleDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['people'] } },
			options: [
			{ name: 'Enrich Person', value: 'enrichPerson', action: 'Enrich person', description: 'Finds and normalizes the best available person candidate from additive identity clues, then assigns an identity match score from 0 to 100. Available on all paid plans. Successful requests cost 20 credits. Disposable and free email addresses (like gmail.com, yahoo.com) will throw a 422 error', routing: { request: { method: 'POST', url: '/people/enrich' } } },
			{ name: 'Retrieve Person', value: 'retrievePerson', action: 'Retrieve person', description: 'Retrieve and normalize a person profile from identifiers', routing: { request: { method: 'POST', url: '/people/retrieve' } } },
			],
			default: 'enrichPerson',
		},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['people'], operation: ['enrichPerson'] } },
		options: [
			{
				displayName: 'City',
				name: 'locationCity',
				type: 'string',
				default: "",
				routing: { send: { property: 'location.city', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Country',
				name: 'locationCountry',
				type: 'string',
				default: "",
				routing: { send: { property: 'location.country', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Domain',
				name: 'companyDomain',
				type: 'string',
				default: "",
				routing: { send: { property: 'company.domain', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Education',
				name: 'education',
				type: 'string',
				default: "",
				routing: { send: { property: 'education', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: "",
				routing: { send: { property: 'email', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'First',
				name: 'nameFirst',
				type: 'string',
				default: "",
				routing: { send: { property: 'name.first', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Last',
				name: 'nameLast',
				type: 'string',
				default: "",
				routing: { send: { property: 'name.last', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Name',
				name: 'companyName',
				type: 'string',
				default: "",
				routing: { send: { property: 'company.name', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Region',
				name: 'locationRegion',
				type: 'string',
				default: "",
				routing: { send: { property: 'location.region', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Social URLs',
				name: 'socialUrls',
				type: 'string',
				default: "",
				routing: { send: { property: 'social_urls', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['people'], operation: ['retrievePerson'] } },
		options: [
			{
				displayName: 'Linkedin URL',
				name: 'identifiersLinkedinUrl',
				type: 'string',
				default: "",
				description: 'LinkedIn profile URL, e.g. https://www.linkedin.com/in/yahia-bakour/',
				routing: { send: { property: 'identifiers.linkedinUrl', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
];
