import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['web'] };
const visualOps = ['screenshot', 'extractStyleguide', 'extractFonts', 'extractCompetitors'];

export const brandFields: INodeProperties[] = [
	{
		// The SDK accepts EITHER domain OR directUrl (not both), so domain is not required —
		// an empty value is omitted so a directUrl-only request is possible.
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { ...show, operation: visualOps } },
		default: '',
		placeholder: 'stripe.com',
		description: 'Company domain. Provide either Domain or Direct URL (in Additional Fields), not both.',
		routing: { request: { qs: { domain: '={{ $value || undefined }}' } } },
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...show, operation: visualOps } },
		options: [
			{
				displayName: 'Color Scheme',
				name: 'colorScheme',
				type: 'options',
				displayOptions: { show: { '/operation': ['screenshot', 'extractStyleguide'] } },
				default: '',
				options: [
					{ name: 'Auto (Default)', value: '' },
					{ name: 'Light', value: 'light' },
					{ name: 'Dark', value: 'dark' },
				],
				description: 'Preferred color scheme to request from the target page',
				routing: { request: { qs: { colorScheme: '={{ $value }}' } } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: '',
				placeholder: 'us',
				description:
					'Two-letter ISO 3166-1 alpha-2 country code to fetch the page from that location',
				routing: { request: { qs: { country: '={{ $value }}' } } },
			},
			{
				displayName: 'Direct URL',
				name: 'directUrl',
				type: 'string',
				displayOptions: {
					show: {
						'/operation': ['screenshot', 'extractStyleguide', 'extractFonts', 'extractCompetitors'],
					},
				},
				default: '',
				placeholder: 'https://example.com/design-system',
				description: 'Fetch from this exact URL instead of resolving from the domain. Alternative to Domain (not both).',
				routing: { request: { qs: { directUrl: '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Full Page Screenshot',
				name: 'fullScreenshot',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: false,
				description: 'Whether to capture the full scrollable page height instead of just the visible viewport',
				routing: { request: { qs: { fullScreenshot: '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Handle Cookie Popup',
				name: 'handleCookiePopup',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: false,
				description: 'Whether to attempt to dismiss cookie consent banners before taking the screenshot',
				routing: { request: { qs: { handleCookiePopup: '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				default: 86400000,
				description: 'Max age of cached result in ms before a fresh fetch. Default 1 day.',
				routing: { request: { qs: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Number of Competitors',
				name: 'numCompetitors',
				type: 'number',
				displayOptions: { show: { '/operation': ['extractCompetitors'] } },
				default: 5,
				typeOptions: { minValue: 1 },
				routing: { request: { qs: { numCompetitors: '={{ $value }}' } } },
			},
			{
				displayName: 'Page Type',
				name: 'page',
				type: 'options',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: '',
				options: [
					{ name: 'Blog', value: 'blog' },
					{ name: 'Careers', value: 'careers' },
					{ name: 'Contact', value: 'contact' },
					{ name: 'Homepage (Default)', value: '' },
					{ name: 'Login', value: 'login' },
					{ name: 'Pricing', value: 'pricing' },
					{ name: 'Privacy', value: 'privacy' },
					{ name: 'Signup', value: 'signup' },
					{ name: 'Terms', value: 'terms' },
				],
				routing: { request: { qs: { page: '={{ $value }}' } } },
			},
			{
				displayName: 'Scroll Offset',
				name: 'scrollOffset',
				type: 'number',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: 0,
				description:
					'Vertical scroll offset in pixels to capture a long page in viewport-sized slices. Takes precedence over Full Page Screenshot. Max 100,000.',
				typeOptions: { minValue: 0, maxValue: 100000 },
				routing: { request: { qs: { scrollOffset: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				default: 30000,
				description: 'Maximum time in milliseconds to wait for a response before the request fails',
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { qs: { timeoutMS: '={{ $value }}' } } },
			},
			{
				displayName: 'Viewport',
				name: 'viewport',
				type: 'collection',
				placeholder: 'Add Dimension',
				default: {},
				displayOptions: { show: { '/operation': ['screenshot'] } },
				description: 'Browser viewport dimensions for the screenshot. Defaults to 1920x1080.',
				options: [
					{
						displayName: 'Width',
						name: 'width',
						type: 'number',
						default: 1920,
						description: 'Viewport width in pixels',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: 'Height',
						name: 'height',
						type: 'number',
						default: 1080,
						description: 'Viewport height in pixels',
						typeOptions: { minValue: 1 },
					},
				],
				routing: { request: { qs: { viewport: '={{ $value }}' } } },
			},
			{
				displayName: 'Wait For (Ms)',
				name: 'waitForMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: 0,
				description: 'Delay capturing by this many milliseconds after page load. Max 30,000 ms.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { request: { qs: { waitForMs: '={{ $value }}' } } },
			},
		],
	},
];
