import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['web'] };

export const webDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show },
		options: [
			{
				name: 'Crawl Sitemap',
				value: 'scrapeSitemap',
				action: 'Crawl sitemap and return all discovered urls',
				description:
					'Parse a domain sitemap and return all discovered page URLs. <a href="https://docs.context.dev/api-reference/web-scraping/crawl-sitemap" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/scrape/sitemap' } },
			},
			{
				name: 'Crawl Website',
				value: 'crawl',
				action: 'Crawl a website and return markdown for all pages',
				description:
					'Crawl multiple pages of a website and return markdown for each. <a href="https://docs.context.dev/api-reference/web-scraping/crawl-website" target="_blank">View docs</a>.',
				routing: { request: { method: 'POST', url: '/web/crawl' } },
			},
			{
				name: 'Extract Competitors',
				value: 'extractCompetitors',
				action: 'Extract competitors for a domain',
				description: 'Identify direct competitors for a given brand domain',
				routing: { request: { method: 'GET', url: '/web/competitors' } },
			},
			{
				name: 'Extract Fonts',
				value: 'extractFonts',
				action: 'Extract font information from a website',
				description:
					'Extract font families, usage statistics, fallbacks, and element counts. <a href="https://docs.context.dev/api-reference/brand/fonts" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/fonts' } },
			},
			{
				name: 'Extract Structured Data',
				value: 'extract',
				action: 'Extract structured data using a JSON schema',
				description:
					'Crawl a website and extract data matching your JSON schema. <a href="https://docs.context.dev/api-reference/web-scraping/extract" target="_blank">View docs</a>.',
				routing: { request: { method: 'POST', url: '/web/extract' } },
			},
			{
				name: 'Extract Styleguide',
				value: 'extractStyleguide',
				action: 'Extract design system from a website',
				description:
					'Extract colors, typography, spacing, shadows, and UI components. <a href="https://docs.context.dev/api-reference/brand/styleguide" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/styleguide' } },
			},
			{
				name: 'Scrape HTML',
				value: 'scrapeHtml',
				action: 'Scrape a URL and return raw HTML',
				description:
					'Scrape any URL and return the raw HTML. <a href="https://docs.context.dev/api-reference/web-scraping/scrape-html" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/scrape/html' } },
			},
			{
				name: 'Scrape Images',
				value: 'scrapeImages',
				action: 'Extract all images from a webpage',
				description:
					'Extract image assets from a web page including URLs, inline SVGs, and metadata. <a href="https://docs.context.dev/api-reference/web-scraping/scrape-images" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/scrape/images' } },
			},
			{
				name: 'Scrape to Markdown',
				value: 'scrapeMd',
				action: 'Scrape a url to markdown',
				description:
					'Scrape any URL and get back clean markdown content. <a href="https://docs.context.dev/api-reference/web-scraping/scrape-markdown" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/scrape/markdown' } },
			},
			{
				name: 'Screenshot',
				value: 'screenshot',
				action: 'Take a screenshot of a website',
				description:
					'Capture a screenshot with options for page type and viewport. <a href="https://docs.context.dev/api-reference/brand/screenshot" target="_blank">View docs</a>.',
				routing: { request: { method: 'GET', url: '/web/screenshot' } },
			},
			{
				name: 'Search',
				value: 'search',
				action: 'Search the web and return results',
				description:
					'Run a web search and get structured results with optional markdown content. <a href="https://docs.context.dev/api-reference/web-scraping/web-search" target="_blank">View docs</a>.',
				routing: { request: { method: 'POST', url: '/web/search' } },
			},
		],
		default: 'scrapeMd',
	},

	// ─── URL field for GET scrape ops ─────────────────────────────────────────
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...show, operation: ['scrapeMd', 'scrapeHtml', 'scrapeImages'] },
		},
		default: '',
		placeholder: 'https://example.com',
		routing: { request: { qs: { url: '={{ $value }}' } } },
	},

	// ─── URL field for POST ops ───────────────────────────────────────────────
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		displayOptions: {
			show: { ...show, operation: ['crawl', 'extract'] },
		},
		default: '',
		placeholder: 'https://example.com',
		routing: { request: { body: { url: '={{ $value }}' } } },
	},

	// ─── Domain field ─────────────────────────────────────────────────────────
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				...show,
				operation: [
					'scrapeSitemap',
					'screenshot',
					'extractStyleguide',
					'extractFonts',
					'extractCompetitors',
				],
			},
		},
		default: '',
		placeholder: 'example.com',
		routing: { request: { qs: { domain: '={{ $value }}' } } },
	},

	// ─── Search query ─────────────────────────────────────────────────────────
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['search'] } },
		default: '',
		placeholder: 'best CRM software 2025',
		routing: { request: { body: { query: '={{ $value }}' } } },
	},

	// ─── JSON schema for extract ──────────────────────────────────────────────
	{
		displayName: 'Schema (JSON)',
		name: 'schema',
		type: 'json',
		required: true,
		displayOptions: { show: { ...show, operation: ['extract'] } },
		default: '{}',
		description: 'JSON Schema describing the shape of data to extract from the website',
		routing: { request: { body: { schema: '={{ JSON.parse($value) }}' } } },
	},

	// ─── Additional Fields ────────────────────────────────────────────────────
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show },
		options: [
			{
				displayName: 'Direct URL',
				name: 'directUrl',
				type: 'string',
				displayOptions: { show: { '/operation': ['screenshot', 'extractStyleguide', 'extractFonts'] } },
				default: '',
				placeholder: 'https://example.com/design-system',
				description: 'Fetch from this exact URL instead of resolving from the domain',
				routing: { request: { qs: { directUrl: '={{ $value }}' } } },
			},
			{
				displayName: 'Exclude Domains',
				name: 'excludeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'pinterest.com,reddit.com',
				description: 'Comma-separated blocklist of domains to exclude from results',
				routing: { request: { body: { excludeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' } } },
			},
			{
				displayName: 'Fact Check',
				name: 'factCheck',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Whether to require every returned value to be grounded in facts stated on the page',
				routing: { request: { body: { factCheck: '={{ $value }}' } } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'followSubdomains',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['crawl', 'extract'] } },
				default: false,
				routing: { request: { body: { followSubdomains: '={{ $value }}' } } },
			},
			{
				displayName: 'Freshness',
				name: 'freshness',
				type: 'options',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				options: [
					{ name: 'Any Time', value: '' },
					{ name: 'Last 24 Hours', value: 'last_24_hours' },
					{ name: 'Last Month', value: 'last_month' },
					{ name: 'Last Week', value: 'last_week' },
					{ name: 'Last Year', value: 'last_year' },
				],
				routing: { request: { body: { freshness: '={{ $value }}' } } },
			},
			{
				displayName: 'Full Page Screenshot',
				name: 'fullScreenshot',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: false,
				routing: { request: { qs: { fullScreenshot: '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Handle Cookie Popup',
				name: 'handleCookiePopup',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: false,
				routing: { request: { qs: { handleCookiePopup: '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include Domains',
				name: 'includeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'arxiv.org,github.com',
				description: 'Comma-separated allowlist — only return results from these domains',
				routing: { request: { body: { includeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' } } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['scrapeMd', 'scrapeHtml'] } },
				default: false,
				routing: { request: { qs: { includeFrames: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFramesPost',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['crawl', 'extract'] } },
				default: false,
				routing: { request: { body: { includeFrames: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Images',
				name: 'includeImages',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['scrapeMd'] } },
				default: false,
				routing: { request: { qs: { includeImages: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Images',
				name: 'includeImagesPost',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: false,
				routing: { request: { body: { includeImages: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Links',
				name: 'includeLinks',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['scrapeMd'] } },
				default: true,
				routing: { request: { qs: { includeLinks: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Links',
				name: 'includeLinksPost',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: true,
				routing: { request: { body: { includeLinks: '={{ $value }}' } } },
			},
			{
				displayName: 'Instructions',
				name: 'instructions',
				type: 'string',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: '',
				description: 'Optional guidance on which facts to prioritize or how to interpret schema fields',
				routing: { request: { body: { instructions: '={{ $value }}' } } },
			},
			{
				displayName: 'Main Content Only',
				name: 'useMainContentOnly',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['scrapeMd'] } },
				default: false,
				description: 'Whether to strip navigation, headers, footers and return only main body content',
				routing: { request: { qs: { useMainContentOnly: '={{ $value }}' } } },
			},
			{
				displayName: 'Main Content Only',
				name: 'useMainContentOnlyPost',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: false,
				description: 'Whether to strip navigation, headers, footers and return only main body content',
				routing: { request: { body: { useMainContentOnly: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['scrapeMd', 'scrapeHtml', 'scrapeImages', 'scrapeSitemap', 'screenshot', 'extractStyleguide', 'extractFonts', 'extractCompetitors'] } },
				default: 86400000,
				description: 'Max age of cached result in ms before a fresh fetch. Default 1 day.',
				routing: { request: { qs: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMsPost',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl', 'extract'] } },
				default: 86400000,
				description: 'Max age of cached result in ms before a fresh fetch. Default 1 day.',
				routing: { request: { body: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Depth',
				name: 'maxDepth',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: 3,
				typeOptions: { minValue: 0 },
				routing: { request: { body: { maxDepth: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Links',
				name: 'maxLinks',
				type: 'number',
				displayOptions: { show: { '/operation': ['scrapeSitemap'] } },
				default: 10000,
				typeOptions: { minValue: 1, maxValue: 100000 },
				routing: { request: { qs: { maxLinks: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Pages',
				name: 'maxPages',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: 10,
				typeOptions: { minValue: 1, maxValue: 500 },
				routing: { request: { body: { maxPages: '={{ $value }}' } } },
			},
			{
				displayName: 'Number of Competitors',
				name: 'numCompetitors',
				type: 'number',
				displayOptions: { show: { '/operation': ['extractCompetitors'] } },
				default: 5,
				typeOptions: { minValue: 1 },
				routing: { request: { qs: { numCompetitors: '={{ $value }}' } } },
			},
			{
				displayName: 'Page Type',
				name: 'page',
				type: 'options',
				displayOptions: { show: { '/operation': ['screenshot'] } },
				default: '',
				options: [
					{ name: 'Blog', value: 'blog' },
					{ name: 'Careers', value: 'careers' },
					{ name: 'Contact', value: 'contact' },
					{ name: 'Homepage (Default)', value: '' },
					{ name: 'Login', value: 'login' },
					{ name: 'Pricing', value: 'pricing' },
					{ name: 'Privacy', value: 'privacy' },
					{ name: 'Signup', value: 'signup' },
					{ name: 'Terms', value: 'terms' },
				],
				routing: { request: { qs: { page: '={{ $value }}' } } },
			},
			{
				displayName: 'Query Fanout',
				name: 'queryFanout',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description: 'Whether to expand the query into multiple parallel variants for broader recall',
				routing: { request: { body: { queryFanout: '={{ $value }}' } } },
			},
			{
				displayName: 'Scrape Results to Markdown',
				name: 'markdownEnabled',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description: 'Whether to scrape each search result page to markdown inline',
				routing: { send: { type: 'body', property: 'markdownOptions.enabled' } },
			},
			{
				displayName: 'Stop After (Ms)',
				name: 'stopAfterMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl', 'extract'] } },
				default: 120000,
				description: 'Soft time budget for the crawl in milliseconds. Min 10000, max 240000.',
				typeOptions: { minValue: 10000, maxValue: 240000 },
				routing: { request: { body: { stopAfterMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				displayOptions: { show: { '/operation': ['scrapeMd', 'scrapeHtml', 'scrapeImages', 'scrapeSitemap', 'screenshot', 'extractStyleguide', 'extractFonts', 'extractCompetitors'] } },
				default: 30000,
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { qs: { timeoutMS: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMSPost',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl', 'extract', 'search'] } },
				default: 30000,
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { body: { timeoutMS: '={{ $value }}' } } },
			},
			{
				displayName: 'URL Regex',
				name: 'urlRegex',
				type: 'string',
				displayOptions: { show: { '/operation': ['crawl'] } },
				default: '',
				placeholder: '^https?://[^/]+/blog/',
				description: 'Only crawl URLs matching this RE2 regex pattern',
				routing: { request: { body: { urlRegex: '={{ $value }}' } } },
			},
			{
				displayName: 'URL Regex',
				name: 'urlRegexSitemap',
				type: 'string',
				displayOptions: { show: { '/operation': ['scrapeSitemap'] } },
				default: '',
				placeholder: '^https?://[^/]+/blog/',
				description: 'Only return sitemap URLs matching this RE2 regex pattern',
				routing: { request: { qs: { urlRegex: '={{ $value }}' } } },
			},
			{
				displayName: 'Wait For (Ms)',
				name: 'waitForMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['scrapeMd', 'scrapeHtml', 'scrapeImages', 'screenshot'] } },
				default: 0,
				description: 'Delay scraping by this many milliseconds after page load — useful for pages with delayed JavaScript rendering. Max 30,000 ms.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { request: { qs: { waitForMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Wait For (Ms)',
				name: 'waitForMsPost',
				type: 'number',
				displayOptions: { show: { '/operation': ['crawl', 'extract'] } },
				default: 0,
				description: 'Delay scraping by this many milliseconds after page load — useful for pages with delayed JavaScript rendering. Max 30,000 ms.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { request: { body: { waitForMs: '={{ $value }}' } } },
			},
		],
	},
];
