import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['web'] };
const searchExtractOps = ['search', 'extract'];

export const searchExtractFields: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['search'] } },
		default: '',
		placeholder: 'best CRM software 2025',
		routing: { request: { body: { query: '={{ $value }}' } } },
	},
	{
		displayName: 'Schema (JSON)',
		name: 'schema',
		type: 'json',
		required: true,
		displayOptions: { show: { ...show, operation: ['extract'] } },
		default: '{}',
		description: 'JSON Schema describing the shape of data to extract from the website',
		routing: { request: { body: { schema: '={{ JSON.parse($value) }}' } } },
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['extract'] } },
		default: '',
		placeholder: 'https://stripe.com',
		routing: { request: { body: { url: '={{ $value }}' } } },
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...show, operation: searchExtractOps } },
		options: [
			{
				displayName: 'Exclude Domains',
				name: 'excludeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'pinterest.com,reddit.com',
				description: 'Comma-separated blocklist of domains to exclude from results',
				routing: { request: { body: { excludeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' } } },
			},
			{
				displayName: 'Fact Check',
				name: 'factCheck',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Require every returned value to be grounded in facts stated on the page',
				routing: { request: { body: { factCheck: '={{ $value }}' } } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'followSubdomains',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Follow links to subdomains during the extraction crawl',
				routing: { request: { body: { followSubdomains: '={{ $value }}' } } },
			},
			{
				displayName: 'Freshness',
				name: 'freshness',
				type: 'options',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				options: [
					{ name: 'Any Time', value: '' },
					{ name: 'Last 24 Hours', value: 'last_24_hours' },
					{ name: 'Last Month', value: 'last_month' },
					{ name: 'Last Week', value: 'last_week' },
					{ name: 'Last Year', value: 'last_year' },
				],
				routing: { request: { body: { freshness: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Domains',
				name: 'includeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'arxiv.org,github.com',
				description: 'Comma-separated allowlist — only return results from these domains',
				routing: { request: { body: { includeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' } } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Include content from iframes embedded in the page',
				routing: { request: { body: { includeFrames: '={{ $value }}' } } },
			},
			{
				displayName: 'Instructions',
				name: 'instructions',
				type: 'string',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: '',
				description: 'Optional guidance on which facts to prioritize or how to interpret schema fields',
				routing: { request: { body: { instructions: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 86400000,
				description: 'Max age of cached result in ms before a fresh fetch. Default 1 day.',
				routing: { request: { body: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Query Fanout',
				name: 'queryFanout',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description: 'Expand the query into multiple parallel variants for broader recall',
				routing: { request: { body: { queryFanout: '={{ $value }}' } } },
			},
			{
				displayName: 'Scrape Results to Markdown',
				name: 'markdownEnabled',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description: 'Scrape each search result page and include the full content as Markdown. Significantly increases response time.',
				routing: { send: { type: 'body', property: 'markdownOptions.enabled' } },
			},
			{
				displayName: 'Stop After (Ms)',
				name: 'stopAfterMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 120000,
				description: 'Stop the extraction crawl after this many milliseconds, returning data collected so far.',
				typeOptions: { minValue: 10000, maxValue: 240000 },
				routing: { request: { body: { stopAfterMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				default: 30000,
				description: 'Maximum time in milliseconds to wait for a response before the request fails.',
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { body: { timeoutMS: '={{ $value }}' } } },
			},
			{
				displayName: 'Wait For (Ms)',
				name: 'waitForMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 0,
				description: 'Delay scraping by this many milliseconds after page load. Max 30,000 ms.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { request: { body: { waitForMs: '={{ $value }}' } } },
			},
		],
	},
];
