import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['web'] };
const searchExtractOps = ['search', 'extract'];

export const searchExtractFields: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['search'] } },
		default: '',
		placeholder: 'best CRM software 2025',
		routing: { request: { body: { query: '={{ $value }}' } } },
	},
	{
		displayName: 'Schema (JSON)',
		name: 'schema',
		type: 'json',
		required: true,
		displayOptions: { show: { ...show, operation: ['extract'] } },
		default: '{}',
		description: 'JSON Schema describing the shape of data to extract from the website',
		routing: { request: { body: { schema: '={{ JSON.parse($value) }}' } } },
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		displayOptions: { show: { ...show, operation: ['extract'] } },
		default: '',
		placeholder: 'https://stripe.com',
		routing: { request: { body: { url: '={{ $value }}' } } },
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...show, operation: searchExtractOps } },
		options: [
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'us',
				description:
					'Two-letter ISO 3166-1 alpha-2 country code to run the search from that location',
				routing: { request: { body: { country: '={{ $value }}' } } },
			},
			{
				displayName: 'Exclude Domains',
				name: 'excludeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'pinterest.com,reddit.com',
				description: 'Comma-separated blocklist of domains to exclude from results',
				routing: {
					request: {
						body: { excludeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' },
					},
				},
			},
			{
				displayName: 'Fact Check',
				name: 'factCheck',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Whether to require every returned value to be grounded in facts stated on the page',
				routing: { request: { body: { factCheck: '={{ $value }}' } } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'followSubdomains',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Whether to follow links to subdomains during the extraction crawl',
				routing: { request: { body: { followSubdomains: '={{ $value }}' } } },
			},
			{
				displayName: 'Freshness',
				name: 'freshness',
				type: 'options',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				options: [
					{ name: 'Any Time', value: '' },
					{ name: 'Last 24 Hours', value: 'last_24_hours' },
					{ name: 'Last Month', value: 'last_month' },
					{ name: 'Last Week', value: 'last_week' },
					{ name: 'Last Year', value: 'last_year' },
				],
				routing: { request: { body: { freshness: '={{ $value }}' } } },
			},
			{
				displayName: 'Include Domains',
				name: 'includeDomains',
				type: 'string',
				displayOptions: { show: { '/operation': ['search'] } },
				default: '',
				placeholder: 'arxiv.org,github.com',
				description: 'Comma-separated allowlist — only return results from these domains',
				routing: {
					request: {
						body: { includeDomains: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' },
					},
				},
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: false,
				description: 'Whether to include content from iframes embedded in the page',
				routing: { request: { body: { includeFrames: '={{ $value }}' } } },
			},
			{
				displayName: 'Instructions',
				name: 'instructions',
				type: 'string',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: '',
				description:
					'Optional guidance on which facts to prioritize or how to interpret schema fields',
				routing: { request: { body: { instructions: '={{ $value }}' } } },
			},
			{
				displayName: 'Markdown: Include Frames',
				name: 'markdownIncludeFrames',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: false,
				description: 'Whether to render iframe contents into the Markdown',
				routing: { send: { type: 'body', property: 'markdownOptions.includeFrames' } },
			},
			{
				displayName: 'Markdown: Include Images',
				name: 'markdownIncludeImages',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: false,
				description: 'Whether to emit image references in the Markdown',
				routing: { send: { type: 'body', property: 'markdownOptions.includeImages' } },
			},
			{
				displayName: 'Markdown: Include Links',
				name: 'markdownIncludeLinks',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: false,
				description: 'Whether to keep hyperlinks in the Markdown',
				routing: { send: { type: 'body', property: 'markdownOptions.includeLinks' } },
			},
			{
				displayName: 'Markdown: Max Age (Ms)',
				name: 'markdownMaxAgeMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: 86400000,
				description:
					'Cache TTL in ms for scraped Markdown keyed by URL + options. Default 1 day, max 30 days. Set to 0 to force a fresh scrape.',
				routing: { send: { type: 'body', property: 'markdownOptions.maxAgeMs' } },
			},
			{
				displayName: 'Markdown: PDF Parsing',
				name: 'markdownPdf',
				type: 'collection',
				placeholder: 'Add PDF Option',
				default: {},
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				description:
					'Control how PDF result pages are fetched and parsed when scraping search results to Markdown',
				options: [
					{
						displayName: 'End Page',
						name: 'end',
						type: 'number',
						default: 1,
						description: 'Last PDF page to parse (1-based, inclusive). Defaults to the final page. Must be >= Start Page.',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: 'Should Parse',
						name: 'shouldParse',
						type: 'boolean',
						default: true,
						description:
							'Whether PDF URLs are parsed. When false, PDF results are skipped with WEBSITE_ACCESS_ERROR.',
					},
					{
						displayName: 'Start Page',
						name: 'start',
						type: 'number',
						default: 1,
						description: 'First PDF page to parse (1-based, inclusive). Defaults to page 1.',
						typeOptions: { minValue: 1 },
					},
				],
				routing: { send: { type: 'body', property: 'markdownOptions.pdf' } },
			},
			{
				displayName: 'Markdown: Shorten Base64 Images',
				name: 'markdownShortenBase64Images',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: false,
				description: 'Whether to truncate inline base64 image payloads to keep responses small',
				routing: { send: { type: 'body', property: 'markdownOptions.shortenBase64Images' } },
			},
			{
				displayName: 'Markdown: Timeout (Ms)',
				name: 'markdownTimeoutMS',
				type: 'number',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: 30000,
				description:
					'Maximum time in milliseconds to wait for each result scrape before it is aborted',
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { send: { type: 'body', property: 'markdownOptions.timeoutMS' } },
			},
			{
				displayName: 'Markdown: Use Main Content Only',
				name: 'markdownUseMainContentOnly',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: false,
				description: 'Whether to strip nav, header, footer, and sidebar — keep only the primary article content',
				routing: { send: { type: 'body', property: 'markdownOptions.useMainContentOnly' } },
			},
			{
				displayName: 'Markdown: Wait For (Ms)',
				name: 'markdownWaitForMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['search'], '/markdownEnabled': [true] } },
				default: 0,
				description: 'Extra wait after page load before rendering, in ms. Useful for JS-heavy pages.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { send: { type: 'body', property: 'markdownOptions.waitForMs' } },
			},
			{
				displayName: 'Max Age (Ms)',
				name: 'maxAgeMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 86400000,
				description: 'Max age of cached result in ms before a fresh fetch. Default 1 day.',
				routing: { request: { body: { maxAgeMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Depth',
				name: 'maxDepth',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 3,
				description:
					'Maximum link depth to crawl from the starting URL during extraction. 0 = starting page only.',
				typeOptions: { minValue: 0 },
				routing: { request: { body: { maxDepth: '={{ $value }}' } } },
			},
			{
				displayName: 'Max Pages',
				name: 'maxPages',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 5,
				description: 'Maximum number of pages to analyze for extraction. Hard cap: 50.',
				typeOptions: { minValue: 1, maxValue: 50 },
				routing: { request: { body: { maxPages: '={{ $value }}' } } },
			},
			{
				displayName: 'Number of Results',
				name: 'numResults',
				type: 'number',
				displayOptions: { show: { '/operation': ['search'] } },
				default: 10,
				description: 'Number of results to request and return. Between 10 and 100.',
				typeOptions: { minValue: 10, maxValue: 100 },
				routing: { request: { body: { numResults: '={{ $value }}' } } },
			},
			{
				displayName: 'PDF Parsing',
				name: 'pdf',
				type: 'collection',
				placeholder: 'Add PDF Option',
				default: {},
				displayOptions: { show: { '/operation': ['extract'] } },
				description: 'Control how linked PDF documents are fetched and parsed',
				options: [
					{
						displayName: 'End Page',
						name: 'end',
						type: 'number',
						default: 1,
						description: 'Last 1-based PDF page to parse. Must be greater than or equal to Start Page.',
						typeOptions: { minValue: 1 },
					},
					{
						displayName: 'Should Parse',
						name: 'shouldParse',
						type: 'boolean',
						default: true,
						description:
							'Whether PDF pages are fetched and parsed. When false, PDF pages are skipped.',
					},
					{
						displayName: 'Start Page',
						name: 'start',
						type: 'number',
						default: 1,
						description: 'First 1-based PDF page to parse',
						typeOptions: { minValue: 1 },
					},
				],
				routing: { request: { body: { pdf: '={{ $value }}' } } },
			},
			{
				displayName: 'Query Fanout',
				name: 'queryFanout',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description: 'Whether to expand the query into multiple parallel variants for broader recall',
				routing: { request: { body: { queryFanout: '={{ $value }}' } } },
			},
			{
				displayName: 'Scrape Results to Markdown',
				name: 'markdownEnabled',
				type: 'boolean',
				displayOptions: { show: { '/operation': ['search'] } },
				default: false,
				description:
					'Whether to scrape each search result page and include the full content as Markdown. Significantly increases response time.',
				routing: { send: { type: 'body', property: 'markdownOptions.enabled' } },
			},
			{
				displayName: 'Stop After (Ms)',
				name: 'stopAfterMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 80000,
				description:
					'Stop the extraction crawl after this many milliseconds, returning data collected so far. Between 10,000 and 110,000 ms.',
				typeOptions: { minValue: 10000, maxValue: 110000 },
				routing: { request: { body: { stopAfterMs: '={{ $value }}' } } },
			},
			{
				displayName: 'Timeout (Ms)',
				name: 'timeoutMS',
				type: 'number',
				default: 30000,
				description: 'Maximum time in milliseconds to wait for a response before the request fails',
				typeOptions: { minValue: 1, maxValue: 300000 },
				routing: { request: { body: { timeoutMS: '={{ $value }}' } } },
			},
			{
				displayName: 'Wait For (Ms)',
				name: 'waitForMs',
				type: 'number',
				displayOptions: { show: { '/operation': ['extract'] } },
				default: 0,
				description: 'Delay scraping by this many milliseconds after page load. Max 30,000 ms.',
				typeOptions: { minValue: 0, maxValue: 30000 },
				routing: { request: { body: { waitForMs: '={{ $value }}' } } },
			},
		],
	},
];
