import type { INodeProperties } from 'n8n-workflow';

export const webExtractionDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['webExtraction'] } },
			options: [
			{ name: 'Classify NAICS Industries', value: 'classifyNAICSIndustries', action: 'Classify NAICS industries', description: 'Classify any brand into 2022 NAICS industry codes from its domain or name', routing: { request: { method: 'GET', url: '/web/naics' } } },
			{ name: 'Classify SIC Industries', value: 'classifySICIndustries', action: 'Classify SIC industries', description: 'Classify any brand into Standard Industrial Classification (SIC) codes from its domain or name. Choose between the original SIC system (`original_sic`) or the latest SIC list maintained by the SEC (`latest_sec`).', routing: { request: { method: 'GET', url: '/web/sic' } } },
			{ name: 'Extract a Single Product From a URL', value: 'extractASingleProductFromAURL', action: 'Extract a single product from a URL', description: 'Given a single URL, determines if it is a product page and extracts the product information', routing: { request: { method: 'POST', url: '/brand/ai/product' } } },
			{ name: 'Extract Products From a Brand\'s Website', value: 'extractProductsFromABrandSWebsite', action: 'Extract products from a brand s website', description: 'Extract product information from a brand\'s website. We will analyze the website and return a list of products with details such as name, description, image, pricing, features, and more.', routing: { request: { method: 'POST', url: '/brand/ai/products' } } },
			{ name: 'Extract Structured Website Data', value: 'extractStructuredWebsiteData', action: 'Extract structured website data', description: 'Crawl a website, use the provided JSON Schema and instructions to prioritize relevant internal links, and extract structured data from the selected pages', routing: { request: { method: 'POST', url: '/web/extract' } } },
			{ name: 'Find Website Competitors', value: 'findWebsiteCompetitors', action: 'Find website competitors', description: 'Analyze a company\'s landing page and web search evidence to return direct competitors for the same product or market', routing: { request: { method: 'GET', url: '/web/competitors' } } },
			{ name: 'Query Website Data Using AI', value: 'queryWebsiteDataUsingAI', action: 'Query website data using AI', description: 'Use AI to extract specific data points from a brand\'s website. The AI will crawl the website and extract the requested information based on the provided data points.', routing: { request: { method: 'POST', url: '/brand/ai/query' } } },
			{ name: 'Scrape Fonts', value: 'scrapeFonts', action: 'Scrape fonts', description: 'Scrape font information from a website including font families, usage statistics, fallbacks, and element/word counts', routing: { request: { method: 'GET', url: '/web/fonts' } } },
			{ name: 'Scrape Styleguide', value: 'scrapeStyleguide', action: 'Scrape styleguide', description: 'Extract a comprehensive design system from a website including colors, typography, spacing, shadows, and UI components', routing: { request: { method: 'GET', url: '/web/styleguide' } } },
			],
			default: 'extractStructuredWebsiteData',
		},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractStructuredWebsiteData'] } },
		required: true,
		default: "",
		description: 'The starting website URL to crawl and extract from. Must include http:// or https://.',
		routing: { send: { property: 'url', type: 'body' } },
	},
	{
		displayName: 'Schema',
		name: 'schema',
		type: 'json',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractStructuredWebsiteData'] } },
		required: true,
		default: "{}",
		description: 'JSON Schema for the returned data object. TypeScript Zod users can pass a JSON Schema generated from a Zod object; Python users can pass the equivalent JSON Schema object.',
		routing: { send: { property: 'schema', type: 'body', value: '={{ $value ? JSON.parse($value) : undefined }}' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractStructuredWebsiteData'] } },
		options: [
			{
				displayName: 'End',
				name: 'pdfEnd',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last 1-based PDF page to parse. Must be greater than or equal to start when both are provided.',
				routing: { send: { property: 'pdf.end', type: 'body' } },
			},
			{
				displayName: 'Fact Check',
				name: 'factCheck',
				type: 'boolean',
				default: false,
				description: 'Whether true, every returned value must be grounded in facts stated on the page; fields that cannot be supported by the page are returned as null/empty. When false (default), the model may make reasonable inferences and derivations from the page content (e.g. ideal customer, competitor analysis, recommendations) while keeping verifiable specifics (names, quotes, URLs, dates, metrics) faithful to the source.',
				routing: { send: { property: 'factCheck', type: 'body' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'followSubdomains',
				type: 'boolean',
				default: false,
				description: 'Whether true, follow links on subdomains of the starting URL\'s domain',
				routing: { send: { property: 'followSubdomains', type: 'body' } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				default: false,
				description: 'Whether true, iframe contents are included in Markdown before extraction',
				routing: { send: { property: 'includeFrames', type: 'body' } },
			},
			{
				displayName: 'Instructions',
				name: 'instructions',
				type: 'string',
				default: "",
				description: 'Optional extraction guidance, such as which facts to prioritize or how to interpret fields in the schema',
				routing: { send: { property: 'instructions', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'number',
				default: 604800000,
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return cached scrape results if a prior scrape for the same parameters is younger than this many milliseconds. Defaults to 7 days (604800000 ms).',
				routing: { send: { property: 'maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Max Depth',
				name: 'maxDepth',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0},
				description: 'Optional maximum link depth from the starting URL (0 = only the starting page). If omitted, there is no crawl depth limit.',
				routing: { send: { property: 'maxDepth', type: 'body' } },
			},
			{
				displayName: 'Max Pages',
				name: 'maxPages',
				type: 'number',
				default: 5,
				typeOptions: {"minValue":1,"maxValue":50},
				description: 'Maximum number of pages to analyze for extraction. Hard cap: 50. Defaults to 5.',
				routing: { send: { property: 'maxPages', type: 'body' } },
			},
			{
				displayName: 'Settle Animations',
				name: 'settleAnimations',
				type: 'boolean',
				default: false,
				description: 'Whether true, waits briefly for CSS and transition animations to settle before extracting each crawled page. Defaults to false. This adds a bit of latency in exchange for more stable output on animated pages.',
				routing: { send: { property: 'settleAnimations', type: 'body' } },
			},
			{
				displayName: 'Should Parse',
				name: 'pdfShouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether true, PDF pages are fetched and parsed. When false, PDF pages are skipped.',
				routing: { send: { property: 'pdf.shouldParse', type: 'body' } },
			},
			{
				displayName: 'Start',
				name: 'pdfStart',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First 1-based PDF page to parse',
				routing: { send: { property: 'pdf.start', type: 'body' } },
			},
			{
				displayName: 'Stop After MS',
				name: 'stopAfterMs',
				type: 'number',
				default: 80000,
				typeOptions: {"minValue":10000,"maxValue":110000},
				description: 'Soft time budget for the crawl in milliseconds. Min: 10000 (10s). Max: 110000 (110s). Default: 80000 (80s).',
				routing: { send: { property: 'stopAfterMs', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load for each crawled page',
				routing: { send: { property: 'waitForMs', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['findWebsiteCompetitors'] } },
		required: true,
		default: "",
		description: 'Company domain to analyze, such as `stripe.com`. Full http(s) URLs are accepted and normalized to their domain.',
		routing: { request: { qs: { "domain": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['findWebsiteCompetitors'] } },
		options: [
			{
				displayName: 'Num Competitors',
				name: 'numCompetitors',
				type: 'number',
				default: 5,
				typeOptions: {"minValue":1,"maxValue":10},
				description: 'Exact number of direct competitors to return. Defaults to 5.',
				routing: { request: { qs: { "numCompetitors": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['scrapeStyleguide'] } },
		options: [
			{
				displayName: 'Color Scheme',
				name: 'colorScheme',
				type: 'options',
				default: "light",
				options: [{ name: 'Dark', value: "dark" }, { name: 'Light', value: "light" }],
				description: 'Optional browser color scheme to emulate for websites that respond to prefers-color-scheme. This value is part of the styleguide cache key.',
				routing: { request: { qs: { "colorScheme": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Direct URL',
				name: 'directUrl',
				type: 'string',
				default: "",
				description: 'A specific URL to fetch the styleguide from directly, bypassing domain resolution (e.g., \'https://example.com/design-system\'). When provided, the styleguide is extracted from this exact URL. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "directUrl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: "",
				description: 'Domain name to extract styleguide from (e.g., \'example.com\', \'google.com\'). The domain will be automatically normalized and validated. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "domain": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['scrapeFonts'] } },
		options: [
			{
				displayName: 'Direct URL',
				name: 'directUrl',
				type: 'string',
				default: "",
				description: 'A specific URL to fetch fonts from directly, bypassing domain resolution (e.g., \'https://example.com/design-system\'). When provided, fonts are extracted from this exact URL. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "directUrl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: "",
				description: 'Domain name to extract fonts from (e.g., \'example.com\', \'google.com\'). The domain will be automatically normalized and validated. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "domain": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Input',
		name: 'input',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['classifyNAICSIndustries'] } },
		required: true,
		default: "",
		description: 'Brand domain or title to retrieve NAICS code for. If a valid domain is provided, it will be used for classification, otherwise, we will search for the brand using the provided title.',
		routing: { request: { qs: { "input": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['classifyNAICSIndustries'] } },
		options: [
			{
				displayName: 'Max Results',
				name: 'maxResults',
				type: 'number',
				default: 5,
				typeOptions: {"minValue":1,"maxValue":10},
				description: 'Maximum number of NAICS codes to return. Must be between 1 and 10. Defaults to 5.',
				routing: { request: { qs: { "maxResults": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Min Results',
				name: 'minResults',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":10},
				description: 'Minimum number of NAICS codes to return. Must be at least 1. Defaults to 1.',
				routing: { request: { qs: { "minResults": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Input',
		name: 'input',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['classifySICIndustries'] } },
		required: true,
		default: "",
		description: 'Brand domain or title to retrieve SIC code for. If a valid domain is provided, it will be used for classification, otherwise, we will search for the brand using the provided title.',
		routing: { request: { qs: { "input": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['classifySICIndustries'] } },
		options: [
			{
				displayName: 'Max Results',
				name: 'maxResults',
				type: 'number',
				default: 5,
				typeOptions: {"minValue":1,"maxValue":10},
				description: 'Maximum number of SIC codes to return. Must be between 1 and 10. Defaults to 5.',
				routing: { request: { qs: { "maxResults": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Min Results',
				name: 'minResults',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":10},
				description: 'Minimum number of SIC codes to return. Must be at least 1. Defaults to 1.',
				routing: { request: { qs: { "minResults": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				default: "original_sic",
				options: [{ name: 'Latest Sec', value: "latest_sec" }, { name: 'Original SIC', value: "original_sic" }],
				description: 'Which SIC dataset to classify against. `original_sic` uses the 1987 Standard Industrial Classification system; `latest_sec` uses the current SIC list as published by the SEC. Defaults to `original_sic`.',
				routing: { request: { qs: { "type": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['queryWebsiteDataUsingAI'] } },
		required: true,
		default: "",
		description: 'The domain name to analyze',
		routing: { send: { property: 'domain', type: 'body' } },
	},
	{
		displayName: 'Data to Extract',
		name: 'dataToExtract',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['queryWebsiteDataUsingAI'] } },
		required: true,
		default: "",
		description: 'Array of data points to extract from the website',
		routing: { send: { property: 'data_to_extract', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['queryWebsiteDataUsingAI'] } },
		options: [
			{
				displayName: 'About Us',
				name: 'specificPagesAboutUs',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the about us page',
				routing: { send: { property: 'specific_pages.about_us', type: 'body' } },
			},
			{
				displayName: 'Blog',
				name: 'specificPagesBlog',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the blog',
				routing: { send: { property: 'specific_pages.blog', type: 'body' } },
			},
			{
				displayName: 'Careers',
				name: 'specificPagesCareers',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the careers page',
				routing: { send: { property: 'specific_pages.careers', type: 'body' } },
			},
			{
				displayName: 'Contact Us',
				name: 'specificPagesContactUs',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the contact us page',
				routing: { send: { property: 'specific_pages.contact_us', type: 'body' } },
			},
			{
				displayName: 'Faq',
				name: 'specificPagesFaq',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the FAQ page',
				routing: { send: { property: 'specific_pages.faq', type: 'body' } },
			},
			{
				displayName: 'Home Page',
				name: 'specificPagesHomePage',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the home page',
				routing: { send: { property: 'specific_pages.home_page', type: 'body' } },
			},
			{
				displayName: 'Pricing',
				name: 'specificPagesPricing',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the pricing page',
				routing: { send: { property: 'specific_pages.pricing', type: 'body' } },
			},
			{
				displayName: 'Privacy Policy',
				name: 'specificPagesPrivacyPolicy',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the privacy policy page',
				routing: { send: { property: 'specific_pages.privacy_policy', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Terms and Conditions',
				name: 'specificPagesTermsAndConditions',
				type: 'boolean',
				default: false,
				description: 'Whether to analyze the terms and conditions page',
				routing: { send: { property: 'specific_pages.terms_and_conditions', type: 'body' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractASingleProductFromAURL'] } },
		required: true,
		default: "",
		description: 'The product page URL to extract product data from',
		routing: { send: { property: 'url', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractASingleProductFromAURL'] } },
		options: [
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'number',
				default: 604800000,
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 7 days (604800000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { send: { property: 'maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractProductsFromABrandSWebsite'] } },
		required: true,
		default: "",
		description: 'The domain name to analyze',
		routing: { send: { property: 'domain', type: 'body' } },
	},
	{
		displayName: 'Direct URL',
		name: 'directUrl',
		type: 'string',
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractProductsFromABrandSWebsite'] } },
		required: true,
		default: "",
		description: 'A specific URL to use directly as the starting point for extraction without domain resolution',
		routing: { send: { property: 'directUrl', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webExtraction'], operation: ['extractProductsFromABrandSWebsite'] } },
		options: [
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'number',
				default: 604800000,
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 7 days (604800000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { send: { property: 'maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Max Products',
				name: 'maxProducts',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":12},
				description: 'Maximum number of products to extract',
				routing: { send: { property: 'maxProducts', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
];
