import type { INodeProperties } from 'n8n-workflow';

export const webScrapingDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['webScraping'] } },
			options: [
			{ name: 'Crawl Sitemap', value: 'crawlSitemap', action: 'Crawl sitemap', description: 'Crawl an entire website\'s sitemap and return all discovered page URLs. Pass `search` to have the crawled sitemap filtered down to the pages about a phrase (for example `pricing and plans` or `api authentication docs`), most relevant first — a searched crawl scans the whole sitemap and costs 2 credits instead of 1.', routing: { request: { method: 'GET', url: '/web/scrape/sitemap' } } },
			{ name: 'Crawl Website & Scrape Markdown', value: 'crawlWebsiteScrapeMarkdown', action: 'Crawl website scrape markdown', description: 'Performs a crawl starting from a given URL, extracts page content as Markdown, and returns results for all crawled pages', routing: { request: { method: 'POST', url: '/web/crawl' } } },
			{ name: 'Scrape HTML', value: 'scrapeHTML', action: 'Scrape HTML', description: 'Scrapes the given URL and returns the raw HTML content of the page. The base request costs 1 credit; requests with browser actions cost 2 credits.', routing: { request: { method: 'GET', url: '/web/scrape/html' } } },
			{ name: 'Scrape Images', value: 'scrapeImages', action: 'Scrape images', description: 'Extract image assets from a web page, including standard URLs, inline SVGs, data URIs, responsive image sources, metadata, CSS backgrounds, video posters, and embeds. The base request costs 1 credit, or 2 credits with browser actions. When enrichment is enabled, the entire call costs 5 credits, including requests that also use actions', routing: { request: { method: 'GET', url: '/web/scrape/images' } } },
			{ name: 'Scrape Markdown', value: 'scrapeMarkdown', action: 'Scrape markdown', description: 'Scrapes the given URL into LLM usable Markdown. Inspect key_metadata on JSON responses from a recognized API key; use error_code to distinguish stable failure categories.', routing: { request: { method: 'GET', url: '/web/scrape/markdown' } } },
			{ name: 'Scrape Screenshot', value: 'scrapeScreenshot', action: 'Scrape screenshot', description: 'Capture a screenshot of a website', routing: { request: { method: 'GET', url: '/web/screenshot' } } },
			{ name: 'Web Search', value: 'webSearch', action: 'Web search', description: 'Search the web and optionally scrape each result to Markdown in one round-trip', routing: { request: { method: 'POST', url: '/web/search' } } },
			],
			default: 'scrapeHTML',
		},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeHTML'] } },
		required: true,
		default: "",
		description: 'Full URL to scrape (must include http:// or https:// protocol)',
		routing: { request: { qs: { "url": '={{ $value }}' } } },
	},
	{
		displayName: 'PDF',
		name: 'pdf',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeHTML'] } },
		options: [
			{
				displayName: 'Should Parse',
				name: 'shouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether true, PDF URLs are fetched and parsed. When false, PDF URLs are skipped and a 400 PDF_SKIPPED is returned.',
			},
			{
				displayName: 'Start',
				name: 'start',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First 1-based PDF page to parse. When omitted, parsing starts at the first page.',
			},
			{
				displayName: 'End',
				name: 'end',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last 1-based PDF page to parse. When omitted, parsing ends at the last page. Must be greater than or equal to start when both are provided.',
			},
			{
				displayName: 'OCR',
				name: 'ocr',
				type: 'boolean',
				default: false,
				description: 'Whether true, OCR the selected PDF pages that have no usable text layer (scans), replacing each recovered page\'s text with the OCR result while pages with a real text layer keep it. Billed at 1 credit per page OCR actually recovered, on top of the base request cost. When false, no OCR runs.',
			},
		],
		routing: { request: { qs: { "pdf": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeHTML'] } },
		options: [
			{
				displayName: 'Actions',
				name: 'actions',
				type: 'string',
				default: "",
				description: 'Optional browser actions executed in array order after the page loads and before content is captured. Requires a paid plan. Send a JSON array in the query parameter. Maximum: 5 actions.',
				routing: { request: { qs: { "actions": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				default: "ad",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'Ao', value: "ao" }, { name: 'Ar', value: "ar" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Bq', value: "bq" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cv', value: "cv" }, { name: 'Cw', value: "cw" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gg', value: "gg" }, { name: 'Gh', value: "gh" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'Im', value: "im" }, { name: 'In', value: "in" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Je', value: "je" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Kn', value: "kn" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Me', value: "me" }, { name: 'Mf', value: "mf" }, { name: 'Mg', value: "mg" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Si', value: "si" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'Ss', value: "ss" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sx', value: "sx" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Fetch the target page through a residential proxy in this country (ISO 3166-1 alpha-2)',
				routing: { request: { qs: { "country": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Exclude Selectors',
				name: 'excludeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors to remove from the result. Applied after includeSelectors. Exclusion takes precedence: an element matching both is removed. Examples: "nav", "footer", ".ad-banner", "[aria-hidden=true]".',
				routing: { request: { qs: { "excludeSelectors": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Headers',
				name: 'headers',
				type: 'json',
				default: "{}",
				description: 'Optional outbound HTTP headers forwarded only to the target URL, sent as deep-object query params such as headers[X-Custom]=value. When provided, caching is bypassed: the result is neither read from nor written to cache.',
				routing: { request: { qs: { "headers": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				default: false,
				description: 'Whether true, iframes are rendered inline into the returned HTML',
				routing: { request: { qs: { "includeFrames": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include Selectors',
				name: 'includeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors. When provided, only matching subtrees (and their descendants) are kept and everything else is dropped. When omitted, the entire document is kept. Examples: "article.main", "#content", "[role=main]".',
				routing: { request: { qs: { "includeSelectors": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 1 day (86400000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Settle Animations',
				name: 'settleAnimations',
				type: 'boolean',
				default: false,
				description: 'Whether true, waits briefly for CSS and transition animations to settle before extracting HTML. Defaults to false. This adds a bit of latency in exchange for more stable output on animated pages.',
				routing: { request: { qs: { "settleAnimations": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Use Main Content Only',
				name: 'useMainContentOnly',
				type: 'boolean',
				default: false,
				description: 'Whether true, return only the page\'s main content in the HTML response, excluding headers, footers, sidebars, and navigation when detectable',
				routing: { request: { qs: { "useMainContentOnly": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'string',
				default: "",
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load. Min: 0. Max: 30000 (30 seconds).',
				routing: { request: { qs: { "waitForMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ZDR',
				name: 'zdr',
				type: 'options',
				default: "disabled",
				options: [{ name: 'Disabled', value: "disabled" }, { name: 'Enabled', value: "enabled" }],
				description: 'Set to enabled to bypass shared caches and omit request and response content from retained usage logs. Requires zero data retention to be enabled for your organization (contact support@context.dev), otherwise the request fails with ZDR_NOT_ENABLED. Successful ZDR responses include X-Context-ZDR: true.',
				routing: { request: { qs: { "zdr": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeMarkdown'] } },
		required: true,
		default: "",
		description: 'Full URL to scrape into LLM usable Markdown (must include http:// or https:// protocol)',
		routing: { request: { qs: { "url": '={{ $value }}' } } },
	},
	{
		displayName: 'PDF',
		name: 'pdf',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeMarkdown'] } },
		options: [
			{
				displayName: 'Should Parse',
				name: 'shouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether true, PDF URLs are fetched and parsed. When false, PDF URLs are skipped and a 400 PDF_SKIPPED is returned.',
			},
			{
				displayName: 'Start',
				name: 'start',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First 1-based PDF page to parse. When omitted, parsing starts at the first page.',
			},
			{
				displayName: 'End',
				name: 'end',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last 1-based PDF page to parse. When omitted, parsing ends at the last page. Must be greater than or equal to start when both are provided.',
			},
			{
				displayName: 'OCR',
				name: 'ocr',
				type: 'boolean',
				default: false,
				description: 'Whether true, OCR the selected PDF pages that have no usable text layer (scans), replacing each recovered page\'s text with the OCR result while pages with a real text layer keep it. Billed at 1 credit per page OCR actually recovered, on top of the base request cost. When false, no OCR runs.',
			},
		],
		routing: { request: { qs: { "pdf": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeMarkdown'] } },
		options: [
			{
				displayName: 'Actions',
				name: 'actions',
				type: 'string',
				default: "",
				description: 'Optional browser actions executed in array order after the page loads and before content is captured. Requires a paid plan. Send a JSON array in the query parameter. Maximum: 5 actions.',
				routing: { request: { qs: { "actions": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				default: "ad",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'Ao', value: "ao" }, { name: 'Ar', value: "ar" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Bq', value: "bq" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cv', value: "cv" }, { name: 'Cw', value: "cw" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gg', value: "gg" }, { name: 'Gh', value: "gh" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'Im', value: "im" }, { name: 'In', value: "in" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Je', value: "je" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Kn', value: "kn" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Me', value: "me" }, { name: 'Mf', value: "mf" }, { name: 'Mg', value: "mg" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Si', value: "si" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'Ss', value: "ss" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sx', value: "sx" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Fetch the target page through a residential proxy in this country (ISO 3166-1 alpha-2)',
				routing: { request: { qs: { "country": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Exclude Selectors',
				name: 'excludeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors to remove before conversion to Markdown. Applied after includeSelectors. Exclusion takes precedence: an element matching both is removed. Examples: "nav", "footer", ".ad-banner", "[aria-hidden=true]".',
				routing: { request: { qs: { "excludeSelectors": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Headers',
				name: 'headers',
				type: 'json',
				default: "{}",
				description: 'Optional outbound HTTP headers forwarded only to the target URL, sent as deep-object query params such as headers[X-Custom]=value. When provided, caching is bypassed: the result is neither read from nor written to cache.',
				routing: { request: { qs: { "headers": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				default: false,
				description: 'Whether true, the contents of iframes are rendered to Markdown',
				routing: { request: { qs: { "includeFrames": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include HTML',
				name: 'includeHTML',
				type: 'boolean',
				default: false,
				description: 'Whether true, the response also includes an `HTML` field with the page HTML the Markdown was converted from — the same body the Scrape HTML endpoint returns for the equivalent request',
				routing: { request: { qs: { "includeHTML": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include Images',
				name: 'includeImages',
				type: 'boolean',
				default: false,
				description: 'Whether include image references in Markdown output',
				routing: { request: { qs: { "includeImages": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include Links',
				name: 'includeLinks',
				type: 'boolean',
				default: true,
				description: 'Whether preserve hyperlinks in Markdown output',
				routing: { request: { qs: { "includeLinks": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Include Selectors',
				name: 'includeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors. When provided, only matching HTML subtrees (and their descendants) are kept before conversion to Markdown. When omitted, the entire document is kept. Examples: "article.main", "#content", "[role=main]".',
				routing: { request: { qs: { "includeSelectors": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 1 day (86400000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Settle Animations',
				name: 'settleAnimations',
				type: 'boolean',
				default: false,
				description: 'Whether true, waits briefly for CSS and transition animations to settle before converting to Markdown. Defaults to false. This adds a bit of latency in exchange for more stable output on animated pages.',
				routing: { request: { qs: { "settleAnimations": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Shorten Base64 Images',
				name: 'shortenBase64Images',
				type: 'boolean',
				default: true,
				description: 'Whether shorten base64-encoded image data in the Markdown output',
				routing: { request: { qs: { "shortenBase64Images": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Use Main Content Only',
				name: 'useMainContentOnly',
				type: 'boolean',
				default: false,
				description: 'Whether extract only the main content of the page, excluding headers, footers, sidebars, and navigation',
				routing: { request: { qs: { "useMainContentOnly": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'string',
				default: "",
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load before converting the page to Markdown. Min: 0. Max: 30000 (30 seconds).',
				routing: { request: { qs: { "waitForMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ZDR',
				name: 'zdr',
				type: 'options',
				default: "disabled",
				options: [{ name: 'Disabled', value: "disabled" }, { name: 'Enabled', value: "enabled" }],
				description: 'Set to enabled to bypass shared caches and omit request and response content from retained usage logs. Requires zero data retention to be enabled for your organization (contact support@context.dev), otherwise the request fails with ZDR_NOT_ENABLED. Successful ZDR responses include X-Context-ZDR: true.',
				routing: { request: { qs: { "zdr": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeImages'] } },
		required: true,
		default: "",
		description: 'Page URL to inspect. Must include http:// or https://.',
		routing: { request: { qs: { "url": '={{ $value }}' } } },
	},
	{
		displayName: 'Enrichment',
		name: 'enrichment',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeImages'] } },
		options: [
			{
				displayName: 'Resolution',
				name: 'resolution',
				type: 'boolean',
				default: false,
				description: 'Whether measure image width and height when possible',
			},
			{
				displayName: 'Hosted URL',
				name: 'hostedUrl',
				type: 'boolean',
				default: false,
				description: 'Whether host materializable images on the Brand.dev CDN and return their URL and MIME type',
			},
			{
				displayName: 'Classification',
				name: 'classification',
				type: 'boolean',
				default: false,
				description: 'Whether classify each image by visual asset type',
			},
			{
				displayName: 'Max Time per MS',
				name: 'maxTimePerMs',
				type: 'number',
				default: 30000,
				typeOptions: {"minValue":1,"maxValue":60000},
				description: 'Per-image enrichment timeout in milliseconds. Default: 30000. Maximum: 60000.',
			},
		],
		routing: { request: { qs: { "enrichment": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeImages'] } },
		options: [
			{
				displayName: 'Actions',
				name: 'actions',
				type: 'string',
				default: "",
				description: 'Optional browser actions executed in array order after the page loads and before content is captured. Requires a paid plan. Send a JSON array in the query parameter. Maximum: 5 actions.',
				routing: { request: { qs: { "actions": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Dedupe',
				name: 'dedupe',
				type: 'boolean',
				default: false,
				description: 'Whether true, visually duplicate images are removed: every image is loaded and perceptually hashed, and only the highest-resolution copy of each duplicate group is kept. Images that cannot be downloaded or hashed are kept. Default: false.',
				routing: { request: { qs: { "dedupe": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Headers',
				name: 'headers',
				type: 'json',
				default: "{}",
				description: 'Optional outbound HTTP headers forwarded only to the target URL, sent as deep-object query params such as headers[X-Custom]=value. When provided, caching is bypassed: the result is neither read from nor written to cache.',
				routing: { request: { qs: { "headers": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Reuse a cached result this many milliseconds old or newer. Default: 86400000 (1 day). Set to 0 to bypass cache. Maximum: 2592000000 (30 days).',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'string',
				default: "",
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load before collecting images. Min: 0. Max: 30000 (30 seconds).',
				routing: { request: { qs: { "waitForMs": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['crawlSitemap'] } },
		required: true,
		default: "",
		description: 'Domain to build a sitemap for',
		routing: { request: { qs: { "domain": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['crawlSitemap'] } },
		options: [
			{
				displayName: 'Headers',
				name: 'headers',
				type: 'json',
				default: "{}",
				description: 'Optional outbound HTTP headers forwarded only to the target URL, sent as deep-object query params such as headers[X-Custom]=value. When provided, caching is bypassed: the result is neither read from nor written to cache.',
				routing: { request: { qs: { "headers": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Links',
				name: 'maxLinks',
				type: 'number',
				default: 10000,
				typeOptions: {"minValue":1,"maxValue":100000},
				description: 'Maximum number of links to return from the sitemap crawl. Defaults to 10,000. Minimum is 1, maximum is 100,000.',
				routing: { request: { qs: { "maxLinks": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: "",
				description: 'Optional search phrase. When provided, the crawled sitemap is filtered to the pages whose URLs are about that phrase, most relevant first, and the request costs 2 credits instead of 1.',
				routing: { request: { qs: { "search": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Sitemap URL',
				name: 'sitemapUrl',
				type: 'string',
				default: "",
				description: 'Optional explicit sitemap URL. When provided, exactly this sitemap is crawled instead of discovering the domain\'s sitemaps.',
				routing: { request: { qs: { "sitemapUrl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'URL Regex',
				name: 'urlRegex',
				type: 'string',
				default: "",
				description: 'Optional RE2-compatible regex pattern. Only URLs matching this pattern are returned and counted against maxLinks.',
				routing: { request: { qs: { "urlRegex": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ZDR',
				name: 'zdr',
				type: 'options',
				default: "disabled",
				options: [{ name: 'Disabled', value: "disabled" }, { name: 'Enabled', value: "enabled" }],
				description: 'Set to enabled to bypass shared caches and omit request and response content from retained usage logs. Requires zero data retention to be enabled for your organization (contact support@context.dev), otherwise the request fails with ZDR_NOT_ENABLED. Successful ZDR responses include X-Context-ZDR: true.',
				routing: { request: { qs: { "zdr": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['crawlWebsiteScrapeMarkdown'] } },
		required: true,
		default: "",
		description: 'The starting URL for the crawl (must include http:// or https:// protocol)',
		routing: { send: { property: 'url', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['crawlWebsiteScrapeMarkdown'] } },
		options: [
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				default: "ad",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'Ao', value: "ao" }, { name: 'Ar', value: "ar" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Bq', value: "bq" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cv', value: "cv" }, { name: 'Cw', value: "cw" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gg', value: "gg" }, { name: 'Gh', value: "gh" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'Im', value: "im" }, { name: 'In', value: "in" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Je', value: "je" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Kn', value: "kn" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Me', value: "me" }, { name: 'Mf', value: "mf" }, { name: 'Mg', value: "mg" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Si', value: "si" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'Ss', value: "ss" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sx', value: "sx" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Fetch the target page through a residential proxy in this country (ISO 3166-1 alpha-2)',
				routing: { send: { property: 'country', type: 'body' } },
			},
			{
				displayName: 'End',
				name: 'pdfEnd',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last 1-based PDF page to parse. When omitted, parsing ends at the last page. Must be greater than or equal to start when both are provided.',
				routing: { send: { property: 'pdf.end', type: 'body' } },
			},
			{
				displayName: 'Exclude Selectors',
				name: 'excludeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors to remove before each crawled page is converted to Markdown. Applied after includeSelectors. Exclusion takes precedence: an element matching both is removed. Examples: "nav", "footer", ".ad-banner", "[aria-hidden=true]".',
				routing: { send: { property: 'excludeSelectors', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'followSubdomains',
				type: 'boolean',
				default: false,
				description: 'Whether true, follow links on subdomains of the starting URL\'s domain (e.g. docs.example.com when starting from example.com). www and apex are always treated as equivalent.',
				routing: { send: { property: 'followSubdomains', type: 'body' } },
			},
			{
				displayName: 'Include Frames',
				name: 'includeFrames',
				type: 'boolean',
				default: false,
				description: 'Whether true, the contents of iframes are rendered to Markdown for each crawled page',
				routing: { send: { property: 'includeFrames', type: 'body' } },
			},
			{
				displayName: 'Include Images',
				name: 'includeImages',
				type: 'boolean',
				default: false,
				description: 'Whether include image references in the Markdown output',
				routing: { send: { property: 'includeImages', type: 'body' } },
			},
			{
				displayName: 'Include Links',
				name: 'includeLinks',
				type: 'boolean',
				default: true,
				description: 'Whether preserve hyperlinks in the Markdown output',
				routing: { send: { property: 'includeLinks', type: 'body' } },
			},
			{
				displayName: 'Include Selectors',
				name: 'includeSelectors',
				type: 'string',
				default: "",
				description: 'CSS selectors. When provided, only matching HTML subtrees (and their descendants) are kept before each crawled page is converted to Markdown. When omitted, the entire document is kept. Examples: "article.main", "#content", "[role=main]".',
				routing: { send: { property: 'includeSelectors', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'number',
				default: 86400000,
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 1 day (86400000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { send: { property: 'maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Max Depth',
				name: 'maxDepth',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0},
				description: 'Maximum link depth from the starting URL (0 = only the starting page)',
				routing: { send: { property: 'maxDepth', type: 'body' } },
			},
			{
				displayName: 'Max Pages',
				name: 'maxPages',
				type: 'number',
				default: 100,
				typeOptions: {"minValue":1,"maxValue":500},
				description: 'Maximum number of pages to crawl. Hard cap: 500.',
				routing: { send: { property: 'maxPages', type: 'body' } },
			},
			{
				displayName: 'OCR',
				name: 'pdfOcr',
				type: 'boolean',
				default: false,
				description: 'Whether true, OCR the selected PDF pages that have no usable text layer (scans), replacing each recovered page\'s text with the OCR result while pages with a real text layer keep it. Billed at 1 credit per page OCR actually recovered, on top of the base request cost.',
				routing: { send: { property: 'pdf.ocr', type: 'body' } },
			},
			{
				displayName: 'Settle Animations',
				name: 'settleAnimations',
				type: 'boolean',
				default: false,
				description: 'Whether true, waits briefly for CSS and transition animations to settle before extracting each crawled page. Defaults to false. This adds a bit of latency in exchange for more stable output on animated pages.',
				routing: { send: { property: 'settleAnimations', type: 'body' } },
			},
			{
				displayName: 'Shorten Base64 Images',
				name: 'shortenBase64Images',
				type: 'boolean',
				default: true,
				description: 'Whether truncate base64-encoded image data in the Markdown output',
				routing: { send: { property: 'shortenBase64Images', type: 'body' } },
			},
			{
				displayName: 'Should Parse',
				name: 'pdfShouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether true, PDF pages are fetched and parsed. When false, PDF pages are skipped entirely (not included in results and not counted as failures).',
				routing: { send: { property: 'pdf.shouldParse', type: 'body' } },
			},
			{
				displayName: 'Start',
				name: 'pdfStart',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First 1-based PDF page to parse. When omitted, parsing starts at the first page.',
				routing: { send: { property: 'pdf.start', type: 'body' } },
			},
			{
				displayName: 'Stop After MS',
				name: 'stopAfterMs',
				type: 'number',
				default: 80000,
				typeOptions: {"minValue":10000,"maxValue":110000},
				description: 'Soft time budget for the crawl in milliseconds. After each scrape, the crawler checks the elapsed time and, if exceeded, returns the pages collected so far instead of continuing. Min: 10000 (10s). Max: 110000 (110s). Default: 80000 (80s).',
				routing: { send: { property: 'stopAfterMs', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
			{
				displayName: 'URL Regex',
				name: 'urlRegex',
				type: 'string',
				default: "",
				description: 'Regex pattern. Only URLs matching this pattern will be followed and scraped.',
				routing: { send: { property: 'urlRegex', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Use Main Content Only',
				name: 'useMainContentOnly',
				type: 'boolean',
				default: false,
				description: 'Whether extract only the main content, stripping headers, footers, sidebars, and navigation',
				routing: { send: { property: 'useMainContentOnly', type: 'body' } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load for each crawled page. Min: 0. Max: 30000 (30 seconds).',
				routing: { send: { property: 'waitForMs', type: 'body' } },
			},
			{
				displayName: 'ZDR',
				name: 'zdr',
				type: 'options',
				default: "disabled",
				options: [{ name: 'Disabled', value: "disabled" }, { name: 'Enabled', value: "enabled" }],
				description: 'Set to enabled to bypass shared caches and omit request and response content from retained usage logs. Requires zero data retention to be enabled for your organization (contact support@context.dev), otherwise the request fails with ZDR_NOT_ENABLED. Successful ZDR responses include X-Context-ZDR: true.',
				routing: { send: { property: 'zdr', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		displayOptions: { show: { resource: ['webScraping'], operation: ['webSearch'] } },
		required: true,
		default: "",
		description: 'Search query. Accepts natural language as well as Google-style search operators such as `site:`, `-site:`, `inurl:`, `intitle:`, quoted phrases, and `OR`.',
		routing: { send: { property: 'query', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['webSearch'] } },
		options: [
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				default: "af",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'An', value: "an" }, { name: 'Ao', value: "ao" }, { name: 'Aq', value: "aq" }, { name: 'Ar', value: "ar" }, { name: 'As', value: "as" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bt', value: "bt" }, { name: 'Bv', value: "bv" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cc', value: "cc" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Ck', value: "ck" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cu', value: "cu" }, { name: 'Cv', value: "cv" }, { name: 'Cx', value: "cx" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Eh', value: "eh" }, { name: 'Er', value: "er" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fk', value: "fk" }, { name: 'Fm', value: "fm" }, { name: 'Fo', value: "fo" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gh', value: "gh" }, { name: 'Gi', value: "gi" }, { name: 'Gl', value: "gl" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gs', value: "gs" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hm', value: "hm" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'In', value: "in" }, { name: 'Io', value: "io" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Ki', value: "ki" }, { name: 'Km', value: "km" }, { name: 'Kn', value: "kn" }, { name: 'Kp', value: "kp" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Li', value: "li" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Mg', value: "mg" }, { name: 'Mh', value: "mh" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mp', value: "mp" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'MS', value: "ms" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Nf', value: "nf" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nr', value: "nr" }, { name: 'Nu', value: "nu" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pm', value: "pm" }, { name: 'Pn', value: "pn" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Pw', value: "pw" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sb', value: "sb" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Sh', value: "sh" }, { name: 'Si', value: "si" }, { name: 'Sj', value: "sj" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tf', value: "tf" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tk', value: "tk" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'To', value: "to" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tv', value: "tv" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Um', value: "um" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Va', value: "va" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Vu', value: "vu" }, { name: 'Wf', value: "wf" }, { name: 'Ws', value: "ws" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Two-letter ISO 3166-1 alpha-2 country code to localize results to a specific country (maps to Google\'s `gl` parameter). Example: "us", "gb", "de".',
				routing: { send: { property: 'country', type: 'body' } },
			},
			{
				displayName: 'Enabled',
				name: 'markdownOptionsEnabled',
				type: 'boolean',
				default: false,
				description: 'Whether scrape each result to Markdown. Off by default to keep search cheap and fast.',
				routing: { send: { property: 'markdownOptions.enabled', type: 'body' } },
			},
			{
				displayName: 'End',
				name: 'markdownOptionsPdfEnd',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last PDF page to parse (1-based, inclusive). Defaults to the final page. Must be >= start.',
				routing: { send: { property: 'markdownOptions.pdf.end', type: 'body' } },
			},
			{
				displayName: 'Exclude Domains',
				name: 'excludeDomains',
				type: 'string',
				default: "",
				description: 'Blocklist — drop results from these domains. Example: ["pinterest.com", "reddit.com"].',
				routing: { send: { property: 'excludeDomains', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Freshness',
				name: 'freshness',
				type: 'options',
				default: "last_24_hours",
				options: [{ name: 'Last 24 Hours', value: "last_24_hours" }, { name: 'Last Month', value: "last_month" }, { name: 'Last Week', value: "last_week" }, { name: 'Last Year', value: "last_year" }],
				description: 'Restrict results to content published within this window',
				routing: { send: { property: 'freshness', type: 'body' } },
			},
			{
				displayName: 'Include Domains',
				name: 'includeDomains',
				type: 'string',
				default: "",
				description: 'Allowlist — only return results from these domains. Example: ["arxiv.org", "github.com"].',
				routing: { send: { property: 'includeDomains', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Include Frames',
				name: 'markdownOptionsIncludeFrames',
				type: 'boolean',
				default: false,
				description: 'Whether render iframe contents into the Markdown',
				routing: { send: { property: 'markdownOptions.includeFrames', type: 'body' } },
			},
			{
				displayName: 'Include Images',
				name: 'markdownOptionsIncludeImages',
				type: 'boolean',
				default: false,
				description: 'Whether emit image references in the Markdown',
				routing: { send: { property: 'markdownOptions.includeImages', type: 'body' } },
			},
			{
				displayName: 'Include Links',
				name: 'markdownOptionsIncludeLinks',
				type: 'boolean',
				default: true,
				description: 'Whether keep hyperlinks in the Markdown',
				routing: { send: { property: 'markdownOptions.includeLinks', type: 'body' } },
			},
			{
				displayName: 'Max Age MS',
				name: 'markdownOptionsMaxAgeMs',
				type: 'number',
				default: 86400000,
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Cache TTL in ms for scraped Markdown keyed by URL + options. Default 1 day, max 30 days. Set to 0 to force a fresh scrape.',
				routing: { send: { property: 'markdownOptions.maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Num Results',
				name: 'numResults',
				type: 'number',
				default: 10,
				typeOptions: {"minValue":10,"maxValue":100},
				description: 'Number of results to request and return (10–100). Defaults to 10.',
				routing: { send: { property: 'numResults', type: 'body' } },
			},
			{
				displayName: 'Query Fanout',
				name: 'queryFanout',
				type: 'boolean',
				default: false,
				description: 'Whether expand the query into multiple parallel variants for broader recall',
				routing: { send: { property: 'queryFanout', type: 'body' } },
			},
			{
				displayName: 'Shorten Base64 Images',
				name: 'markdownOptionsShortenBase64Images',
				type: 'boolean',
				default: true,
				description: 'Whether truncate inline base64 image payloads to keep responses small',
				routing: { send: { property: 'markdownOptions.shortenBase64Images', type: 'body' } },
			},
			{
				displayName: 'Should Parse',
				name: 'markdownOptionsPdfShouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether parse PDF URLs. When false, PDF results are skipped with WEBSITE_ACCESS_ERROR.',
				routing: { send: { property: 'markdownOptions.pdf.shouldParse', type: 'body' } },
			},
			{
				displayName: 'Start',
				name: 'markdownOptionsPdfStart',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First PDF page to parse (1-based, inclusive). Defaults to page 1.',
				routing: { send: { property: 'markdownOptions.pdf.start', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'markdownOptionsTimeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'markdownOptions.timeoutMS', type: 'body' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
			{
				displayName: 'Use Main Content Only',
				name: 'markdownOptionsUseMainContentOnly',
				type: 'boolean',
				default: false,
				description: 'Whether strip nav, header, footer, and sidebar — keep only the primary article content',
				routing: { send: { property: 'markdownOptions.useMainContentOnly', type: 'body' } },
			},
			{
				displayName: 'Wait for MS',
				name: 'markdownOptionsWaitForMs',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Extra wait after page load before rendering, in ms (0–30000). Useful for JS-heavy pages.',
				routing: { send: { property: 'markdownOptions.waitForMs', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Viewport',
		name: 'viewport',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeScreenshot'] } },
		options: [
			{
				displayName: 'Width',
				name: 'width',
				type: 'number',
				default: 1920,
				typeOptions: {"minValue":240,"maxValue":7680},
				description: 'Viewport width in pixels',
			},
			{
				displayName: 'Height',
				name: 'height',
				type: 'number',
				default: 1080,
				typeOptions: {"minValue":240,"maxValue":4320},
				description: 'Viewport height in pixels',
			},
		],
		routing: { request: { qs: { "viewport": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['webScraping'], operation: ['scrapeScreenshot'] } },
		options: [
			{
				displayName: 'Clear Popups',
				name: 'clearPopups',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter for comprehensive popup cleanup. If \'true\', the browser dismisses detected cookie/consent UI and clears other detected obstructive popups and overlays before capture. If \'false\' or not provided, this parameter requests no cleanup; handleCookiePopup can still request cookie/consent handling independently.',
				routing: { request: { qs: { "clearPopups": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Color Scheme',
				name: 'colorScheme',
				type: 'options',
				default: "light",
				options: [{ name: 'Dark', value: "dark" }, { name: 'Light', value: "light" }],
				description: 'Optional parameter to choose the site\'s visual theme in the screenshot. Use \'light\' or \'dark\' when the site offers both appearances.',
				routing: { request: { qs: { "colorScheme": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				default: "ad",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'Ao', value: "ao" }, { name: 'Ar', value: "ar" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Bq', value: "bq" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cv', value: "cv" }, { name: 'Cw', value: "cw" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gg', value: "gg" }, { name: 'Gh', value: "gh" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'Im', value: "im" }, { name: 'In', value: "in" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Je', value: "je" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Kn', value: "kn" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Me', value: "me" }, { name: 'Mf', value: "mf" }, { name: 'Mg', value: "mg" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Si', value: "si" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'Ss', value: "ss" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sx', value: "sx" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Fetch the target page through a residential proxy in this country (ISO 3166-1 alpha-2)',
				routing: { request: { qs: { "country": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Direct URL',
				name: 'directUrl',
				type: 'string',
				default: "",
				description: 'A specific URL to screenshot directly, bypassing domain resolution (e.g., \'https://example.com/pricing\'). When provided, the screenshot is taken of this exact URL. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "directUrl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: "",
				description: 'Domain name to take screenshot of (e.g., \'example.com\', \'google.com\'). The domain will be automatically normalized and validated. You must provide either \'domain\' or \'directUrl\', but not both.',
				routing: { request: { qs: { "domain": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Full Screenshot',
				name: 'fullScreenshot',
				type: 'options',
				default: "true",
				options: [{ name: 'False', value: "false" }, { name: 'True', value: "true" }],
				description: 'Optional parameter to determine screenshot type. If \'true\', takes a full page screenshot capturing all content. If \'false\' or not provided, takes a viewport screenshot (standard browser view).',
				routing: { request: { qs: { "fullScreenshot": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Handle Cookie Popup',
				name: 'handleCookiePopup',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to control cookie/consent popup handling. If \'true\', we dismiss cookie banner before capture. If \'false\' or not provided, captures the page without that step.',
				routing: { request: { qs: { "handleCookiePopup": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached screenshot if a prior screenshot for the same parameters exists and is younger than this many milliseconds. Defaults to 1 day (86400000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always capture fresh.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Page',
				name: 'page',
				type: 'options',
				default: "login",
				options: [{ name: 'Blog', value: "blog" }, { name: 'Careers', value: "careers" }, { name: 'Contact', value: "contact" }, { name: 'Login', value: "login" }, { name: 'Pricing', value: "pricing" }, { name: 'Privacy', value: "privacy" }, { name: 'Signup', value: "signup" }, { name: 'Terms', value: "terms" }],
				description: 'Optional parameter to specify which page type to screenshot. If provided, the system will scrape the domain\'s links and use heuristics to find the most appropriate URL for the specified page type (30 supported languages). If not provided, screenshots the main domain landing page. Only applicable when using \'domain\', not \'directUrl\'.',
				routing: { request: { qs: { "page": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Scroll Offset',
				name: 'scrollOffset',
				type: 'string',
				default: "",
				typeOptions: {"minValue":0,"maxValue":100000},
				description: 'Optional vertical scroll offset in pixels for capturing a long page in viewport-sized chunks. When provided, the full page is captured once and the returned image is the viewport-sized slice that begins at this Y offset (e.g. request scrollOffset=0, then 1080, then 2160 to walk a 1920x1080 landing page top to bottom). The final slice may be shorter than the viewport height. Takes precedence over fullScreenshot. Max: 100000.',
				routing: { request: { qs: { "scrollOffset": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Wait for MS',
				name: 'waitForMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":30000},
				description: 'Optional browser wait time in milliseconds after initial page load before taking the screenshot. Min: 0. Max: 30000 (30 seconds). Defaults to 3000 ms when omitted.',
				routing: { request: { qs: { "waitForMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'ZDR',
				name: 'zdr',
				type: 'options',
				default: "disabled",
				options: [{ name: 'Disabled', value: "disabled" }, { name: 'Enabled', value: "enabled" }],
				description: 'Set to enabled to bypass shared caches and omit request and response content from retained usage logs. Requires zero data retention to be enabled for your organization (contact support@context.dev), otherwise the request fails with ZDR_NOT_ENABLED. Successful ZDR responses include X-Context-ZDR: true.',
				routing: { request: { qs: { "zdr": '={{ $value || undefined }}' } } },
			},
		],
	},
];
