import type { INodeProperties } from 'n8n-workflow';

export const newsDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['news'] } },
			options: [
			{ name: 'Search Company News', value: 'searchCompanyNews', action: 'Search company news', description: 'Searches live and historical company news for one company, identified in searchBy by name, domain, ticker (optionally disambiguated by exchange), or ISIN. Results can be filtered by publisher domain, publisher country, article language, article type, and published-at date, and include stable story IDs, source metadata, verified entity relevance, and cursor pagination.', routing: { request: { method: 'POST', url: '/news/search' } } },
			],
			default: 'searchCompanyNews',
		},
	{
		displayName: 'Type',
		name: 'searchByType',
		type: 'options',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "entity",
		options: [{ name: 'Entity', value: "entity" }],
		description: 'How to search. Only entity search is supported.',
		routing: { send: { property: 'searchBy.type', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'searchByEntityType',
		type: 'options',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "name",
		options: [{ name: 'Domain', value: "domain" }, { name: 'ISIN', value: "isin" }, { name: 'Name', value: "name" }, { name: 'Ticker', value: "ticker" }],
		routing: { send: { property: 'searchBy.entity.type', type: 'body' } },
	},
	{
		displayName: 'Name',
		name: 'searchByEntityName',
		type: 'string',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "",
		description: 'Company name',
		routing: { send: { property: 'searchBy.entity.name', type: 'body' } },
	},
	{
		displayName: 'Domain',
		name: 'searchByEntityDomain',
		type: 'string',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "",
		description: 'Company website domain, such as apple.com',
		routing: { send: { property: 'searchBy.entity.domain', type: 'body' } },
	},
	{
		displayName: 'Ticker',
		name: 'searchByEntityTicker',
		type: 'string',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "",
		description: 'Public-company ticker',
		routing: { send: { property: 'searchBy.entity.ticker', type: 'body' } },
	},
	{
		displayName: 'ISIN',
		name: 'searchByEntityIsin',
		type: 'string',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "",
		description: 'International Securities Identification Number',
		routing: { send: { property: 'searchBy.entity.isin', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'sortByType',
		type: 'options',
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		required: true,
		default: "relevance",
		options: [{ name: 'Newest', value: "newest" }, { name: 'Relevance', value: "relevance" }],
		description: 'Result ordering',
		routing: { send: { property: 'sortBy.type', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['news'], operation: ['searchCompanyNews'] } },
		options: [
			{
				displayName: 'Article Language',
				name: 'filterByArticleLanguage',
				type: 'string',
				default: "",
				description: 'Article languages to include. Up to 3.',
				routing: { send: { property: 'filterBy.articleLanguage', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Article Type',
				name: 'filterByArticleType',
				type: 'string',
				default: "",
				description: 'Article types to include. Up to 3.',
				routing: { send: { property: 'filterBy.articleType', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque next_cursor from the previous response, or null for the first page',
				routing: { send: { property: 'cursor', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Exchange',
				name: 'searchByEntityExchange',
				type: 'options',
				default: "AMEX",
				options: [{ name: 'AMEX', value: "AMEX" }, { name: 'AMS', value: "AMS" }, { name: 'AQS', value: "AQS" }, { name: 'ASX', value: "ASX" }, { name: 'ATH', value: "ATH" }, { name: 'BER', value: "BER" }, { name: 'BME', value: "BME" }, { name: 'BRU', value: "BRU" }, { name: 'BSE', value: "BSE" }, { name: 'BUD', value: "BUD" }, { name: 'BUE', value: "BUE" }, { name: 'BVC', value: "BVC" }, { name: 'CBOE', value: "CBOE" }, { name: 'CNQ', value: "CNQ" }, { name: 'CPH', value: "CPH" }, { name: 'DFM', value: "DFM" }, { name: 'DOH', value: "DOH" }, { name: 'DUB', value: "DUB" }, { name: 'DUS', value: "DUS" }, { name: 'DXE', value: "DXE" }, { name: 'EGX', value: "EGX" }, { name: 'FSX', value: "FSX" }, { name: 'HAM', value: "HAM" }, { name: 'HEL', value: "HEL" }, { name: 'HKSE', value: "HKSE" }, { name: 'HOSE', value: "HOSE" }, { name: 'ICE', value: "ICE" }, { name: 'IOB', value: "IOB" }, { name: 'IST', value: "IST" }, { name: 'JKT', value: "JKT" }, { name: 'JNB', value: "JNB" }, { name: 'JPX', value: "JPX" }, { name: 'KLS', value: "KLS" }, { name: 'KOE', value: "KOE" }, { name: 'KSC', value: "KSC" }, { name: 'KUW', value: "KUW" }, { name: 'LIS', value: "LIS" }, { name: 'LSE', value: "LSE" }, { name: 'MCX', value: "MCX" }, { name: 'MEX', value: "MEX" }, { name: 'MIL', value: "MIL" }, { name: 'MUN', value: "MUN" }, { name: 'NASDAQ', value: "NASDAQ" }, { name: 'NEO', value: "NEO" }, { name: 'NSE', value: "NSE" }, { name: 'NYSE', value: "NYSE" }, { name: 'NZE', value: "NZE" }, { name: 'OSL', value: "OSL" }, { name: 'OTC', value: "OTC" }, { name: 'PAR', value: "PAR" }, { name: 'PNK', value: "PNK" }, { name: 'PRA', value: "PRA" }, { name: 'RIS', value: "RIS" }, { name: 'SAO', value: "SAO" }, { name: 'SAU', value: "SAU" }, { name: 'SES', value: "SES" }, { name: 'SET', value: "SET" }, { name: 'SGO', value: "SGO" }, { name: 'SHH', value: "SHH" }, { name: 'SHZ', value: "SHZ" }, { name: 'SIX', value: "SIX" }, { name: 'STO', value: "STO" }, { name: 'STU', value: "STU" }, { name: 'TAI', value: "TAI" }, { name: 'TAL', value: "TAL" }, { name: 'TLV', value: "TLV" }, { name: 'TSX', value: "TSX" }, { name: 'TSXV', value: "TSXV" }, { name: 'TWO', value: "TWO" }, { name: 'VIE', value: "VIE" }, { name: 'WSE', value: "WSE" }, { name: 'XETRA', value: "XETRA" }],
				description: 'Stock exchange the ticker trades on, used to disambiguate tickers listed on multiple exchanges',
				routing: { send: { property: 'searchBy.entity.exchange', type: 'body' } },
			},
			{
				displayName: 'From',
				name: 'filterByDateFrom',
				type: 'number',
				default: 0,
				description: 'Inclusive start of the published-at window, in epoch milliseconds',
				routing: { send: { property: 'filterBy.date.from', type: 'body' } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { send: { property: 'limit', type: 'body' } },
			},
			{
				displayName: 'Source Country',
				name: 'filterBySourceCountry',
				type: 'string',
				default: "",
				description: 'Publisher countries to include, as lowercase ISO 3166-1 alpha-2 codes. Up to 3.',
				routing: { send: { property: 'filterBy.sourceCountry', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Source Domain',
				name: 'filterBySourceDomain',
				type: 'string',
				default: "",
				description: 'Publisher domains to include. Up to 3.',
				routing: { send: { property: 'filterBy.sourceDomain', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'To',
				name: 'filterByDateTo',
				type: 'number',
				default: 0,
				description: 'Inclusive end of the published-at window, in epoch milliseconds',
				routing: { send: { property: 'filterBy.date.to', type: 'body' } },
			},
		],
	},
];
