import type { INodeProperties } from 'n8n-workflow';

export const monitorsDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['monitors'] } },
			options: [
			{ name: 'Create a monitor', value: 'createMonitor', action: 'Create a monitor', description: 'Creates a monitor. The request body is a union of the supported target/change detection combinations. The monitor runs immediately after creation to create its initial baseline', routing: { request: { method: 'POST', url: '/monitors' } } },
			{ name: 'Delete a monitor', value: 'deleteMonitor', action: 'Delete a monitor', routing: { request: { method: 'DELETE', url: '=/monitors/{{ $parameter["monitorId"] }}' } } },
			{ name: 'Get a Change', value: 'getChange', action: 'Get a change', routing: { request: { method: 'GET', url: '=/monitors/changes/{{ $parameter["changeId"] }}' } } },
			{ name: 'Get a monitor', value: 'getMonitor', action: 'Get a monitor', routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}' } } },
			{ name: 'List Changes', value: 'listChanges', action: 'List changes', description: 'Returns an account-wide feed of detected changes across monitors', routing: { request: { method: 'GET', url: '/monitors/changes' } } },
			{ name: 'List changes for a monitor', value: 'listMonitorChanges', action: 'List changes for a monitor', routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}/changes' } } },
			{ name: 'List Monitor Runs', value: 'listMonitorRuns', action: 'List monitor runs', routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}/runs' } } },
			{ name: 'List Monitors', value: 'listMonitors', action: 'List monitors', description: 'Lists monitors for the authenticated organization. Supports free-text search (`q` over `search_by` fields, `prefix` or `exact` via `search_type`) plus status/type/tag filters. Results are paginated via the opaque `cursor`', routing: { request: { method: 'GET', url: '/monitors' } } },
			{ name: 'List Runs', value: 'listAccountRuns', action: 'List runs', description: 'Returns an account-wide feed of monitor runs across all monitors', routing: { request: { method: 'GET', url: '/monitors/runs' } } },
			{ name: 'Monitor Credit Usage', value: 'listMonitorCreditUsage', action: 'Monitor credit usage', description: 'Returns credits charged per monitor over an optional [since, until] window, newest spenders first', routing: { request: { method: 'GET', url: '/monitors/credit-usage' } } },
			{ name: 'Monitor Limits', value: 'getMonitorLimits', action: 'Monitor limits', description: 'Returns how many monitors the account has and the maximum it allows', routing: { request: { method: 'GET', url: '/monitors/limits' } } },
			{ name: 'Retrieve a Monitor Run', value: 'getMonitorRun', action: 'Retrieve a monitor run', description: 'Fetches one run for a monitor, including lifecycle status, timing, credits charged, and any detected change', routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}/runs/{{ $parameter["runId"] }}' } } },
			{ name: 'Rotate a Monitor Webhook Secret', value: 'rotateMonitorWebhookSecret', action: 'Rotate a monitor webhook secret', description: 'Generates a new signing secret for the monitor\'s webhook and returns the updated monitor (including the new `webhook.secret`). The previous secret stops signing deliveries immediately, so update your endpoint before rotating.', routing: { request: { method: 'POST', url: '=/monitors/{{ $parameter["monitorId"] }}/webhook/rotate-secret' } } },
			{ name: 'Run a Monitor Now', value: 'runMonitorNow', action: 'Run a monitor now', description: 'Triggers an immediate run of the monitor outside its normal schedule. The run is queued and processed asynchronously.', routing: { request: { method: 'POST', url: '=/monitors/{{ $parameter["monitorId"] }}/run' } } },
			{ name: 'Update a monitor', value: 'updateMonitor', action: 'Update a monitor', description: 'Updates a monitor. If `target` or `change_detection` changes, the monitor creates a new baseline. Unsupported target/change detection combinations are rejected', routing: { request: { method: 'PATCH', url: '=/monitors/{{ $parameter["monitorId"] }}' } } },
			],
			default: 'createMonitor',
		},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "",
		routing: { send: { property: 'name', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'targetType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "page",
		options: [{ name: 'Extract', value: "extract" }, { name: 'Page', value: "page" }, { name: 'Sitemap', value: "sitemap" }],
		routing: { send: { property: 'target.type', type: 'body' } },
	},
	{
		displayName: 'URL',
		name: 'targetUrl',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "",
		description: 'Sitemap URL to monitor',
		routing: { send: { property: 'target.url', type: 'body' } },
	},
	{
		displayName: 'Instructions',
		name: 'targetInstructions',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "",
		description: 'Plain-language goal describing which page changes matter. When provided without change_detection, semantic detection is inferred.',
		routing: { send: { property: 'target.instructions', type: 'body' } },
	},
	{
		displayName: 'Target',
		name: 'target',
		type: 'json',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "{}",
		description: 'Watch the monitor-relevant pages of a site for meaningful changes. A crawl guided by `schema`/`instructions` selects up to `max_pages` relevant pages to track; each run re-checks exactly those pages, and confirmed content changes are judged for relevance against the monitor\'s `instructions` (and `schema`, when provided). The tracked page set is refreshed by a periodic re-discovery crawl.',
		routing: { send: { property: 'target', type: 'body', value: '={{ $value ? JSON.parse($value) : undefined }}' } },
	},
	{
		displayName: 'Type',
		name: 'changeDetectionType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "exact",
		options: [{ name: 'Exact', value: "exact" }, { name: 'Semantic', value: "semantic" }],
		routing: { send: { property: 'change_detection.type', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'scheduleType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "interval",
		options: [{ name: 'Interval', value: "interval" }],
		routing: { send: { property: 'schedule.type', type: 'body' } },
	},
	{
		displayName: 'Frequency',
		name: 'scheduleFrequency',
		type: 'number',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: 1,
		typeOptions: {"minValue":1,"maxValue":525600},
		description: 'Number of units between runs. The resulting interval (frequency × unit) must be at least 10 minutes and at most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is days).',
		routing: { send: { property: 'schedule.frequency', type: 'body' } },
	},
	{
		displayName: 'Unit',
		name: 'scheduleUnit',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "minutes",
		options: [{ name: 'Days', value: "days" }, { name: 'Hours', value: "hours" }, { name: 'Minutes', value: "minutes" }],
		routing: { send: { property: 'schedule.unit', type: 'body' } },
	},
	{
		displayName: 'URL',
		name: 'webhookUrl',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		required: true,
		default: "",
		description: 'Webhook URL events are delivered to',
		routing: { send: { property: 'webhook.url', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['createMonitor'] } },
		options: [
			{
				displayName: 'Confidence Threshold',
				name: 'changeDetectionConfidenceThreshold',
				type: 'number',
				default: 0.75,
				typeOptions: {"minValue":0,"maxValue":1},
				routing: { send: { property: 'change_detection.confidence_threshold', type: 'body' } },
			},
			{
				displayName: 'Events',
				name: 'webhookEvents',
				type: 'string',
				default: "",
				description: 'Events delivered to this endpoint. `change.detected` fires only when a run detects a change; `run.completed` fires on every completed run — including runs that detected no change — and embeds the change when one was detected. Defaults to `["change.detected"]` when omitted.',
				routing: { send: { property: 'webhook.events', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Exclude',
				name: 'targetExclude',
				type: 'string',
				default: "",
				description: 'URL path patterns to exclude (max 50)',
				routing: { send: { property: 'target.exclude', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'targetFollowSubdomains',
				type: 'boolean',
				default: false,
				routing: { send: { property: 'target.follow_subdomains', type: 'body' } },
			},
			{
				displayName: 'Include',
				name: 'targetInclude',
				type: 'string',
				default: "",
				description: 'URL path patterns to include (max 50)',
				routing: { send: { property: 'target.include', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Depth',
				name: 'targetMaxDepth',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":10},
				description: 'Optional maximum link depth from the starting URL (0 = only the starting page)',
				routing: { send: { property: 'target.max_depth', type: 'body' } },
			},
			{
				displayName: 'Max Pages',
				name: 'targetMaxPages',
				type: 'number',
				default: 10,
				typeOptions: {"minValue":1,"maxValue":50},
				description: 'Maximum number of pages to track',
				routing: { send: { property: 'target.max_pages', type: 'body' } },
			},
			{
				displayName: 'Max URLs',
				name: 'targetMaxUrls',
				type: 'number',
				default: 5000,
				typeOptions: {"minValue":1,"maxValue":10000},
				description: 'Maximum number of sitemap URLs to track (capped at 10,000)',
				routing: { send: { property: 'target.max_urls', type: 'body' } },
			},
			{
				displayName: 'Mode',
				name: 'mode',
				type: 'options',
				default: "web",
				options: [{ name: 'Web', value: "web" }],
				description: 'Top-level monitor category. Always `web` today; the concrete behavior is described by `target` and `change_detection`.',
				routing: { send: { property: 'mode', type: 'body' } },
			},
			{
				displayName: 'Normalize Whitespace',
				name: 'targetNormalizeWhitespace',
				type: 'boolean',
				default: true,
				description: 'Whether normalize whitespace before comparing or analyzing text',
				routing: { send: { property: 'target.normalize_whitespace', type: 'body' } },
			},
			{
				displayName: 'Schema',
				name: 'targetSchema',
				type: 'json',
				default: "{}",
				description: 'JSON Schema describing the data you care about. It is used three ways: it guides which pages are selected for tracking, it gives the change judge extra context on which changes matter (alongside `instructions`), and it defines the shape of the baseline `data` snapshot on GET /monitors/{monitor_id} (refreshed at most about once a day). It is not a response format for changes: change events and webhook payloads always contain diffs, summaries, and evidence excerpts — never data in this schema\'s shape. If omitted, a default summary + key-points schema is used.',
				routing: { send: { property: 'target.schema', type: 'body', value: '={{ $value ? JSON.parse($value) : undefined }}' } },
			},
			{
				displayName: 'Secret',
				name: 'webhookSecret',
				type: 'string',
				typeOptions: { password: true },
				default: "",
				description: 'Signing secret used to verify webhook authenticity. Each delivery includes an `X-Context-Signature: t=&lt;unix&gt;,v1=&lt;hmac&gt;` header, where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret. Recompute it with a constant-time compare and reject stale timestamps to prevent replay. Generated by the API; cannot be set by clients.',
				routing: { send: { property: 'webhook.secret', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'User-defined tags for grouping and filtering monitors and their changes. Duplicates are removed.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Webhook',
				name: 'webhook',
				type: 'string',
				default: "",
				routing: { send: { property: 'webhook', type: 'body', value: '={{ $value || undefined }}' } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitors'] } },
		options: [
			{
				displayName: 'Change Detection Type',
				name: 'changeDetectionType',
				type: 'options',
				default: "exact",
				options: [{ name: 'Exact', value: "exact" }, { name: 'Semantic', value: "semantic" }],
				description: 'Filter by change detection type',
				routing: { request: { qs: { "change_detection_type": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque pagination cursor from a previous response',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Q',
				name: 'q',
				type: 'string',
				default: "",
				description: 'Free-text search term, matched against the fields named in `search_by`',
				routing: { request: { qs: { "q": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Search By',
				name: 'searchBy',
				type: 'string',
				default: "",
				description: 'Comma-separated fields to search with `q`. Defaults to all of them. Note `instructions` only exists on extract monitors.',
				routing: { request: { qs: { "search_by": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Search Type',
				name: 'searchType',
				type: 'options',
				default: "exact",
				options: [{ name: 'Exact', value: "exact" }, { name: 'Prefix', value: "prefix" }],
				description: '`prefix` for as-you-type prefix matching (default), `exact` for full-token matching',
				routing: { request: { qs: { "search_type": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: "active",
				options: [{ name: 'Active', value: "active" }, { name: 'Failed', value: "failed" }, { name: 'Paused', value: "paused" }],
				description: 'Filter monitors by lifecycle status',
				routing: { request: { qs: { "status": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tag',
				name: 'tag',
				type: 'string',
				default: "",
				description: 'Filter to items that have this tag',
				routing: { request: { qs: { "tag": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Comma-separated list of tags to filter by (matches monitors having any of them)',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Target Type',
				name: 'targetType',
				type: 'options',
				default: "page",
				options: [{ name: 'Extract', value: "extract" }, { name: 'Page', value: "page" }, { name: 'Sitemap', value: "sitemap" }],
				description: 'Filter by target type',
				routing: { request: { qs: { "target_type": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['getMonitor'] } },
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
	},
	{
		displayName: 'Type',
		name: 'targetType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "page",
		options: [{ name: 'Extract', value: "extract" }, { name: 'Page', value: "page" }, { name: 'Sitemap', value: "sitemap" }],
		routing: { send: { property: 'target.type', type: 'body' } },
	},
	{
		displayName: 'URL',
		name: 'targetUrl',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "",
		description: 'Sitemap URL to monitor',
		routing: { send: { property: 'target.url', type: 'body' } },
	},
	{
		displayName: 'Instructions',
		name: 'targetInstructions',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "",
		description: 'Plain-language goal describing which page changes matter. When provided without change_detection, semantic detection is inferred.',
		routing: { send: { property: 'target.instructions', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'changeDetectionType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "exact",
		options: [{ name: 'Exact', value: "exact" }, { name: 'Semantic', value: "semantic" }],
		routing: { send: { property: 'change_detection.type', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'scheduleType',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "interval",
		options: [{ name: 'Interval', value: "interval" }],
		routing: { send: { property: 'schedule.type', type: 'body' } },
	},
	{
		displayName: 'Frequency',
		name: 'scheduleFrequency',
		type: 'number',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: 1,
		typeOptions: {"minValue":1,"maxValue":525600},
		description: 'Number of units between runs. The resulting interval (frequency × unit) must be at least 10 minutes and at most 1 year (e.g. minimum 10 when unit is minutes; maximum 365 when unit is days).',
		routing: { send: { property: 'schedule.frequency', type: 'body' } },
	},
	{
		displayName: 'Unit',
		name: 'scheduleUnit',
		type: 'options',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "minutes",
		options: [{ name: 'Days', value: "days" }, { name: 'Hours', value: "hours" }, { name: 'Minutes', value: "minutes" }],
		routing: { send: { property: 'schedule.unit', type: 'body' } },
	},
	{
		displayName: 'URL',
		name: 'webhookUrl',
		type: 'string',
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		required: true,
		default: "",
		description: 'Webhook URL events are delivered to',
		routing: { send: { property: 'webhook.url', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['updateMonitor'] } },
		options: [
			{
				displayName: 'Confidence Threshold',
				name: 'changeDetectionConfidenceThreshold',
				type: 'number',
				default: 0.75,
				typeOptions: {"minValue":0,"maxValue":1},
				routing: { send: { property: 'change_detection.confidence_threshold', type: 'body' } },
			},
			{
				displayName: 'Events',
				name: 'webhookEvents',
				type: 'string',
				default: "",
				description: 'Events delivered to this endpoint. `change.detected` fires only when a run detects a change; `run.completed` fires on every completed run — including runs that detected no change — and embeds the change when one was detected. Defaults to `["change.detected"]` when omitted.',
				routing: { send: { property: 'webhook.events', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Exclude',
				name: 'targetExclude',
				type: 'string',
				default: "",
				description: 'URL path patterns to exclude (max 50)',
				routing: { send: { property: 'target.exclude', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'targetFollowSubdomains',
				type: 'boolean',
				default: false,
				routing: { send: { property: 'target.follow_subdomains', type: 'body' } },
			},
			{
				displayName: 'Include',
				name: 'targetInclude',
				type: 'string',
				default: "",
				description: 'URL path patterns to include (max 50)',
				routing: { send: { property: 'target.include', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Depth',
				name: 'targetMaxDepth',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":10},
				description: 'Optional maximum link depth from the starting URL (0 = only the starting page)',
				routing: { send: { property: 'target.max_depth', type: 'body' } },
			},
			{
				displayName: 'Max Pages',
				name: 'targetMaxPages',
				type: 'number',
				default: 10,
				typeOptions: {"minValue":1,"maxValue":50},
				description: 'Maximum number of pages to track',
				routing: { send: { property: 'target.max_pages', type: 'body' } },
			},
			{
				displayName: 'Max URLs',
				name: 'targetMaxUrls',
				type: 'number',
				default: 5000,
				typeOptions: {"minValue":1,"maxValue":10000},
				description: 'Maximum number of sitemap URLs to track (capped at 10,000)',
				routing: { send: { property: 'target.max_urls', type: 'body' } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: "",
				routing: { send: { property: 'name', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Normalize Whitespace',
				name: 'targetNormalizeWhitespace',
				type: 'boolean',
				default: true,
				description: 'Whether normalize whitespace before comparing or analyzing text',
				routing: { send: { property: 'target.normalize_whitespace', type: 'body' } },
			},
			{
				displayName: 'Schema',
				name: 'targetSchema',
				type: 'json',
				default: "{}",
				description: 'JSON Schema describing the data you care about. It is used three ways: it guides which pages are selected for tracking, it gives the change judge extra context on which changes matter (alongside `instructions`), and it defines the shape of the baseline `data` snapshot on GET /monitors/{monitor_id} (refreshed at most about once a day). It is not a response format for changes: change events and webhook payloads always contain diffs, summaries, and evidence excerpts — never data in this schema\'s shape. If omitted, a default summary + key-points schema is used.',
				routing: { send: { property: 'target.schema', type: 'body', value: '={{ $value ? JSON.parse($value) : undefined }}' } },
			},
			{
				displayName: 'Secret',
				name: 'webhookSecret',
				type: 'string',
				typeOptions: { password: true },
				default: "",
				description: 'Signing secret used to verify webhook authenticity. Each delivery includes an `X-Context-Signature: t=&lt;unix&gt;,v1=&lt;hmac&gt;` header, where the HMAC is SHA-256 over `"{t}.{rawRequestBody}"` keyed by this secret. Recompute it with a constant-time compare and reject stale timestamps to prevent replay. Generated by the API; cannot be set by clients.',
				routing: { send: { property: 'webhook.secret', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: "active",
				options: [{ name: 'Active', value: "active" }, { name: 'Paused', value: "paused" }],
				routing: { send: { property: 'status', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'User-defined tags for grouping and filtering monitors and their changes. Duplicates are removed.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Target',
				name: 'target',
				type: 'json',
				default: "{}",
				description: 'Watch the monitor-relevant pages of a site for meaningful changes. A crawl guided by `schema`/`instructions` selects up to `max_pages` relevant pages to track; each run re-checks exactly those pages, and confirmed content changes are judged for relevance against the monitor\'s `instructions` (and `schema`, when provided). The tracked page set is refreshed by a periodic re-discovery crawl.',
				routing: { send: { property: 'target', type: 'body', value: '={{ $value ? JSON.parse($value) : undefined }}' } },
			},
			{
				displayName: 'Webhook',
				name: 'webhook',
				type: 'string',
				default: "",
				routing: { send: { property: 'webhook', type: 'body', value: '={{ $value || undefined }}' } },
			},
		],
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['deleteMonitor'] } },
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitorRuns'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitorRuns'] } },
		options: [
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque pagination cursor from a previous response',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: "queued",
				options: [{ name: 'Completed', value: "completed" }, { name: 'Failed', value: "failed" }, { name: 'Queued', value: "queued" }, { name: 'Running', value: "running" }, { name: 'Skipped', value: "skipped" }],
				description: 'Filter runs by lifecycle status',
				routing: { request: { qs: { "status": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['getMonitorRun'] } },
	},
	{
		displayName: 'Run ID',
		name: 'runId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['getMonitorRun'] } },
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitorChanges'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitorChanges'] } },
		options: [
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque pagination cursor from a previous response',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Since',
				name: 'since',
				type: 'string',
				default: "",
				description: 'Only include items at or after this ISO 8601 timestamp',
				routing: { request: { qs: { "since": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tag',
				name: 'tag',
				type: 'string',
				default: "",
				description: 'Filter to items that have this tag',
				routing: { request: { qs: { "tag": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Until',
				name: 'until',
				type: 'string',
				default: "",
				description: 'Only include items before this ISO 8601 timestamp',
				routing: { request: { qs: { "until": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listAccountRuns'] } },
		options: [
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque pagination cursor from a previous response',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: "queued",
				options: [{ name: 'Completed', value: "completed" }, { name: 'Failed', value: "failed" }, { name: 'Queued', value: "queued" }, { name: 'Running', value: "running" }, { name: 'Skipped', value: "skipped" }],
				description: 'Filter runs by lifecycle status',
				routing: { request: { qs: { "status": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listMonitorCreditUsage'] } },
		options: [
			{
				displayName: 'Since',
				name: 'since',
				type: 'string',
				default: "",
				description: 'Only include items at or after this ISO 8601 timestamp',
				routing: { request: { qs: { "since": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Until',
				name: 'until',
				type: 'string',
				default: "",
				description: 'Only include items before this ISO 8601 timestamp',
				routing: { request: { qs: { "until": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['monitors'], operation: ['listChanges'] } },
		options: [
			{
				displayName: 'Change Detection Type',
				name: 'changeDetectionType',
				type: 'options',
				default: "exact",
				options: [{ name: 'Exact', value: "exact" }, { name: 'Semantic', value: "semantic" }],
				description: 'Filter by change detection type',
				routing: { request: { qs: { "change_detection_type": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Opaque pagination cursor from a previous response',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Monitor ID',
				name: 'monitorId',
				type: 'string',
				default: "",
				description: 'Filter changes to a single monitor',
				routing: { request: { qs: { "monitor_id": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Since',
				name: 'since',
				type: 'string',
				default: "",
				description: 'Only include items at or after this ISO 8601 timestamp',
				routing: { request: { qs: { "since": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tag',
				name: 'tag',
				type: 'string',
				default: "",
				description: 'Filter to items that have this tag',
				routing: { request: { qs: { "tag": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Target Type',
				name: 'targetType',
				type: 'options',
				default: "page",
				options: [{ name: 'Extract', value: "extract" }, { name: 'Page', value: "page" }, { name: 'Sitemap', value: "sitemap" }],
				description: 'Filter by target type',
				routing: { request: { qs: { "target_type": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Until',
				name: 'until',
				type: 'string',
				default: "",
				description: 'Only include items before this ISO 8601 timestamp',
				routing: { request: { qs: { "until": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Change ID',
		name: 'changeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['getChange'] } },
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['runMonitorNow'] } },
	},
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['monitors'], operation: ['rotateMonitorWebhookSecret'] } },
	},
];
