import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['monitors'] };

// ops that carry a monitor_id path param
const idOps = ['get', 'update', 'delete', 'run', 'listChanges', 'listRuns'];
// list-family ops (pagination + filters)
const listOps = ['list', 'listAccountChanges', 'listAccountRuns', 'listChanges', 'listRuns'];

// shared literals (create + update reuse these)
const UNIT_OPTIONS = [
	{ name: 'Minutes', value: 'minutes' },
	{ name: 'Hours', value: 'hours' },
	{ name: 'Days', value: 'days' },
];
const CONFIDENCE_OPTS = { minValue: 0, maxValue: 1, numberPrecision: 2 };
// comma-separated string -> trimmed non-empty array, sent on body key "tags"
const tagsRouting = {
	request: { body: { tags: '={{ $value.split(",").map(s => s.trim()).filter(Boolean) }}' } },
};

const operationField: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show },
	options: [
		{
			name: 'Create Monitor',
			value: 'create',
			action: 'Create a monitor',
			description: 'Create a website monitor that watches a page, sitemap, or extraction target for changes',
			routing: { request: { method: 'POST', url: '/monitors' } },
		},
		{
			name: 'Delete Monitor',
			value: 'delete',
			action: 'Delete a monitor',
			description: 'Delete a monitor by ID',
			routing: { request: { method: 'DELETE', url: '=/monitors/{{ $parameter["monitorId"] }}' } },
		},
		{
			name: 'Get Change',
			value: 'getChange',
			action: 'Get a single change',
			description: 'Retrieve a single detected change by its ID',
			routing: { request: { method: 'GET', url: '=/monitors/changes/{{ $parameter["changeId"] }}' } },
		},
		{
			name: 'Get Monitor',
			value: 'get',
			action: 'Get a monitor',
			description: 'Retrieve a monitor by ID',
			routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}' } },
		},
		{
			name: 'List Account Changes',
			value: 'listAccountChanges',
			action: 'List changes across all monitors',
			description: 'List detected changes across every monitor in the account',
			routing: { request: { method: 'GET', url: '/monitors/changes' } },
		},
		{
			name: 'List Account Runs',
			value: 'listAccountRuns',
			action: 'List runs across all monitors',
			description: 'List monitor runs across every monitor in the account',
			routing: { request: { method: 'GET', url: '/monitors/runs' } },
		},
		{
			name: 'List Monitor Changes',
			value: 'listChanges',
			action: 'List changes for a monitor',
			description: 'List detected changes for a single monitor',
			routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}/changes' } },
		},
		{
			name: 'List Monitor Runs',
			value: 'listRuns',
			action: 'List runs for a monitor',
			description: 'List runs for a single monitor',
			routing: { request: { method: 'GET', url: '=/monitors/{{ $parameter["monitorId"] }}/runs' } },
		},
		{
			name: 'List Monitors',
			value: 'list',
			action: 'List monitors',
			description: 'List monitors in the account',
			routing: { request: { method: 'GET', url: '/monitors' } },
		},
		{
			name: 'Run Monitor',
			value: 'run',
			action: 'Run a monitor now',
			description: 'Trigger an immediate run of a monitor',
			routing: { request: { method: 'POST', url: '=/monitors/{{ $parameter["monitorId"] }}/run' } },
		},
		{
			name: 'Update Monitor',
			value: 'update',
			action: 'Update a monitor',
			description: 'Update a monitor by ID',
			routing: { request: { method: 'PATCH', url: '=/monitors/{{ $parameter["monitorId"] }}' } },
		},
	],
	default: 'list',
};

// ─── path params ────────────────────────────────────────────────────────────────
const pathParams: INodeProperties[] = [
	{
		displayName: 'Monitor ID',
		name: 'monitorId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'mon_123',
		displayOptions: { show: { ...show, operation: idOps } },
	},
	{
		displayName: 'Change ID',
		name: 'changeId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'chg_123',
		displayOptions: { show: { ...show, operation: ['getChange'] } },
	},
];

// ─── create: core + discriminators ────────────────────────────────────────────────
const createCore: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Pricing page watcher',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Target Type',
		name: 'targetType',
		type: 'options',
		default: 'page',
		description: 'What to monitor. Sitemap targets pair with exact detection; extract targets pair with semantic detection.',
		displayOptions: { show: { ...show, operation: ['create'] } },
		options: [
			{ name: 'Page', value: 'page' },
			{ name: 'Sitemap', value: 'sitemap' },
			{ name: 'Extract', value: 'extract' },
		],
		routing: { send: { type: 'body', property: 'target.type' } },
	},
	{
		displayName: 'Target URL',
		name: 'targetUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://stripe.com/pricing',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'target.url' } },
	},
	{
		displayName: 'Normalize Whitespace',
		name: 'normalizeWhitespace',
		type: 'boolean',
		default: false,
		description: 'Whether to normalize whitespace before comparing or analyzing text',
		displayOptions: { show: { ...show, operation: ['create'], targetType: ['page'] } },
		routing: { send: { type: 'body', property: 'target.normalize_whitespace' } },
	},
	{
		displayName: 'Follow Subdomains',
		name: 'followSubdomains',
		type: 'boolean',
		default: false,
		description: 'Whether to follow links into subdomains while extracting',
		displayOptions: { show: { ...show, operation: ['create'], targetType: ['extract'] } },
		routing: { send: { type: 'body', property: 'target.follow_subdomains' } },
	},
	{
		displayName: 'Extract Prompt',
		name: 'extractPrompt',
		type: 'string',
		default: '',
		description: 'Optional natural-language instructions guiding what to extract',
		displayOptions: { show: { ...show, operation: ['create'], targetType: ['extract'] } },
		routing: { send: { type: 'body', property: 'target.prompt' } },
	},
	{
		displayName: 'Extract Schema (JSON)',
		name: 'extractSchema',
		type: 'json',
		default: '',
		description: 'Optional JSON Schema for the structured data to extract. Defaults to a summary + key-points schema.',
		displayOptions: { show: { ...show, operation: ['create'], targetType: ['extract'] } },
		routing: { send: { type: 'body', property: 'target.schema', value: '={{ JSON.parse($value) }}' } },
	},
	{
		displayName: 'Change Detection',
		name: 'changeDetectionType',
		type: 'options',
		default: 'exact',
		displayOptions: { show: { ...show, operation: ['create'] } },
		options: [
			{ name: 'Exact', value: 'exact' },
			{ name: 'Semantic', value: 'semantic' },
		],
		routing: { send: { type: 'body', property: 'change_detection.type' } },
	},
	{
		displayName: 'Semantic Query',
		name: 'semanticQuery',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'the monthly price of the Pro plan',
		description: 'Natural-language query describing the meaning-level change to watch for',
		displayOptions: { show: { ...show, operation: ['create'], changeDetectionType: ['semantic'] } },
		routing: { send: { type: 'body', property: 'change_detection.query' } },
	},
	{
		displayName: 'Confidence Threshold',
		name: 'confidenceThreshold',
		type: 'number',
		default: 0.5,
		typeOptions: CONFIDENCE_OPTS,
		description: 'Minimum confidence (0–1) required to report a semantic change',
		displayOptions: { show: { ...show, operation: ['create'], changeDetectionType: ['semantic'] } },
		routing: { send: { type: 'body', property: 'change_detection.confidence_threshold' } },
	},
	{
		displayName: 'Schedule Frequency',
		name: 'scheduleFrequency',
		type: 'number',
		required: true,
		default: 6,
		typeOptions: { minValue: 1 },
		description: 'Number of units between runs. The total interval (frequency × unit) must be between 10 minutes and 1 year.',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'schedule.frequency' } },
	},
	{
		displayName: 'Schedule Unit',
		name: 'scheduleUnit',
		type: 'options',
		default: 'hours',
		displayOptions: { show: { ...show, operation: ['create'] } },
		options: UNIT_OPTIONS,
		routing: { send: { type: 'body', property: 'schedule.unit' } },
	},
	{
		displayName: 'Schedule Type',
		name: 'scheduleType',
		type: 'hidden',
		default: 'interval',
		displayOptions: { show: { ...show, operation: ['create'] } },
		routing: { send: { type: 'body', property: 'schedule.type' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...show, operation: ['create'] } },
		options: [
			{
				displayName: 'Webhook URL',
				name: 'webhookUrl',
				type: 'string',
				default: '',
				placeholder: 'https://example.com/hooks/context',
				description: 'URL called when a change is detected',
				routing: { send: { type: 'body', property: 'webhook.url' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: '',
				placeholder: 'pricing,marketing',
				description: 'Comma-separated tags for grouping and filtering monitors and their changes',
				routing: tagsRouting,
			},
		],
	},
];

// ─── update: all-optional mutable fields ──────────────────────────────────────────
const updateFields: INodeProperties[] = [
	{
		displayName: 'Update Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { ...show, operation: ['update'] } },
		options: [
			{
				displayName: 'Change Detection Query',
				name: 'updQuery',
				type: 'string',
				default: '',
				description: 'Natural-language query for semantic detection',
				routing: { send: { type: 'body', property: 'change_detection.query' } },
			},
			{
				displayName: 'Confidence Threshold',
				name: 'updConfidence',
				type: 'number',
				default: 0.5,
				typeOptions: CONFIDENCE_OPTS,
				routing: { send: { type: 'body', property: 'change_detection.confidence_threshold' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'updFollowSubdomains',
				type: 'boolean',
				default: false,
				description: 'Whether to follow links into subdomains while extracting',
				routing: { send: { type: 'body', property: 'target.follow_subdomains' } },
			},
			{
				displayName: 'Name',
				name: 'updName',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'name' } },
			},
			{
				displayName: 'Normalize Whitespace',
				name: 'updNormalizeWhitespace',
				type: 'boolean',
				default: false,
				description: 'Whether to normalize whitespace before comparing or analyzing text',
				routing: { send: { type: 'body', property: 'target.normalize_whitespace' } },
			},
			{
				displayName: 'Schedule Frequency',
				name: 'updScheduleFrequency',
				type: 'number',
				default: 6,
				typeOptions: { minValue: 1 },
				routing: { send: { type: 'body', property: 'schedule.frequency' } },
			},
			{
				displayName: 'Schedule Unit',
				name: 'updScheduleUnit',
				type: 'options',
				default: 'hours',
				options: UNIT_OPTIONS,
				routing: { send: { type: 'body', property: 'schedule.unit' } },
			},
			{
				displayName: 'Status',
				name: 'updStatus',
				type: 'options',
				default: 'active',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Paused', value: 'paused' },
				],
				routing: { send: { type: 'body', property: 'status' } },
			},
			{
				displayName: 'Tags',
				name: 'updTags',
				type: 'string',
				default: '',
				placeholder: 'pricing,marketing',
				description: 'Comma-separated tags',
				routing: tagsRouting,
			},
			{
				displayName: 'Target URL',
				name: 'updTargetUrl',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'target.url' } },
			},
			{
				displayName: 'Webhook URL',
				name: 'updWebhookUrl',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'webhook.url' } },
			},
		],
	},
];

// ─── list / changes / runs: pagination + filters ─────────────────────────────────
const runStatusOptions = [
	{ name: 'Queued', value: 'queued' },
	{ name: 'Running', value: 'running' },
	{ name: 'Completed', value: 'completed' },
	{ name: 'Failed', value: 'failed' },
];

const listFilters: INodeProperties[] = [
	{
		displayName: 'Filters',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { ...show, operation: listOps } },
		options: [
			{
				displayName: 'Change Detection Type',
				name: 'change_detection_type',
				type: 'options',
				default: 'exact',
				displayOptions: { show: { '/operation': ['list', 'listAccountChanges'] } },
				options: [
					{ name: 'Exact', value: 'exact' },
					{ name: 'Semantic', value: 'semantic' },
				],
				routing: { request: { qs: { change_detection_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: '',
				description: 'Pagination cursor from a previous response',
				routing: { request: { qs: { cursor: '={{ $value }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: { minValue: 1 },
				description: 'Max number of results to return',
				routing: { request: { qs: { limit: '={{ $value }}' } } },
			},
			{
				displayName: 'Monitor ID',
				name: 'monitor_id',
				type: 'string',
				default: '',
				description: 'Filter account-wide changes to a single monitor',
				displayOptions: { show: { '/operation': ['listAccountChanges'] } },
				routing: { request: { qs: { monitor_id: '={{ $value }}' } } },
			},
			{
				displayName: 'Run Status',
				name: 'runStatus',
				type: 'options',
				default: 'completed',
				displayOptions: { show: { '/operation': ['listAccountRuns', 'listRuns'] } },
				options: runStatusOptions,
				routing: { request: { qs: { status: '={{ $value }}' } } },
			},
			{
				displayName: 'Since',
				name: 'since',
				type: 'string',
				default: '',
				placeholder: '2026-01-01T00:00:00Z',
				description: 'Only return changes at or after this ISO 8601 timestamp',
				displayOptions: { show: { '/operation': ['listAccountChanges', 'listChanges'] } },
				routing: { request: { qs: { since: '={{ $value }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'active',
				displayOptions: { show: { '/operation': ['list'] } },
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Paused', value: 'paused' },
					{ name: 'Failed', value: 'failed' },
				],
				routing: { request: { qs: { status: '={{ $value }}' } } },
			},
			{
				displayName: 'Tag',
				name: 'tag',
				type: 'string',
				default: '',
				description: 'Filter by a single tag',
				displayOptions: { show: { '/operation': ['list', 'listAccountChanges', 'listChanges'] } },
				routing: { request: { qs: { tag: '={{ $value }}' } } },
			},
			{
				displayName: 'Target Type',
				name: 'target_type',
				type: 'options',
				default: 'page',
				displayOptions: { show: { '/operation': ['list', 'listAccountChanges'] } },
				options: [
					{ name: 'Page', value: 'page' },
					{ name: 'Sitemap', value: 'sitemap' },
					{ name: 'Extract', value: 'extract' },
				],
				routing: { request: { qs: { target_type: '={{ $value }}' } } },
			},
			{
				displayName: 'Until',
				name: 'until',
				type: 'string',
				default: '',
				placeholder: '2026-02-01T00:00:00Z',
				description: 'Only return changes at or before this ISO 8601 timestamp',
				displayOptions: { show: { '/operation': ['listAccountChanges', 'listChanges'] } },
				routing: { request: { qs: { until: '={{ $value }}' } } },
			},
		],
	},
];

export const monitorsDescription: INodeProperties[] = [
	operationField,
	...pathParams,
	...createCore,
	...updateFields,
	...listFilters,
];
