import type { INodeProperties } from 'n8n-workflow';

export const brandIntelligenceDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['brandIntelligence'] } },
			options: [
			{ name: 'Brand Search', value: 'brandSearch', action: 'Brand search', description: 'Search indexed brands by name or domain', routing: { request: { method: 'GET', url: '/brand/search' } } },
			{ name: 'Identify Brand From Transaction Data', value: 'identifyBrandFromTransactionData', action: 'Identify brand from transaction data', description: 'Endpoint specially designed for platforms that want to identify transaction data by the transaction title', routing: { request: { method: 'GET', url: '/brand/transaction_identifier' } } },
			{ name: 'Retrieve Brand Data', value: 'retrieveBrandData', action: 'Retrieve brand data', description: 'Retrieve logos, backdrops, colors, industry, description, and more. Provide exactly one lookup identifier in the request body: a domain, company name, email address, stock ticker, transaction descriptor, or direct URL. Note: `by_direct_url` fetches brand data only from the provided URL — not from the entire internet', routing: { request: { method: 'POST', url: '/brand/retrieve' } } },
			{ name: 'Retrieve Brand Data by Company Name', value: 'retrieveBrandDataByCompanyName', action: 'Retrieve brand data by company name', description: 'Retrieve brand information using a company name', routing: { request: { method: 'GET', url: '/brand/retrieve-by-name' } } },
			{ name: 'Retrieve Brand Data by Domain', value: 'retrieveBrandDataByDomain', action: 'Retrieve brand data by domain', description: 'Retrieve logos, backdrops, colors, industry, description, and more from any domain', routing: { request: { method: 'GET', url: '/brand/retrieve' } } },
			{ name: 'Retrieve Brand Data by Email Address', value: 'retrieveBrandDataByEmailAddress', action: 'Retrieve brand data by email address', description: 'Retrieve brand information using an email address while detecting disposable and free email addresses. Disposable and free email addresses (like gmail.com, yahoo.com) will throw a 422 error.', routing: { request: { method: 'GET', url: '/brand/retrieve-by-email' } } },
			{ name: 'Retrieve Brand Data by ISIN', value: 'retrieveBrandDataByISIN', action: 'Retrieve brand data by ISIN', description: 'Retrieve brand information using an ISIN (International Securities Identification Number)', routing: { request: { method: 'GET', url: '/brand/retrieve-by-isin' } } },
			{ name: 'Retrieve Brand Data by Stock Ticker', value: 'retrieveBrandDataByStockTicker', action: 'Retrieve brand data by stock ticker', description: 'Retrieve brand information using a stock ticker symbol', routing: { request: { method: 'GET', url: '/brand/retrieve-by-ticker' } } },
			{ name: 'Retrieve Simplified Brand Data by Domain', value: 'retrieveSimplifiedBrandDataByDomain', action: 'Retrieve simplified brand data by domain', description: 'Returns a simplified version of brand data containing only essential information: domain, title, colors, logos, and backdrops. Optimized for faster responses and reduced data transfer.', routing: { request: { method: 'GET', url: '/brand/retrieve-simplified' } } },
			],
			default: 'retrieveBrandDataByDomain',
		},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByDomain'] } },
		options: [
			{
				displayName: 'Domain',
				name: 'domain',
				type: 'string',
				default: "",
				description: 'Domain name to retrieve brand data for (e.g., \'example.com\', \'google.com\'). Cannot be used with name or ticker parameters.',
				routing: { request: { qs: { "domain": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data. Works with all three lookup methods.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: "",
				description: 'Company name to retrieve brand data for (e.g., \'Apple Inc\'). Cannot be used with domain or ticker parameters.',
				routing: { request: { qs: { "name": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Ticker',
				name: 'ticker',
				type: 'string',
				default: "",
				description: 'Stock ticker symbol to retrieve brand data for (e.g., \'AAPL\'). Cannot be used with domain or name parameters.',
				routing: { request: { qs: { "ticker": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Ticker Exchange',
				name: 'tickerExchange',
				type: 'options',
				default: "AMEX",
				options: [{ name: 'AMEX', value: "AMEX" }, { name: 'AMS', value: "AMS" }, { name: 'AQS', value: "AQS" }, { name: 'ASX', value: "ASX" }, { name: 'ATH', value: "ATH" }, { name: 'BER', value: "BER" }, { name: 'BME', value: "BME" }, { name: 'BRU', value: "BRU" }, { name: 'BSE', value: "BSE" }, { name: 'BUD', value: "BUD" }, { name: 'BUE', value: "BUE" }, { name: 'BVC', value: "BVC" }, { name: 'CBOE', value: "CBOE" }, { name: 'CNQ', value: "CNQ" }, { name: 'CPH', value: "CPH" }, { name: 'DFM', value: "DFM" }, { name: 'DOH', value: "DOH" }, { name: 'DUB', value: "DUB" }, { name: 'DUS', value: "DUS" }, { name: 'DXE', value: "DXE" }, { name: 'EGX', value: "EGX" }, { name: 'FSX', value: "FSX" }, { name: 'HAM', value: "HAM" }, { name: 'HEL', value: "HEL" }, { name: 'HKSE', value: "HKSE" }, { name: 'HOSE', value: "HOSE" }, { name: 'ICE', value: "ICE" }, { name: 'IOB', value: "IOB" }, { name: 'IST', value: "IST" }, { name: 'JKT', value: "JKT" }, { name: 'JNB', value: "JNB" }, { name: 'JPX', value: "JPX" }, { name: 'KLS', value: "KLS" }, { name: 'KOE', value: "KOE" }, { name: 'KSC', value: "KSC" }, { name: 'KUW', value: "KUW" }, { name: 'LIS', value: "LIS" }, { name: 'LSE', value: "LSE" }, { name: 'MCX', value: "MCX" }, { name: 'MEX', value: "MEX" }, { name: 'MIL', value: "MIL" }, { name: 'MUN', value: "MUN" }, { name: 'NASDAQ', value: "NASDAQ" }, { name: 'NEO', value: "NEO" }, { name: 'NSE', value: "NSE" }, { name: 'NYSE', value: "NYSE" }, { name: 'NZE', value: "NZE" }, { name: 'OSL', value: "OSL" }, { name: 'OTC', value: "OTC" }, { name: 'PAR', value: "PAR" }, { name: 'PNK', value: "PNK" }, { name: 'PRA', value: "PRA" }, { name: 'RIS', value: "RIS" }, { name: 'SAO', value: "SAO" }, { name: 'SAU', value: "SAU" }, { name: 'SES', value: "SES" }, { name: 'SET', value: "SET" }, { name: 'SGO', value: "SGO" }, { name: 'SHH', value: "SHH" }, { name: 'SHZ', value: "SHZ" }, { name: 'SIX', value: "SIX" }, { name: 'STO', value: "STO" }, { name: 'STU', value: "STU" }, { name: 'TAI', value: "TAI" }, { name: 'TAL', value: "TAL" }, { name: 'TLV', value: "TLV" }, { name: 'TSX', value: "TSX" }, { name: 'TSXV', value: "TSXV" }, { name: 'TWO', value: "TWO" }, { name: 'VIE', value: "VIE" }, { name: 'WSE', value: "WSE" }, { name: 'XETRA', value: "XETRA" }],
				description: 'Stock exchange code',
				routing: { request: { qs: { "ticker_exchange": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Type',
		name: 'type',
		type: 'options',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "by_domain",
		options: [{ name: 'By Direct URL', value: "by_direct_url" }, { name: 'By Domain', value: "by_domain" }, { name: 'By Email', value: "by_email" }, { name: 'By Name', value: "by_name" }, { name: 'By Ticker', value: "by_ticker" }, { name: 'By Transaction', value: "by_transaction" }],
		description: 'Discriminator for domain-based brand retrieval',
		routing: { send: { property: 'type', type: 'body' } },
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Domain name to retrieve brand data for (e.g., \'stripe.com\')',
		routing: { send: { property: 'domain', type: 'body' } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Company name to retrieve brand data for (e.g., \'Apple Inc\')',
		routing: { send: { property: 'name', type: 'body' } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Email address to retrieve brand data for (e.g., \'jane@stripe.com\')',
		routing: { send: { property: 'email', type: 'body' } },
	},
	{
		displayName: 'Ticker',
		name: 'ticker',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Stock ticker symbol to retrieve brand data for (e.g., \'AAPL\')',
		routing: { send: { property: 'ticker', type: 'body' } },
	},
	{
		displayName: 'Direct URL',
		name: 'directUrl',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Full http(s) URL to fetch brand data from (e.g., \'https://stripe.com/enterprise\'). Only this URL is fetched — not the entire internet.',
		routing: { send: { property: 'direct_url', type: 'body' } },
	},
	{
		displayName: 'Transaction Info',
		name: 'transactionInfo',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		required: true,
		default: "",
		description: 'Transaction information to identify the brand',
		routing: { send: { property: 'transaction_info', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandData'] } },
		options: [
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: "",
				description: 'Optional city name to prioritize when searching for the brand',
				routing: { send: { property: 'city', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Country Gl',
				name: 'countryGl',
				type: 'string',
				default: "",
				description: 'Optional country code hint (GL parameter) to specify the country when looking up by company name',
				routing: { send: { property: 'country_gl', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { send: { property: 'force_language', type: 'body' } },
			},
			{
				displayName: 'High Confidence Only',
				name: 'highConfidenceOnly',
				type: 'boolean',
				default: false,
				description: 'Whether set to true, the API performs additional verification to ensure the identified brand matches the transaction with high confidence',
				routing: { send: { property: 'high_confidence_only', type: 'body' } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'number',
				default: 0,
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { send: { property: 'maxAgeMs', type: 'body' } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { send: { property: 'maxSpeed', type: 'body' } },
			},
			{
				displayName: 'Mcc',
				name: 'mcc',
				type: 'number',
				default: 0,
				routing: { send: { property: 'mcc', type: 'body' } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'number',
				default: 0,
				routing: { send: { property: 'phone', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Ticker Exchange',
				name: 'tickerExchange',
				type: 'string',
				default: "",
				description: 'Optional stock exchange for the ticker. Defaults to NASDAQ if not specified.',
				routing: { send: { property: 'ticker_exchange', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { send: { property: 'timeoutMS', type: 'body' } },
			},
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByCompanyName'] } },
		required: true,
		default: "",
		description: 'Company name to retrieve brand data for (e.g., \'Apple Inc\', \'Microsoft Corporation\'). Must be 3-30 characters.',
		routing: { request: { qs: { "name": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByCompanyName'] } },
		options: [
			{
				displayName: 'Country Gl',
				name: 'countryGl',
				type: 'options',
				default: "af",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'An', value: "an" }, { name: 'Ao', value: "ao" }, { name: 'Aq', value: "aq" }, { name: 'Ar', value: "ar" }, { name: 'As', value: "as" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bt', value: "bt" }, { name: 'Bv', value: "bv" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cc', value: "cc" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Ck', value: "ck" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cu', value: "cu" }, { name: 'Cv', value: "cv" }, { name: 'Cx', value: "cx" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Eh', value: "eh" }, { name: 'Er', value: "er" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fk', value: "fk" }, { name: 'Fm', value: "fm" }, { name: 'Fo', value: "fo" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gh', value: "gh" }, { name: 'Gi', value: "gi" }, { name: 'Gl', value: "gl" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gs', value: "gs" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hm', value: "hm" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'In', value: "in" }, { name: 'Io', value: "io" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Ki', value: "ki" }, { name: 'Km', value: "km" }, { name: 'Kn', value: "kn" }, { name: 'Kp', value: "kp" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Li', value: "li" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Mg', value: "mg" }, { name: 'Mh', value: "mh" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mp', value: "mp" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'MS', value: "ms" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Nf', value: "nf" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nr', value: "nr" }, { name: 'Nu', value: "nu" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pm', value: "pm" }, { name: 'Pn', value: "pn" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Pw', value: "pw" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sb', value: "sb" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Sh', value: "sh" }, { name: 'Si', value: "si" }, { name: 'Sj', value: "sj" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tf', value: "tf" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tk', value: "tk" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'To', value: "to" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tv', value: "tv" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Um', value: "um" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Va', value: "va" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Vu', value: "vu" }, { name: 'Wf', value: "wf" }, { name: 'Ws', value: "ws" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Two-letter ISO 3166-1 alpha-2 country code (GL parameter) used to localize search',
				routing: { request: { qs: { "country_gl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['brandSearch'] } },
		required: true,
		default: "",
		description: 'Search term, matched against the fields selected by queryBy (e.g. \'nike\', \'nike.com\', \'nik\')',
		routing: { request: { qs: { "query": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['brandSearch'] } },
		options: [
			{
				displayName: 'Autocomplete',
				name: 'autocomplete',
				type: 'boolean',
				default: true,
				description: 'Whether the search term matches by prefix, so partial words match as they are typed (e.g. \'nik\' matches Nike). Set to false to match whole words only.',
				routing: { request: { qs: { "autocomplete": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Query By',
				name: 'queryBy',
				type: 'string',
				default: '',
				description: 'Fields to match the search term against, as a comma-separated list or repeated parameter: \'name\', \'domain\', or both. Defaults to both.',
				routing: { request: { qs: { "queryBy": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Typo Tolerance',
				name: 'typoTolerance',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":2},
				description: 'Maximum number of typos tolerated when matching, from 0 to 2. Defaults to 0 (no typo tolerance).',
				routing: { request: { qs: { "typoTolerance": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@email.com',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByEmailAddress'] } },
		required: true,
		default: "",
		description: 'Email address to retrieve brand data for (e.g., \'contact@example.com\'). The domain will be extracted from the email. Free email providers (gmail.com, yahoo.com, etc.) and disposable email addresses are not allowed.',
		routing: { request: { qs: { "email": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByEmailAddress'] } },
		options: [
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Ticker',
		name: 'ticker',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByStockTicker'] } },
		required: true,
		default: "",
		description: 'Stock ticker symbol to retrieve brand data for (e.g., \'AAPL\', \'GOOGL\', \'BRK.A\'). Must be 1-15 characters, letters/numbers/dots only.',
		routing: { request: { qs: { "ticker": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByStockTicker'] } },
		options: [
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Ticker Exchange',
				name: 'tickerExchange',
				type: 'options',
				default: "AMEX",
				options: [{ name: 'AMEX', value: "AMEX" }, { name: 'AMS', value: "AMS" }, { name: 'AQS', value: "AQS" }, { name: 'ASX', value: "ASX" }, { name: 'ATH', value: "ATH" }, { name: 'BER', value: "BER" }, { name: 'BME', value: "BME" }, { name: 'BRU', value: "BRU" }, { name: 'BSE', value: "BSE" }, { name: 'BUD', value: "BUD" }, { name: 'BUE', value: "BUE" }, { name: 'BVC', value: "BVC" }, { name: 'CBOE', value: "CBOE" }, { name: 'CNQ', value: "CNQ" }, { name: 'CPH', value: "CPH" }, { name: 'DFM', value: "DFM" }, { name: 'DOH', value: "DOH" }, { name: 'DUB', value: "DUB" }, { name: 'DUS', value: "DUS" }, { name: 'DXE', value: "DXE" }, { name: 'EGX', value: "EGX" }, { name: 'FSX', value: "FSX" }, { name: 'HAM', value: "HAM" }, { name: 'HEL', value: "HEL" }, { name: 'HKSE', value: "HKSE" }, { name: 'HOSE', value: "HOSE" }, { name: 'ICE', value: "ICE" }, { name: 'IOB', value: "IOB" }, { name: 'IST', value: "IST" }, { name: 'JKT', value: "JKT" }, { name: 'JNB', value: "JNB" }, { name: 'JPX', value: "JPX" }, { name: 'KLS', value: "KLS" }, { name: 'KOE', value: "KOE" }, { name: 'KSC', value: "KSC" }, { name: 'KUW', value: "KUW" }, { name: 'LIS', value: "LIS" }, { name: 'LSE', value: "LSE" }, { name: 'MCX', value: "MCX" }, { name: 'MEX', value: "MEX" }, { name: 'MIL', value: "MIL" }, { name: 'MUN', value: "MUN" }, { name: 'NASDAQ', value: "NASDAQ" }, { name: 'NEO', value: "NEO" }, { name: 'NSE', value: "NSE" }, { name: 'NYSE', value: "NYSE" }, { name: 'NZE', value: "NZE" }, { name: 'OSL', value: "OSL" }, { name: 'OTC', value: "OTC" }, { name: 'PAR', value: "PAR" }, { name: 'PNK', value: "PNK" }, { name: 'PRA', value: "PRA" }, { name: 'RIS', value: "RIS" }, { name: 'SAO', value: "SAO" }, { name: 'SAU', value: "SAU" }, { name: 'SES', value: "SES" }, { name: 'SET', value: "SET" }, { name: 'SGO', value: "SGO" }, { name: 'SHH', value: "SHH" }, { name: 'SHZ', value: "SHZ" }, { name: 'SIX', value: "SIX" }, { name: 'STO', value: "STO" }, { name: 'STU', value: "STU" }, { name: 'TAI', value: "TAI" }, { name: 'TAL', value: "TAL" }, { name: 'TLV', value: "TLV" }, { name: 'TSX', value: "TSX" }, { name: 'TSXV', value: "TSXV" }, { name: 'TWO', value: "TWO" }, { name: 'VIE', value: "VIE" }, { name: 'WSE', value: "WSE" }, { name: 'XETRA', value: "XETRA" }],
				description: 'Stock exchange code',
				routing: { request: { qs: { "ticker_exchange": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'ISIN',
		name: 'isin',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByISIN'] } },
		required: true,
		default: "",
		description: 'ISIN (International Securities Identification Number) to retrieve brand data for (e.g., \'AU000000IMD5\', \'US0378331005\'). Must be exactly 12 characters: 2 letters followed by 9 alphanumeric characters and ending with a digit.',
		routing: { request: { qs: { "isin": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveBrandDataByISIN'] } },
		options: [
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Transaction Info',
		name: 'transactionInfo',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['identifyBrandFromTransactionData'] } },
		required: true,
		default: "",
		description: 'Transaction information to identify the brand',
		routing: { request: { qs: { "transaction_info": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['identifyBrandFromTransactionData'] } },
		options: [
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: "",
				description: 'Optional city name to prioritize when searching for the brand',
				routing: { request: { qs: { "city": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Country Gl',
				name: 'countryGl',
				type: 'options',
				default: "af",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'An', value: "an" }, { name: 'Ao', value: "ao" }, { name: 'Aq', value: "aq" }, { name: 'Ar', value: "ar" }, { name: 'As', value: "as" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bt', value: "bt" }, { name: 'Bv', value: "bv" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cc', value: "cc" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Ck', value: "ck" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cu', value: "cu" }, { name: 'Cv', value: "cv" }, { name: 'Cx', value: "cx" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Eh', value: "eh" }, { name: 'Er', value: "er" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fk', value: "fk" }, { name: 'Fm', value: "fm" }, { name: 'Fo', value: "fo" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gh', value: "gh" }, { name: 'Gi', value: "gi" }, { name: 'Gl', value: "gl" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gs', value: "gs" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hm', value: "hm" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'In', value: "in" }, { name: 'Io', value: "io" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Ki', value: "ki" }, { name: 'Km', value: "km" }, { name: 'Kn', value: "kn" }, { name: 'Kp', value: "kp" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Li', value: "li" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Mg', value: "mg" }, { name: 'Mh', value: "mh" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mp', value: "mp" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'MS', value: "ms" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Nf', value: "nf" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nr', value: "nr" }, { name: 'Nu', value: "nu" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pm', value: "pm" }, { name: 'Pn', value: "pn" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Pw', value: "pw" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sb', value: "sb" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Sh', value: "sh" }, { name: 'Si', value: "si" }, { name: 'Sj', value: "sj" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tf', value: "tf" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tk', value: "tk" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'To', value: "to" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tv', value: "tv" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Um', value: "um" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Va', value: "va" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Vu', value: "vu" }, { name: 'Wf', value: "wf" }, { name: 'Ws', value: "ws" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Two-letter ISO 3166-1 alpha-2 country code (GL parameter) used to localize search',
				routing: { request: { qs: { "country_gl": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Force Language',
				name: 'forceLanguage',
				type: 'options',
				default: "afrikaans",
				options: [{ name: 'Afrikaans', value: "afrikaans" }, { name: 'Albanian', value: "albanian" }, { name: 'Amharic', value: "amharic" }, { name: 'Arabic', value: "arabic" }, { name: 'Armenian', value: "armenian" }, { name: 'Assamese', value: "assamese" }, { name: 'Aymara', value: "aymara" }, { name: 'Azeri', value: "azeri" }, { name: 'Basque', value: "basque" }, { name: 'Belarusian', value: "belarusian" }, { name: 'Bengali', value: "bengali" }, { name: 'Bosnian', value: "bosnian" }, { name: 'Bulgarian', value: "bulgarian" }, { name: 'Burmese', value: "burmese" }, { name: 'Cantonese', value: "cantonese" }, { name: 'Catalan', value: "catalan" }, { name: 'Cebuano', value: "cebuano" }, { name: 'Chinese', value: "chinese" }, { name: 'Corsican', value: "corsican" }, { name: 'Croatian', value: "croatian" }, { name: 'Czech', value: "czech" }, { name: 'Danish', value: "danish" }, { name: 'Dutch', value: "dutch" }, { name: 'English', value: "english" }, { name: 'Esperanto', value: "esperanto" }, { name: 'Estonian', value: "estonian" }, { name: 'Farsi', value: "farsi" }, { name: 'Fijian', value: "fijian" }, { name: 'Finnish', value: "finnish" }, { name: 'French', value: "french" }, { name: 'Galician', value: "galician" }, { name: 'Georgian', value: "georgian" }, { name: 'German', value: "german" }, { name: 'Greek', value: "greek" }, { name: 'Guarani', value: "guarani" }, { name: 'Gujarati', value: "gujarati" }, { name: 'Haitian Creole', value: "haitian-creole" }, { name: 'Hausa', value: "hausa" }, { name: 'Hawaiian', value: "hawaiian" }, { name: 'Hebrew', value: "hebrew" }, { name: 'Hindi', value: "hindi" }, { name: 'Hmong', value: "hmong" }, { name: 'Hungarian', value: "hungarian" }, { name: 'Icelandic', value: "icelandic" }, { name: 'Igbo', value: "igbo" }, { name: 'Indonesian', value: "indonesian" }, { name: 'Irish', value: "irish" }, { name: 'Italian', value: "italian" }, { name: 'Japanese', value: "japanese" }, { name: 'Javanese', value: "javanese" }, { name: 'Kannada', value: "kannada" }, { name: 'Kazakh', value: "kazakh" }, { name: 'Khmer', value: "khmer" }, { name: 'Kinyarwanda', value: "kinyarwanda" }, { name: 'Korean', value: "korean" }, { name: 'Kurdish', value: "kurdish" }, { name: 'Kyrgyz', value: "kyrgyz" }, { name: 'Lao', value: "lao" }, { name: 'Latin', value: "latin" }, { name: 'Latvian', value: "latvian" }, { name: 'Lingala', value: "lingala" }, { name: 'Lithuanian', value: "lithuanian" }, { name: 'Luxembourgish', value: "luxembourgish" }, { name: 'Macedonian', value: "macedonian" }, { name: 'Malagasy', value: "malagasy" }, { name: 'Malay', value: "malay" }, { name: 'Malayalam', value: "malayalam" }, { name: 'Maltese', value: "maltese" }, { name: 'Maori', value: "maori" }, { name: 'Marathi', value: "marathi" }, { name: 'Mongolian', value: "mongolian" }, { name: 'Nepali', value: "nepali" }, { name: 'Norwegian', value: "norwegian" }, { name: 'Odia', value: "odia" }, { name: 'Oromo', value: "oromo" }, { name: 'Pashto', value: "pashto" }, { name: 'Pidgin', value: "pidgin" }, { name: 'Polish', value: "polish" }, { name: 'Portuguese', value: "portuguese" }, { name: 'Punjabi', value: "punjabi" }, { name: 'Quechua', value: "quechua" }, { name: 'Romanian', value: "romanian" }, { name: 'Russian', value: "russian" }, { name: 'Samoan', value: "samoan" }, { name: 'Scottish Gaelic', value: "scottish-gaelic" }, { name: 'Serbian', value: "serbian" }, { name: 'Sesotho', value: "sesotho" }, { name: 'Shona', value: "shona" }, { name: 'Sindhi', value: "sindhi" }, { name: 'Sinhala', value: "sinhala" }, { name: 'Slovak', value: "slovak" }, { name: 'Slovene', value: "slovene" }, { name: 'Somali', value: "somali" }, { name: 'Spanish', value: "spanish" }, { name: 'Sundanese', value: "sundanese" }, { name: 'Swahili', value: "swahili" }, { name: 'Swedish', value: "swedish" }, { name: 'Tagalog', value: "tagalog" }, { name: 'Tajik', value: "tajik" }, { name: 'Tamil', value: "tamil" }, { name: 'Tatar', value: "tatar" }, { name: 'Telugu', value: "telugu" }, { name: 'Thai', value: "thai" }, { name: 'Tibetan', value: "tibetan" }, { name: 'Tigrinya', value: "tigrinya" }, { name: 'Tongan', value: "tongan" }, { name: 'Tswana', value: "tswana" }, { name: 'Turkish', value: "turkish" }, { name: 'Turkmen', value: "turkmen" }, { name: 'Ukrainian', value: "ukrainian" }, { name: 'Urdu', value: "urdu" }, { name: 'Uyghur', value: "uyghur" }, { name: 'Uzbek', value: "uzbek" }, { name: 'Vietnamese', value: "vietnamese" }, { name: 'Welsh', value: "welsh" }, { name: 'Wolof', value: "wolof" }, { name: 'Xhosa', value: "xhosa" }, { name: 'Yiddish', value: "yiddish" }, { name: 'Yoruba', value: "yoruba" }, { name: 'Zulu', value: "zulu" }],
				description: 'Language to force for the retrieved brand data',
				routing: { request: { qs: { "force_language": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'High Confidence Only',
				name: 'highConfidenceOnly',
				type: 'boolean',
				default: false,
				description: 'Whether set to true, the API will perform an additional verification steps to ensure the identified brand matches the transaction with high confidence',
				routing: { request: { qs: { "high_confidence_only": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Max Speed',
				name: 'maxSpeed',
				type: 'boolean',
				default: false,
				description: 'Whether optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
				routing: { request: { qs: { "maxSpeed": '={{ $value ? "true" : "false" }}' } } },
			},
			{
				displayName: 'Mcc',
				name: 'mcc',
				type: 'number',
				default: 0,
				routing: { request: { qs: { "mcc": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Phone',
				name: 'phone',
				type: 'number',
				default: 0,
				routing: { request: { qs: { "phone": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Domain',
		name: 'domain',
		type: 'string',
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveSimplifiedBrandDataByDomain'] } },
		required: true,
		default: "",
		description: 'Domain name to retrieve simplified brand data for',
		routing: { request: { qs: { "domain": '={{ $value }}' } } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['brandIntelligence'], operation: ['retrieveSimplifiedBrandDataByDomain'] } },
		options: [
			{
				displayName: 'Max Age MS',
				name: 'maxAgeMs',
				type: 'string',
				default: '',
				description: 'Maximum age in milliseconds for cached brand data before the API performs a hard refresh. Defaults to 3 months (7776000000 ms). Values below 1 day (86400000 ms) are clamped to 1 day; values above 1 year (31536000000 ms) are clamped to 1 year.',
				routing: { request: { qs: { "maxAgeMs": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Optional tags for tracking usage. Up to 20 tags, each 1 to 50 characters.',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Theme',
				name: 'theme',
				type: 'options',
				default: "light",
				options: [{ name: 'Dark', value: "dark" }, { name: 'Light', value: "light" }],
				description: 'Optional theme preference used when selecting brand assets',
				routing: { request: { qs: { "theme": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Timeout MS',
				name: 'timeoutMS',
				type: 'number',
				default: 1000,
				typeOptions: {"minValue":1000,"maxValue":300000},
				description: 'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
				routing: { request: { qs: { "timeoutMS": '={{ $value || undefined }}' } } },
			},
		],
	},
];
