import type { INodeProperties } from 'n8n-workflow';

export const batchDescription: INodeProperties[] = [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: { show: { resource: ['batch'] } },
			options: [
			{ name: 'Cancel a Batch', value: 'cancelBatch', action: 'Cancel a batch', description: 'Stop a batch from starting new pages. In-progress pages finish, and unused credits are refunded.', routing: { request: { method: 'POST', url: '=/batch/{{ $parameter["batchId"] }}/cancel' } } },
			{ name: 'Delete a Batch', value: 'deleteBatch', action: 'Delete a batch', description: 'Permanently delete a finished batch and its stored results. Active batches must settle first.', routing: { request: { method: 'DELETE', url: '=/batch/{{ $parameter["batchId"] }}' } } },
			{ name: 'Get a Batch', value: 'getBatch', action: 'Get a batch', description: 'Check progress, and get download links once the batch finishes', routing: { request: { method: 'GET', url: '=/batch/{{ $parameter["batchId"] }}' } } },
			{ name: 'Get Batch Results', value: 'getBatchResults', action: 'Get batch results', description: 'Page through a finished batch\'s results as JSON instead of downloading the NDJSON files', routing: { request: { method: 'GET', url: '=/batch/{{ $parameter["batchId"] }}/results' } } },
			{ name: 'List Batches', value: 'listBatches', action: 'List batches', description: 'List your batches from newest to oldest. Filter by status or continue with a cursor.', routing: { request: { method: 'GET', url: '/batch/list' } } },
			{ name: 'Submit a Batch', value: 'submitBatch', action: 'Submit a batch', description: 'Scrape 25K URLs or crawl large websites asynchronously', routing: { request: { method: 'POST', url: '/batch/submit' } } },
			],
			default: 'submitBatch',
		},
	{
		displayName: 'Mode',
		name: 'inputMode',
		type: 'options',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "scrape",
		options: [{ name: 'Crawl', value: "crawl" }, { name: 'Scrape', value: "scrape" }],
		description: 'Scrape the pages in `data.URLs`',
		routing: { send: { property: 'input.mode', type: 'body' } },
	},
	{
		displayName: 'Format',
		name: 'inputDataFormat',
		type: 'options',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "markdown",
		options: [{ name: 'HTML', value: "html" }, { name: 'Markdown', value: "markdown" }],
		description: 'Return page content as Markdown',
		routing: { send: { property: 'input.data.format', type: 'body' } },
	},
	{
		displayName: 'URLs',
		name: 'inputDataUrls',
		type: 'string',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "",
		description: 'Pages to scrape. Maximum 25000.',
		routing: { send: { property: 'input.data.urls', type: 'body' } },
	},
	{
		displayName: 'Type',
		name: 'inputDataSourceType',
		type: 'options',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "start_url",
		options: [{ name: 'Sitemap', value: "sitemap" }, { name: 'Start URL', value: "start_url" }],
		description: 'Start from one page',
		routing: { send: { property: 'input.data.source.type', type: 'body' } },
	},
	{
		displayName: 'URL',
		name: 'inputDataSourceUrl',
		type: 'string',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "",
		description: 'Page where crawling begins. A URL without a scheme is read as https://.',
		routing: { send: { property: 'input.data.source.url', type: 'body' } },
	},
	{
		displayName: 'Domain',
		name: 'inputDataSourceDomain',
		type: 'string',
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		required: true,
		default: "",
		description: 'Domain whose sitemap lists the pages to scrape. A full URL is reduced to its domain.',
		routing: { send: { property: 'input.data.source.domain', type: 'body' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['batch'], operation: ['submitBatch'] } },
		options: [
			{
				displayName: 'Country',
				name: 'inputDataOptionsCountry',
				type: 'options',
				default: "ad",
				options: [{ name: 'Ad', value: "ad" }, { name: 'Ae', value: "ae" }, { name: 'Af', value: "af" }, { name: 'Ag', value: "ag" }, { name: 'AI', value: "ai" }, { name: 'Al', value: "al" }, { name: 'Am', value: "am" }, { name: 'Ao', value: "ao" }, { name: 'Ar', value: "ar" }, { name: 'At', value: "at" }, { name: 'Au', value: "au" }, { name: 'Aw', value: "aw" }, { name: 'Az', value: "az" }, { name: 'Ba', value: "ba" }, { name: 'Bb', value: "bb" }, { name: 'Bd', value: "bd" }, { name: 'Be', value: "be" }, { name: 'Bf', value: "bf" }, { name: 'Bg', value: "bg" }, { name: 'Bh', value: "bh" }, { name: 'Bi', value: "bi" }, { name: 'Bj', value: "bj" }, { name: 'Bm', value: "bm" }, { name: 'Bn', value: "bn" }, { name: 'Bo', value: "bo" }, { name: 'Bq', value: "bq" }, { name: 'Br', value: "br" }, { name: 'Bs', value: "bs" }, { name: 'Bw', value: "bw" }, { name: 'By', value: "by" }, { name: 'Bz', value: "bz" }, { name: 'Ca', value: "ca" }, { name: 'Cd', value: "cd" }, { name: 'Cf', value: "cf" }, { name: 'Cg', value: "cg" }, { name: 'Ch', value: "ch" }, { name: 'Ci', value: "ci" }, { name: 'Cl', value: "cl" }, { name: 'Cm', value: "cm" }, { name: 'Cn', value: "cn" }, { name: 'Co', value: "co" }, { name: 'Cr', value: "cr" }, { name: 'Cv', value: "cv" }, { name: 'Cw', value: "cw" }, { name: 'Cy', value: "cy" }, { name: 'Cz', value: "cz" }, { name: 'De', value: "de" }, { name: 'Dj', value: "dj" }, { name: 'Dk', value: "dk" }, { name: 'Dm', value: "dm" }, { name: 'Do', value: "do" }, { name: 'Dz', value: "dz" }, { name: 'Ec', value: "ec" }, { name: 'Ee', value: "ee" }, { name: 'Eg', value: "eg" }, { name: 'Es', value: "es" }, { name: 'Et', value: "et" }, { name: 'Fi', value: "fi" }, { name: 'Fj', value: "fj" }, { name: 'Fr', value: "fr" }, { name: 'Ga', value: "ga" }, { name: 'Gb', value: "gb" }, { name: 'Gd', value: "gd" }, { name: 'Ge', value: "ge" }, { name: 'Gf', value: "gf" }, { name: 'Gg', value: "gg" }, { name: 'Gh', value: "gh" }, { name: 'Gm', value: "gm" }, { name: 'Gn', value: "gn" }, { name: 'Gp', value: "gp" }, { name: 'Gq', value: "gq" }, { name: 'Gr', value: "gr" }, { name: 'Gt', value: "gt" }, { name: 'Gu', value: "gu" }, { name: 'Gw', value: "gw" }, { name: 'Gy', value: "gy" }, { name: 'Hk', value: "hk" }, { name: 'Hn', value: "hn" }, { name: 'Hr', value: "hr" }, { name: 'Ht', value: "ht" }, { name: 'Hu', value: "hu" }, { name: 'ID', value: "id" }, { name: 'Ie', value: "ie" }, { name: 'Il', value: "il" }, { name: 'Im', value: "im" }, { name: 'In', value: "in" }, { name: 'Iq', value: "iq" }, { name: 'Ir', value: "ir" }, { name: 'Is', value: "is" }, { name: 'It', value: "it" }, { name: 'Je', value: "je" }, { name: 'Jm', value: "jm" }, { name: 'Jo', value: "jo" }, { name: 'Jp', value: "jp" }, { name: 'Ke', value: "ke" }, { name: 'Kg', value: "kg" }, { name: 'Kh', value: "kh" }, { name: 'Kn', value: "kn" }, { name: 'Kr', value: "kr" }, { name: 'Kw', value: "kw" }, { name: 'Ky', value: "ky" }, { name: 'Kz', value: "kz" }, { name: 'La', value: "la" }, { name: 'Lb', value: "lb" }, { name: 'Lc', value: "lc" }, { name: 'Lk', value: "lk" }, { name: 'Lr', value: "lr" }, { name: 'Ls', value: "ls" }, { name: 'Lt', value: "lt" }, { name: 'Lu', value: "lu" }, { name: 'Lv', value: "lv" }, { name: 'Ly', value: "ly" }, { name: 'Ma', value: "ma" }, { name: 'Mc', value: "mc" }, { name: 'Md', value: "md" }, { name: 'Me', value: "me" }, { name: 'Mf', value: "mf" }, { name: 'Mg', value: "mg" }, { name: 'Mk', value: "mk" }, { name: 'Ml', value: "ml" }, { name: 'Mm', value: "mm" }, { name: 'Mn', value: "mn" }, { name: 'Mo', value: "mo" }, { name: 'Mq', value: "mq" }, { name: 'Mr', value: "mr" }, { name: 'Mt', value: "mt" }, { name: 'Mu', value: "mu" }, { name: 'Mv', value: "mv" }, { name: 'Mw', value: "mw" }, { name: 'Mx', value: "mx" }, { name: 'My', value: "my" }, { name: 'Mz', value: "mz" }, { name: 'Na', value: "na" }, { name: 'Nc', value: "nc" }, { name: 'Ne', value: "ne" }, { name: 'Ng', value: "ng" }, { name: 'Ni', value: "ni" }, { name: 'Nl', value: "nl" }, { name: 'No', value: "no" }, { name: 'Np', value: "np" }, { name: 'Nz', value: "nz" }, { name: 'Om', value: "om" }, { name: 'Pa', value: "pa" }, { name: 'Pe', value: "pe" }, { name: 'Pf', value: "pf" }, { name: 'Pg', value: "pg" }, { name: 'Ph', value: "ph" }, { name: 'Pk', value: "pk" }, { name: 'Pl', value: "pl" }, { name: 'Pr', value: "pr" }, { name: 'Ps', value: "ps" }, { name: 'Pt', value: "pt" }, { name: 'Py', value: "py" }, { name: 'Qa', value: "qa" }, { name: 'Re', value: "re" }, { name: 'Ro', value: "ro" }, { name: 'Rs', value: "rs" }, { name: 'Ru', value: "ru" }, { name: 'Rw', value: "rw" }, { name: 'Sa', value: "sa" }, { name: 'Sc', value: "sc" }, { name: 'Sd', value: "sd" }, { name: 'Se', value: "se" }, { name: 'Sg', value: "sg" }, { name: 'Si', value: "si" }, { name: 'Sk', value: "sk" }, { name: 'Sl', value: "sl" }, { name: 'Sm', value: "sm" }, { name: 'Sn', value: "sn" }, { name: 'So', value: "so" }, { name: 'Sr', value: "sr" }, { name: 'Ss', value: "ss" }, { name: 'St', value: "st" }, { name: 'Sv', value: "sv" }, { name: 'Sx', value: "sx" }, { name: 'Sy', value: "sy" }, { name: 'Sz', value: "sz" }, { name: 'Tc', value: "tc" }, { name: 'Td', value: "td" }, { name: 'Tg', value: "tg" }, { name: 'Th', value: "th" }, { name: 'Tj', value: "tj" }, { name: 'Tl', value: "tl" }, { name: 'Tm', value: "tm" }, { name: 'Tn', value: "tn" }, { name: 'Tr', value: "tr" }, { name: 'Tt', value: "tt" }, { name: 'Tw', value: "tw" }, { name: 'Tz', value: "tz" }, { name: 'Ua', value: "ua" }, { name: 'Ug', value: "ug" }, { name: 'Us', value: "us" }, { name: 'Uy', value: "uy" }, { name: 'Uz', value: "uz" }, { name: 'Vc', value: "vc" }, { name: 'Ve', value: "ve" }, { name: 'Vg', value: "vg" }, { name: 'Vi', value: "vi" }, { name: 'Vn', value: "vn" }, { name: 'Ye', value: "ye" }, { name: 'Yt', value: "yt" }, { name: 'Za', value: "za" }, { name: 'Zm', value: "zm" }, { name: 'Zw', value: "zw" }],
				description: 'Fetch the target page through a residential proxy in this country (ISO 3166-1 alpha-2)',
				routing: { send: { property: 'input.data.options.country', type: 'body' } },
			},
			{
				displayName: 'End',
				name: 'inputDataOptionsPdfEnd',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'Last 1-based PDF page to parse. When omitted, parsing ends at the last page. Must be greater than or equal to start when both are provided.',
				routing: { send: { property: 'input.data.options.pdf.end', type: 'body' } },
			},
			{
				displayName: 'Exclude Selectors',
				name: 'inputDataOptionsExcludeSelectors',
				type: 'string',
				default: "",
				description: 'Remove elements matching these CSS selectors. Applied after `includeSelectors`, so an element matching both is removed.',
				routing: { send: { property: 'input.data.options.excludeSelectors', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Follow Subdomains',
				name: 'inputDataSourceControlsFollowSubdomains',
				type: 'boolean',
				default: false,
				description: 'Whether follow links to subdomains',
				routing: { send: { property: 'input.data.source.controls.followSubdomains', type: 'body' } },
			},
			{
				displayName: 'Include HTML',
				name: 'inputDataOptionsIncludeHTML',
				type: 'boolean',
				default: false,
				description: 'Whether also include each page\'s HTML in its result record, as an `HTML` field alongside the Markdown',
				routing: { send: { property: 'input.data.options.includeHTML', type: 'body' } },
			},
			{
				displayName: 'Include Images',
				name: 'inputDataOptionsIncludeImages',
				type: 'boolean',
				default: false,
				description: 'Whether include image references in the Markdown',
				routing: { send: { property: 'input.data.options.includeImages', type: 'body' } },
			},
			{
				displayName: 'Include Links',
				name: 'inputDataOptionsIncludeLinks',
				type: 'boolean',
				default: true,
				description: 'Whether include links in the Markdown',
				routing: { send: { property: 'input.data.options.includeLinks', type: 'body' } },
			},
			{
				displayName: 'Include Selectors',
				name: 'inputDataOptionsIncludeSelectors',
				type: 'string',
				default: "",
				description: 'Keep only the subtrees matching these CSS selectors. Filtered pages are always fetched fresh, ignoring `maxAgeMs`.',
				routing: { send: { property: 'input.data.options.includeSelectors', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Age MS',
				name: 'inputDataOptionsMaxAgeMs',
				type: 'string',
				default: '',
				typeOptions: {"minValue":0,"maxValue":2592000000},
				description: 'Return a cached result if a prior scrape for the same parameters exists and is younger than this many milliseconds. Defaults to 1 day (86400000 ms) when omitted. Max is 30 days (2592000000 ms). Set to 0 to always scrape fresh.',
				routing: { send: { property: 'input.data.options.maxAgeMs', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Max Depth',
				name: 'inputDataSourceControlsMaxDepth',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":50},
				description: 'Maximum link depth. Source pages are depth 0. No limit when omitted.',
				routing: { send: { property: 'input.data.source.controls.maxDepth', type: 'body' } },
			},
			{
				displayName: 'Max URLs',
				name: 'inputDataSourceControlsMaxUrls',
				type: 'number',
				default: 100,
				typeOptions: {"minValue":1,"maxValue":25000},
				description: 'Maximum pages to fetch. Unused reserved credits are refunded. Maximum 25000.',
				routing: { send: { property: 'input.data.source.controls.maxUrls', type: 'body' } },
			},
			{
				displayName: 'OCR',
				name: 'inputDataOptionsPdfOcr',
				type: 'boolean',
				default: false,
				description: 'Whether true, OCR the selected PDF pages that have no usable text layer (scans), replacing each recovered page\'s text with the OCR result while pages with a real text layer keep it. Billed at 1 credit per page OCR actually recovered, on top of the base request cost. When false, no OCR runs.',
				routing: { send: { property: 'input.data.options.pdf.ocr', type: 'body' } },
			},
			{
				displayName: 'Regex',
				name: 'inputDataSourceControlsRegex',
				type: 'string',
				default: "",
				description: 'RE2 pattern for URLs to include. The `start_url` itself is always included.',
				routing: { send: { property: 'input.data.source.controls.regex', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Settle Animations',
				name: 'inputDataOptionsSettleAnimations',
				type: 'boolean',
				default: false,
				description: 'Whether wait briefly for CSS and transition animations to settle before extraction, on pages that render in a browser',
				routing: { send: { property: 'input.data.options.settleAnimations', type: 'body' } },
			},
			{
				displayName: 'Shorten Base64 Images',
				name: 'inputDataOptionsShortenBase64Images',
				type: 'boolean',
				default: true,
				description: 'Whether shorten inline base64 image data',
				routing: { send: { property: 'input.data.options.shortenBase64Images', type: 'body' } },
			},
			{
				displayName: 'Should Parse',
				name: 'inputDataOptionsPdfShouldParse',
				type: 'boolean',
				default: true,
				description: 'Whether true, PDF URLs are fetched and parsed. When false, PDF URLs are skipped and a 400 PDF_SKIPPED is returned.',
				routing: { send: { property: 'input.data.options.pdf.shouldParse', type: 'body' } },
			},
			{
				displayName: 'Start',
				name: 'inputDataOptionsPdfStart',
				type: 'number',
				default: 1,
				typeOptions: {"minValue":1},
				description: 'First 1-based PDF page to parse. When omitted, parsing starts at the first page.',
				routing: { send: { property: 'input.data.options.pdf.start', type: 'body' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Tags stored on the batch. Filter the batch list by them later.',
				routing: { send: { property: 'tags', type: 'body', value: '={{ $value || undefined }}' } },
			},
			{
				displayName: 'Use Main Content Only',
				name: 'inputDataOptionsUseMainContentOnly',
				type: 'boolean',
				default: false,
				description: 'Whether return the main content without navigation or footers',
				routing: { send: { property: 'input.data.options.useMainContentOnly', type: 'body' } },
			},
			{
				displayName: 'Wait for MS',
				name: 'inputDataOptionsWaitForMs',
				type: 'number',
				default: 0,
				typeOptions: {"minValue":0,"maxValue":15000},
				description: 'How long to wait after initial page load, in milliseconds. `0` waits 500 ms.',
				routing: { send: { property: 'input.data.options.waitForMs', type: 'body' } },
			},
			{
				displayName: 'Webhook URL',
				name: 'webhookUrl',
				type: 'string',
				default: "",
				description: 'URL notified when the batch finishes',
				routing: { send: { property: 'webhookUrl', type: 'body', value: '={{ $value || undefined }}' } },
			},
		],
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['batch'], operation: ['listBatches'] } },
		options: [
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Cursor from the previous page',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Q',
				name: 'q',
				type: 'string',
				default: "",
				description: 'Free-text search term, matched against the batch ID, crawl source (start URL or sitemap domain), and tags',
				routing: { request: { qs: { "q": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Search Type',
				name: 'searchType',
				type: 'options',
				default: "exact",
				options: [{ name: 'Exact', value: "exact" }, { name: 'Prefix', value: "prefix" }],
				description: '`prefix` for as-you-type prefix matching (default), `exact` for full-token matching',
				routing: { request: { qs: { "search_type": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: "queued",
				options: [{ name: 'Cancelled', value: "cancelled" }, { name: 'Cancelling', value: "cancelling" }, { name: 'Completed', value: "completed" }, { name: 'Failed', value: "failed" }, { name: 'Queued', value: "queued" }, { name: 'Running', value: "running" }],
				description: 'Filter by status',
				routing: { request: { qs: { "status": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				default: "",
				description: 'Comma-separated list of tags to filter by (matches batches having any of them)',
				routing: { request: { qs: { "tags": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Batch ID',
		name: 'batchId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['batch'], operation: ['getBatch'] } },
		description: 'ID of the batch to retrieve or cancel',
	},
	{
		displayName: 'Batch ID',
		name: 'batchId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['batch'], operation: ['deleteBatch'] } },
		description: 'ID of the batch to retrieve or cancel',
	},
	{
		displayName: 'Batch ID',
		name: 'batchId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['batch'], operation: ['getBatchResults'] } },
		description: 'ID of the batch to retrieve or cancel',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['batch'], operation: ['getBatchResults'] } },
		options: [
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: "",
				description: 'Next_cursor from the previous page',
				routing: { request: { qs: { "cursor": '={{ $value || undefined }}' } } },
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: {"minValue":1,"maxValue":100},
				description: 'Max number of results to return',
				routing: { request: { qs: { "limit": '={{ $value || undefined }}' } } },
			},
		],
	},
	{
		displayName: 'Batch ID',
		name: 'batchId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['batch'], operation: ['cancelBatch'] } },
		description: 'ID of the batch to retrieve or cancel',
	},
];
