import type { IHttpRequestMethods } from 'n8n-workflow';

export const CONTEXT_API_BASE_URL = 'https://api.context.dev/v1';

export const contextResources = [
	{ name: 'Web Scraping', value: 'webScraping' },
	{ name: 'Web Extraction', value: 'webExtraction' },
	{ name: 'Brand Intelligence', value: 'brandIntelligence' },
	{ name: 'News', value: 'news' },
	{ name: 'Parsing', value: 'parsing' },
	{ name: 'People', value: 'people' },
	{ name: 'Monitors', value: 'monitors' },
	{ name: 'Batch', value: 'batch' },
	{ name: 'Webhooks', value: 'webhooks' },
	{ name: 'Utility', value: 'utility' },
] as const;

export type ContextResource = (typeof contextResources)[number]['value'];
export type ContextRequestKind = 'binary' | 'body' | 'none' | 'query';

export interface ContextOperationDefinition {
	resource: ContextResource;
	name: string;
	value: string;
	action: string;
	description: string;
	method: IHttpRequestMethods;
	path: string;
	requestKind: ContextRequestKind;
	example?: Record<string, unknown>;
	pathParameters?: string[];
	requiresConfirmation?: boolean;
	supportsIdempotencyKey?: boolean;
}

export const contextOperations: ContextOperationDefinition[] = [
	operation(
		'webScraping',
		'Scrape Markdown',
		'scrapeMarkdown',
		'Scrape a URL to Markdown',
		'GET',
		'/web/scrape/markdown',
		'query',
		{
			url: 'https://context.dev',
		},
	),
	operation(
		'webScraping',
		'Scrape HTML',
		'scrapeHtml',
		'Scrape a URL to rendered HTML',
		'GET',
		'/web/scrape/html',
		'query',
		{
			url: 'https://context.dev',
		},
	),
	operation(
		'webScraping',
		'Scrape Images',
		'scrapeImages',
		'Extract an image manifest from a URL',
		'GET',
		'/web/scrape/images',
		'query',
		{
			url: 'https://context.dev',
		},
	),
	operation(
		'webScraping',
		'Crawl Sitemap',
		'crawlSitemap',
		'Discover URLs from a site or sitemap',
		'GET',
		'/web/scrape/sitemap',
		'query',
		{
			domain: 'context.dev',
		},
	),
	operation(
		'webScraping',
		'Crawl Website',
		'crawlWebsite',
		'Crawl a website and scrape its pages',
		'POST',
		'/web/crawl',
		'body',
		{
			url: 'https://context.dev',
			maxPages: 25,
		},
	),
	operation(
		'webScraping',
		'Web Search',
		'webSearch',
		'Search the live web with optional inline Markdown',
		'POST',
		'/web/search',
		'body',
		{
			query: 'latest web scraping API news',
			numResults: 10,
		},
	),
	operation(
		'webScraping',
		'Take Screenshot',
		'takeScreenshot',
		'Capture a viewport or full-page screenshot',
		'GET',
		'/web/screenshot',
		'query',
		{
			directUrl: 'https://context.dev',
		},
	),

	operation(
		'webExtraction',
		'Extract Structured Data',
		'extractStructuredData',
		'Extract schema-shaped data from a website',
		'POST',
		'/web/extract',
		'body',
		{
			url: 'https://context.dev',
			schema: {
				type: 'object',
				properties: { title: { type: 'string' } },
				required: ['title'],
				additionalProperties: false,
			},
		},
	),
	operation(
		'webExtraction',
		'Extract Styleguide',
		'extractStyleguide',
		'Extract a website styleguide and design system',
		'GET',
		'/web/styleguide',
		'query',
		{
			domain: 'context.dev',
		},
	),
	operation(
		'webExtraction',
		'Extract Fonts',
		'extractFonts',
		'Extract fonts used by a website',
		'GET',
		'/web/fonts',
		'query',
		{
			domain: 'context.dev',
		},
	),
	operation(
		'webExtraction',
		'Classify NAICS',
		'classifyNaics',
		'Classify a company into NAICS industries',
		'GET',
		'/web/naics',
		'query',
		{
			input: 'context.dev',
		},
	),
	operation(
		'webExtraction',
		'Classify SIC',
		'classifySic',
		'Classify a company into SIC industries',
		'GET',
		'/web/sic',
		'query',
		{
			input: 'context.dev',
		},
	),
	operation(
		'webExtraction',
		'Extract Product',
		'extractProduct',
		'Extract one product from a URL',
		'POST',
		'/brand/ai/product',
		'body',
		{
			url: 'https://context.dev',
		},
	),
	operation(
		'webExtraction',
		'Extract Products',
		'extractProducts',
		'Extract products from a brand website',
		'POST',
		'/brand/ai/products',
		'body',
		{
			domain: 'context.dev',
			maxProducts: 5,
		},
	),

	operation(
		'brandIntelligence',
		'Retrieve Brand',
		'retrieveBrand',
		'Retrieve brand data by domain, name, email, ticker, URL, or transaction',
		'POST',
		'/brand/retrieve',
		'body',
		{
			type: 'by_domain',
			domain: 'context.dev',
		},
	),
	operation(
		'brandIntelligence',
		'Search Brands',
		'searchBrands',
		'Search Context.dev brand records',
		'GET',
		'/brand/search',
		'query',
		{
			query: 'Context.dev',
		},
	),

	operation(
		'news',
		'Search Company News',
		'searchCompanyNews',
		'Search recent news for a company',
		'POST',
		'/news/search',
		'body',
		{
			searchBy: { type: 'entity', entity: { type: 'domain', domain: 'context.dev' } },
			limit: 10,
		},
	),

	operation(
		'parsing',
		'Parse File',
		'parseFile',
		'Convert a binary file into Markdown',
		'POST',
		'/parse',
		'binary',
	),

	operation(
		'people',
		'Enrich Person',
		'enrichPerson',
		'Enrich a person from identity clues',
		'POST',
		'/people/enrich',
		'body',
		{
			email: 'person@example.com',
		},
	),

	operation(
		'monitors',
		'Create Monitor',
		'createMonitor',
		'Create a page or sitemap monitor',
		'POST',
		'/monitors',
		'body',
		{
			name: 'Context.dev pricing monitor',
			target: { type: 'page', url: 'https://context.dev/pricing' },
		},
	),
	operation(
		'monitors',
		'List Monitors',
		'listMonitors',
		'List monitors with filters and pagination',
		'GET',
		'/monitors',
		'query',
		{},
	),
	operation(
		'monitors',
		'Get Monitor',
		'getMonitor',
		'Retrieve one monitor',
		'GET',
		'/monitors/{monitor_id}',
		'none',
		undefined,
		['monitor_id'],
	),
	operation(
		'monitors',
		'Update Monitor',
		'updateMonitor',
		'Update one monitor',
		'PATCH',
		'/monitors/{monitor_id}',
		'body',
		{ status: 'paused' },
		['monitor_id'],
	),
	operation(
		'monitors',
		'Delete Monitor',
		'deleteMonitor',
		'Delete one monitor',
		'DELETE',
		'/monitors/{monitor_id}',
		'none',
		undefined,
		['monitor_id'],
		true,
	),
	operation(
		'monitors',
		'List Monitor Runs',
		'listMonitorRuns',
		'List runs for one monitor',
		'GET',
		'/monitors/{monitor_id}/runs',
		'query',
		{},
		['monitor_id'],
	),
	operation(
		'monitors',
		'Get Monitor Run',
		'getMonitorRun',
		'Retrieve one monitor run',
		'GET',
		'/monitors/{monitor_id}/runs/{run_id}',
		'none',
		undefined,
		['monitor_id', 'run_id'],
	),
	operation(
		'monitors',
		'List Monitor Changes',
		'listMonitorChanges',
		'List changes for one monitor',
		'GET',
		'/monitors/{monitor_id}/changes',
		'query',
		{},
		['monitor_id'],
	),
	operation(
		'monitors',
		'List All Runs',
		'listAllRuns',
		'List runs across all monitors',
		'GET',
		'/monitors/runs',
		'query',
		{},
	),
	operation(
		'monitors',
		'Get Credit Usage',
		'getCreditUsage',
		'Get monitor credit usage',
		'GET',
		'/monitors/credit-usage',
		'query',
		{},
	),
	operation(
		'monitors',
		'Get Limits',
		'getLimits',
		'Get monitor account limits',
		'GET',
		'/monitors/limits',
		'none',
	),
	operation(
		'monitors',
		'List All Changes',
		'listAllChanges',
		'List changes across all monitors',
		'GET',
		'/monitors/changes',
		'query',
		{},
	),
	operation(
		'monitors',
		'Get Change',
		'getChange',
		'Retrieve one detected change',
		'GET',
		'/monitors/changes/{change_id}',
		'none',
		undefined,
		['change_id'],
	),
	operation(
		'monitors',
		'Run Monitor',
		'runMonitor',
		'Run a monitor immediately',
		'POST',
		'/monitors/{monitor_id}/run',
		'none',
		undefined,
		['monitor_id'],
	),
	operation(
		'monitors',
		'Rotate Webhook Secret',
		'rotateWebhookSecret',
		'Rotate a monitor webhook secret',
		'POST',
		'/monitors/{monitor_id}/webhook/rotate-secret',
		'none',
		undefined,
		['monitor_id'],
		true,
	),

	operation(
		'batch',
		'Submit Batch',
		'submitBatch',
		'Submit a scrape or crawl batch',
		'POST',
		'/batch/submit',
		'body',
		{
			input: { mode: 'scrape', data: { format: 'markdown', urls: ['https://context.dev'] } },
		},
		undefined,
		false,
		true,
	),
	operation(
		'batch',
		'List Batches',
		'listBatches',
		'List batches with filters and pagination',
		'GET',
		'/batch/list',
		'query',
		{},
	),
	operation(
		'batch',
		'Get Batch',
		'getBatch',
		'Retrieve one batch',
		'GET',
		'/batch/{batch_id}',
		'none',
		undefined,
		['batch_id'],
	),
	operation(
		'batch',
		'Delete Batch',
		'deleteBatch',
		'Delete one batch',
		'DELETE',
		'/batch/{batch_id}',
		'none',
		undefined,
		['batch_id'],
		true,
	),
	operation(
		'batch',
		'Get Batch Results',
		'getBatchResults',
		'Get paginated results for one batch',
		'GET',
		'/batch/{batch_id}/results',
		'query',
		{},
		['batch_id'],
	),
	operation(
		'batch',
		'Cancel Batch',
		'cancelBatch',
		'Cancel a running batch',
		'POST',
		'/batch/{batch_id}/cancel',
		'none',
		undefined,
		['batch_id'],
		true,
	),

	operation(
		'webhooks',
		'List Deliveries',
		'listDeliveries',
		'List batch or monitor webhook deliveries',
		'POST',
		'/webhooks/deliveries',
		'body',
		{ type: 'batch' },
	),
	operation(
		'webhooks',
		'Get Delivery',
		'getDelivery',
		'Retrieve one webhook delivery',
		'GET',
		'/webhooks/deliveries/{delivery_id}',
		'none',
		undefined,
		['delivery_id'],
	),
	operation(
		'webhooks',
		'List Delivery Attempts',
		'listDeliveryAttempts',
		'List attempts for a webhook delivery',
		'GET',
		'/webhooks/deliveries/{delivery_id}/attempts',
		'query',
		{},
		['delivery_id'],
	),
	operation(
		'webhooks',
		'Retry Delivery',
		'retryDelivery',
		'Retry a webhook delivery',
		'POST',
		'/webhooks/deliveries/{delivery_id}/retry',
		'body',
		{},
		['delivery_id'],
		false,
		true,
	),

	operation(
		'utility',
		'Prefetch Data',
		'prefetchData',
		'Warm Context.dev caches for brand or styleguide data',
		'POST',
		'/utility/prefetch',
		'body',
		{
			type: 'brand',
			identifier: { domain: 'context.dev' },
		},
	),
];

export function findContextOperation(
	resource: string,
	value: string,
): ContextOperationDefinition | undefined {
	return contextOperations.find(
		(operationDefinition) =>
			operationDefinition.resource === resource && operationDefinition.value === value,
	);
}

function operation(
	resource: ContextResource,
	name: string,
	value: string,
	description: string,
	method: IHttpRequestMethods,
	path: string,
	requestKind: ContextRequestKind,
	example?: Record<string, unknown>,
	pathParameters?: string[],
	requiresConfirmation = false,
	supportsIdempotencyKey = false,
): ContextOperationDefinition {
	return {
		resource,
		name,
		value,
		action: name.toLowerCase(),
		description,
		method,
		path,
		requestKind,
		example,
		pathParameters,
		requiresConfirmation,
		supportsIdempotencyKey,
	};
}
